"""Translation: vulgate-clementine · Book: est

AUTO-GENERATED by scripts/extract_translation.py.
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "vulgate-clementine"
BOOK = "est"
VERSES = [
    (1, 1, "In diebus Assueri, qui regnavit ab India usque Æthiopiam super centum viginti septem provincias,"),
    (1, 2, "quando sedit in solio regni sui, Susan civitas regni ejus exordium fuit."),
    (
        1,
        3,
        "Tertio igitur anno imperii sui fecit grande convivium cunctis principibus et pueris suis, fortissimis Persarum, et Medorum inclytis, et præfectis provinciarum coram se,",
    ),
    (
        1,
        4,
        "ut ostenderet divitias gloriæ regni sui, ac magnitudinem atque jactantiam potentiæ suæ, multo tempore, centum videlicet et octoginta diebus.",
    ),
    (
        1,
        5,
        "Cumque implerentur dies convivii, invitavit omnem populum, qui inventus est in Susan, a maximo usque ad minimum: et jussit septem diebus convivium præparari in vestibulo horti, et nemoris quod regio cultu et manu consitum erat.",
    ),
    (
        1,
        6,
        "Et pendebant ex omni parte tentoria ærii coloris et carbasini ac hyacinthini, sustentata funibus byssinis atque purpureis, qui eburneis circulis inserti erant, et columnis marmoreis fulciebantur. Lectuli quoque aurei et argentei, super pavimentum smaragdino et pario stratum lapide, dispositi erant: quod mira varietate pictura decorabat.",
    ),
    (
        1,
        7,
        "Bibebant autem qui invitati erant aureis poculis, et aliis atque aliis vasis cibi inferebantur. Vinum quoque, ut magnificentia regia dignum erat, abundans, et præcipuum ponebatur.",
    ),
    (
        1,
        8,
        "Nec erat qui nolentes cogeret ad bibendum, sed sicut rex statuerat, præponens mensis singulos de principibus suis ut sumeret unusquisque quod vellet.",
    ),
    (1, 9, "Vasthi quoque regina fecit convivium feminarum in palatio, ubi rex Assuerus manere consueverat."),
    (
        1,
        10,
        "Itaque die septimo, cum rex esset hilarior, et post nimiam potationem incaluisset mero, præcepit Maumam, et Bazatha, et Harbona, et Bagatha, et Abgatha, et Zethar, et Charchas, septem eunuchis qui in conspectu ejus ministrabant,",
    ),
    (
        1,
        11,
        "ut introducerent reginam Vasthi coram rege, posito super caput ejus diademate, ut ostenderet cunctis populis et principibus pulchritudinem illius: erat enim pulchra valde.",
    ),
    (
        1,
        12,
        "Quæ renuit, et ad regis imperium quod per eunuchos mandaverat, venire contempsit. Unde iratus rex, et nimio furore succensus,",
    ),
    (
        1,
        13,
        "interrogavit sapientes, qui ex more regio semper ei aderant, et illorum faciebat cuncta consilio, scientium leges, ac jura majorum",
    ),
    (
        1,
        14,
        "(erant autem primi et proximi, Charsena, et Sethar, et Admatha, et Tharsis, et Mares, et Marsana, et Mamuchan, septem duces Persarum, atque Medorum, qui videbant faciem regis, et primi post eum residere soliti erant):",
    ),
    (
        1,
        15,
        "cui sententiæ Vasthi regina subjaceret, quæ Assueri regis imperium, quod per eunuchos mandaverat, facere noluisset.",
    ),
    (
        1,
        16,
        "Responditque Mamuchan, audiente rege atque principibus: Non solum regem læsit regina Vasthi, sed et omnes populos et principes qui sunt in cunctis provinciis regis Assueri.",
    ),
    (
        1,
        17,
        "Egredietur enim sermo reginæ ad omnes mulieres, ut contemnant viros suos, et dicant: Rex Assuerus jussit ut regina Vasthi intraret ad eum, et illa noluit.",
    ),
    (
        1,
        18,
        "Atque hoc exemplo omnes principum conjuges Persarum atque Medorum parvipendent imperia maritorum: unde regis justa est indignatio.",
    ),
    (
        1,
        19,
        "Si tibi placet, egrediatur edictum a facie tua, et scribatur juxta legem Persarum atque Medorum, quam præteriri illicitum est, ut nequaquam ultra Vasthi ingrediatur ad regem, sed regnum illius altera, quæ melior est illa, accipiat.",
    ),
    (
        1,
        20,
        "Et hoc in omne (quod latissimum est) provinciarum tuarum divulgetur imperium, et cunctæ uxores, tam majorum quam minorum, deferant maritis suis honorem.",
    ),
    (1, 21, "Placuit consilium ejus regi et principibus: fecitque rex juxta consilium Mamuchan,"),
    (
        1,
        22,
        "et misit epistolas ad universas provincias regni sui, ut quæque gens audire et legere poterat, diversis linguis et litteris, esse viros principes ac majores in domibus suis: et hoc per cunctos populos divulgari.",
    ),
    (
        2,
        1,
        "His ita gestis, postquam regis Assueri indignatio deferbuerat, recordatus est Vasthi, et quæ fecisset, vel quæ passa esset:",
    ),
    (2, 2, "dixeruntque pueri regis ac ministri ejus: Quærantur regi puellæ virgines ac speciosæ,"),
    (
        2,
        3,
        "et mittantur qui considerent per universas provincias puellas speciosas et virgines: et adducant eas ad civitatem Susan, et tradant eas in domum feminarum sub manu Egei eunuchi, qui est præpositus et custos mulierum regiarum: et accipiant mundum muliebrem, et cetera ad usus necessaria.",
    ),
    (
        2,
        4,
        "Et quæcumque inter omnes oculis regis placuerit, ipsa regnet pro Vasthi. Placuit sermo regi: et ita, ut suggesserant, jussit fieri.",
    ),
    (
        2,
        5,
        "Erat vir Judæus in Susan civitate, vocabulo Mardochæus filius Jair, filii Semei, filii Cis, de stirpe Jemini,",
    ),
    (
        2,
        6,
        "qui translatus fuerat de Jerusalem eo tempore quo Jechoniam regem Juda Nabuchodonosor rex Babylonis transtulerat,",
    ),
    (
        2,
        7,
        "qui fuit nutritius filiæ fratris sui Edissæ, quæ altero nomine vocabatur Esther, et utrumque parentem amiserat: pulchra nimis, et decora facie. Mortuisque patre ejus ac matre, Mardochæus sibi eam adoptavit in filiam.",
    ),
    (
        2,
        8,
        "Cumque percrebruisset regis imperium, et juxta mandatum illius multæ pulchræ virgines adducerentur Susan, et Egeo traderentur eunucho, Esther quoque inter ceteras puellas ei tradita est, ut servaretur in numero feminarum.",
    ),
    (
        2,
        9,
        "Quæ placuit ei, et invenit gratiam in conspectu illius. Et præcepit eunucho, ut acceleraret mundum muliebrem, et traderet ei partes suas, et septem puellas speciosissimas de domo regis, et tam ipsam quam pedissequas ejus ornaret atque excoleret.",
    ),
    (
        2,
        10,
        "Quæ noluit indicare ei populum et patriam suam: Mardochæus enim præceperat ei, ut de hac re omnino reticeret:",
    ),
    (
        2,
        11,
        "qui deambulabat quotidie ante vestibulum domus, in qua electæ virgines servabantur, curam agens salutis Esther, et scire volens quid ei accideret.",
    ),
    (
        2,
        12,
        "Cum autem venisset tempus singularum per ordinem puellarum ut intrarent ad regem, expletis omnibus quæ ad cultum muliebrem pertinebant, mensis duodecimus vertebatur: ita dumtaxat, ut sex mensibus oleo ungerentur myrrhino, et aliis sex quibusdam pigmentis et aromatibus uterentur.",
    ),
    (
        2,
        13,
        "Ingredientesque ad regem, quidquid postulassent ad ornatum pertinens, accipiebant: et ut eis placuerat, compositæ de triclinio feminarum ad regis cubiculum transibant.",
    ),
    (
        2,
        14,
        "Et quæ intraverat vespere, egrediebatur mane, atque inde in secundas ædes deducebatur, quæ sub manu Susagazi eunuchi erant, qui concubinis regis præsidebat: nec habebat potestatem ad regem ultra redeundi, nisi voluisset rex, et eam venire jussisset ex nomine.",
    ),
    (
        2,
        15,
        "Evoluto autem tempore per ordinem, instabat dies quo Esther filia Abihail fratris Mardochæi, quam sibi adoptaverat in filiam, deberet intrare ad regem. Quæ non quæsivit muliebrem cultum, sed quæcumque voluit Egeus eunuchus custos virginum, hæc ei ad ornatum dedit. Erat enim formosa valde, et incredibili pulchritudine: omnium oculis gratiosa et amabilis videbatur.",
    ),
    (2, 16, "Ducta est itaque ad cubiculum regis Assueri mense decimo, qui vocatur Tebeth, septimo anno regni ejus."),
    (
        2,
        17,
        "Et adamavit eam rex plus quam omnes mulieres, habuitque gratiam et misericordiam coram eo super omnes mulieres: et posuit diadema regni in capite ejus, fecitque eam regnare in loco Vasthi.",
    ),
    (
        2,
        18,
        "Et jussit convivium præparari permagnificum cunctis principibus et servis suis pro conjunctione et nuptiis Esther. Et dedit requiem universis provinciis, ac dona largitus est juxta magnificentiam principalem.",
    ),
    (2, 19, "Cumque secundo quærerentur virgines et congregarentur, Mardochæus manebat ad januam regis:"),
    (
        2,
        20,
        "necdum prodiderat Esther patriam et populum suum, juxta mandatum ejus. Quidquid enim ille præcipiebat, observabat Esther: et ita cuncta faciebat ut eo tempore solita erat, quo eam parvulam nutriebat.",
    ),
    (
        2,
        21,
        "Eo igitur tempore, quo Mardochæus ad regis januam morabatur, irati sunt Bagathan et Thares duo eunuchi regis, qui janitores erant, et in primo palatii limine præsidebant: volueruntque insurgere in regem, et occidere eum.",
    ),
    (
        2,
        22,
        "Quod Mardochæum non latuit, statimque nuntiavit reginæ Esther: et illa regi ex nomine Mardochæi, qui ad se rem detulerat.",
    ),
    (
        2,
        23,
        "Quæsitum est, et inventum: et appensus est uterque eorum in patibulo. Mandatumque est historiis, et annalibus traditum coram rege.",
    ),
    (
        3,
        1,
        "Post hæc rex Assuerus exaltavit Aman filium Amadathi, qui erat de stirpe Agag: et posuit solium ejus super omnes principes quos habebat.",
    ),
    (
        3,
        2,
        "Cunctique servi regis, qui in foribus palatii versabantur, flectebant genua, et adorabant Aman: sic enim præceperat eis imperator: solus Mardochæus non flectebat genu, neque adorabat eum.",
    ),
    (
        3,
        3,
        "Cui dixerunt pueri regis, qui ad fores palatii præsidebant: Cur præter ceteros non observas mandatum regis?",
    ),
    (
        3,
        4,
        "Cumque hoc crebrius dicerent, et ille nollet audire, nuntiaverunt Aman, scire cupientes utrum perseveraret in sententia: dixerat enim eis se esse Judæum.",
    ),
    (
        3,
        5,
        "Quod cum audisset Aman, et experimento probasset quod Mardochæus non flecteret sibi genu, nec se adoraret, iratus est valde,",
    ),
    (
        3,
        6,
        "et pro nihilo duxit in unum Mardochæum mittere manus suas: audierat enim quod esset gentis Judææ; magisque voluit omnem Judæorum, qui erant in regno Assueri, perdere nationem.",
    ),
    (
        3,
        7,
        "Mense primo (cujus vocabulum est Nisan), anno duodecimo regni Assueri, missa est sors in urnam, quæ hebraice dicitur phur, coram Aman, quo die et quo mense gens Judæorum deberet interfici: et exivit mensis duodecimus, qui vocatur Adar.",
    ),
    (
        3,
        8,
        "Dixitque Aman regi Assuero: Est populus per omnes provincias regni tui dispersus, et a se mutuo separatus, novis utens legibus et cæremoniis, insuper et regis scita contemnens: et optime nosti quod non expediat regno tuo ut insolescat per licentiam.",
    ),
    (3, 9, "Si tibi placet, decerne, ut pereat, et decem millia talentorum appendam arcariis gazæ tuæ."),
    (
        3,
        10,
        "Tulit ergo rex annulum, quo utebatur, de manu sua, et dedit eum Aman filio Amadathi de progenie Agag, hosti Judæorum,",
    ),
    (3, 11, "dixitque ad eum: Argentum, quod tu polliceris, tuum sit; de populo age quod tibi placet."),
    (
        3,
        12,
        "Vocatique sunt scribæ regis mense primo Nisan, tertiadecima die ejusdem mensis: et scriptum est, ut jusserat Aman, ad omnes satrapas regis, et judices provinciarum, diversarumque gentium, ut quæque gens legere poterat et audire pro varietate linguarum ex nomine regis Assueri: et litteræ signatæ ipsius annulo",
    ),
    (
        3,
        13,
        "missæ sunt per cursores regis ad universas provincias, ut occiderent atque delerent omnes Judæos, a puero usque ad senem, parvulos et mulieres, uno die, hoc est tertiodecimo mensis duodecimi, qui vocatur Adar; et bona eorum diriperent.",
    ),
    (3, 14, "Summa autem epistolarum hæc fuit, ut omnes provinciæ scirent, et pararent se ad prædictam diem."),
    (
        3,
        15,
        "Festinabant cursores, qui missi erant, regis imperium explere. Statimque in Susan pependit edictum, rege et Aman celebrante convivium, et cunctis Judæis, qui in urbe erant, flentibus.",
    ),
    (
        4,
        1,
        "Quæ cum audisset Mardochæus, scidit vestimenta sua, et indutus est sacco, spargens cinerem capiti: et in platea mediæ civitatis voce magna clamabat, ostendens amaritudinem animi sui,",
    ),
    (4, 2, "et hoc ejulatu usque ad fores palatii gradiens. Non enim erat licitum indutum sacco aulam regis intrare."),
    (
        4,
        3,
        "In omnibus quoque provinciis, oppidis, ac locis, ad quæ crudele regis dogma pervenerat, planctus ingens erat apud Judæos, jejunium, ululatus, et fletus, sacco et cinere multis pro strato utentibus.",
    ),
    (
        4,
        4,
        "Ingressæ autem sunt puellæ Esther et eunuchi, nuntiaveruntque ei. Quod audiens consternata est, et vestem misit, ut ablato sacco induerent eum: quam accipere noluit.",
    ),
    (
        4,
        5,
        "Accitoque Athach eunucho, quem rex ministrum ei dederat, præcepit ei ut iret ad Mardochæum, et disceret ab eo cur hoc faceret.",
    ),
    (4, 6, "Egressusque Athach, ivit ad Mardochæum stantem in platea civitatis, ante ostium palatii:"),
    (
        4,
        7,
        "qui indicavit ei omnia quæ acciderant: quomodo Aman promisisset ut in thesauros regis pro Judæorum nece inferret argentum.",
    ),
    (
        4,
        8,
        "Exemplar quoque edicti, quod pendebat in Susan, dedit ei, ut reginæ ostenderet, et moneret eam ut intraret ad regem et deprecaretur eum pro populo suo.",
    ),
    (4, 9, "Regressus Athach, nuntiavit Esther omnia quæ Mardochæus dixerat."),
    (4, 10, "Quæ respondit ei, et jussit ut diceret Mardochæo:"),
    (
        4,
        11,
        "Omnes servi regis, et cunctæ, quæ sub ditione ejus sunt, norunt provinciæ, quod sive vir, sive mulier non vocatus, interius atrium regis intraverit, absque ulla cunctatione statim interficiatur: nisi forte rex auream virgam ad eum tetenderit pro signo clementiæ, atque ita possit vivere. Ego igitur quomodo ad regem intrare potero, quæ triginta jam diebus non sum vocata ad eum?",
    ),
    (4, 12, "Quod cum audisset Mardochæus,"),
    (
        4,
        13,
        "rursum mandavit Esther, dicens: Ne putes quod animam tuam tantum liberes, quia in domo regis es præ cunctis Judæis:",
    ),
    (
        4,
        14,
        "si enim nunc silueris, per aliam occasionem liberabuntur Judæi: et tu, et domus patris tui, peribitis. Et quis novit utrum idcirco ad regnum veneris, ut in tali tempore parareris?",
    ),
    (4, 15, "Rursumque Esther hæc Mardochæo verba mandavit:"),
    (
        4,
        16,
        "Vade, et congrega omnes Judæos quos in Susan repereris, et orate pro me. Non comedatis et non bibatis tribus diebus et tribus noctibus: et ego cum ancillis meis similiter jejunabo, et tunc ingrediar ad regem contra legem faciens, non vocata, tradensque me morti et periculo.",
    ),
    (4, 17, "Ivit itaque Mardochæus, et fecit omnia quæ ei Esther præceperat."),
    (
        5,
        1,
        "Die autem tertio induta est Esther regalibus vestimentis, et stetit in atrio domus regiæ, quod erat interius, contra basilicam regis: at ille sedebat super solium suum in consistorio palatii contra ostium domus.",
    ),
    (
        5,
        2,
        "Cumque vidisset Esther reginam stantem, placuit oculis ejus, et extendit contra eam virgam auream, quam tenebat manu: quæ accedens, osculata est summitatem virgæ ejus.",
    ),
    (
        5,
        3,
        "Dixitque ad eam rex: Quid vis, Esther regina? quæ est petitio tua? etiam si dimidiam partem regni petieris, dabitur tibi.",
    ),
    (
        5,
        4,
        "At illa respondit: Si regi placet, obsecro ut venias ad me hodie, et Aman tecum, ad convivium quod paravi.",
    ),
    (
        5,
        5,
        "Statimque rex: Vocate, inquit, cito Aman ut Esther obediat voluntati. Venerunt itaque rex et Aman ad convivium, quod eis regina paraverat.",
    ),
    (
        5,
        6,
        "Dixitque ei rex, postquam vinum biberat abundanter: Quid petis ut detur tibi? et pro qua re postulas? etiam si dimidiam partem regni mei petieris, impetrabis.",
    ),
    (5, 7, "Cui respondit Esther: Petitio mea, et preces sunt istæ:"),
    (
        5,
        8,
        "si inveni in conspectu regis gratiam, et si regi placet ut det mihi quod postulo, et meam impleat petitionem: veniat rex et Aman ad convivium quod paravi eis, et cras aperiam regi voluntatem meam.",
    ),
    (
        5,
        9,
        "Egressus est itaque illo die Aman lætus et alacer. Cumque vidisset Mardochæum sedentem ante fores palatii, et non solum non assurrexisse sibi, sed nec motum quidem de loco sessionis suæ, indignatus est valde:",
    ),
    (5, 10, "et dissimulata ira reversus in domum suam, convocavit ad se amicos suos, et Zares uxorem suam,"),
    (
        5,
        11,
        "et exposuit illis magnitudinem divitiarum suarum, filiorumque turbam, et quanta eum gloria super omnes principes et servos suos rex elevasset.",
    ),
    (
        5,
        12,
        "Et post hæc ait: Regina quoque Esther nullum alium vocavit ad convivium cum rege præter me: apud quam etiam cras cum rege pransurus sum.",
    ),
    (
        5,
        13,
        "Et cum hæc omnia habeam, nihil me habere puto, quamdiu videro Mardochæum Judæum sedentem ante fores regias.",
    ),
    (
        5,
        14,
        "Responderuntque ei Zares uxor ejus, et ceteri amici: Jube parari excelsam trabem, habentem altitudinis quinquaginta cubitos, et dic mane regi ut appendatur super eam Mardochæus, et sic ibis cum rege lætus ad convivium. Placuit ei consilium, et jussit excelsam parari crucem.",
    ),
    (
        6,
        1,
        "Noctem illam duxit rex insomnem, jussitque sibi afferri historias et annales priorum temporum. Quæ cum illo præsente legerentur,",
    ),
    (
        6,
        2,
        "ventum est ad illum locum ubi scriptum erat quomodo nuntiasset Mardochæus insidias Bagathan et Thares eunuchorum, regem Assuerum jugulare cupientium.",
    ),
    (
        6,
        3,
        "Quod cum audisset rex, ait: Quid pro hac fide honoris ac præmii Mardochæus consecutus est? Dixerunt ei servi illius ac ministri: Nihil omnino mercedis accepit.",
    ),
    (
        6,
        4,
        "Statimque rex: Quis est, inquit, in atrio? Aman quippe interius atrium domus regiæ intraverat, ut suggereret regi, et juberet Mardochæum affigi patibulo, quod ei fuerat præparatum.",
    ),
    (6, 5, "Responderunt pueri: Aman stat in atrio. Dixitque rex: Ingrediatur."),
    (
        6,
        6,
        "Cumque esset ingressus, ait illi: Quid debet fieri viro, quem rex honorare desiderat? Cogitans autem in corde suo Aman, et reputans quod nullum alium rex, nisi se, vellet honorare,",
    ),
    (6, 7, "respondit: Homo, quem rex honorare cupit,"),
    (
        6,
        8,
        "debet indui vestibus regiis, et imponi super equum, qui de sella regis est, et accipere regium diadema super caput suum:",
    ),
    (
        6,
        9,
        "et primus de regiis principibus ac tyrannis teneat equum ejus, et per plateam civitatis incedens clamet, et dicat: Sic honorabitur, quemcumque voluerit rex honorare.",
    ),
    (
        6,
        10,
        "Dixitque ei rex: Festina, et sumpta stola et equo, fac, ut locutus es, Mardochæo Judæo, qui sedet ante fores palatii. Cave ne quidquam de his, quæ locutus es, prætermittas.",
    ),
    (
        6,
        11,
        "Tulit itaque Aman stolam et equum, indutumque Mardochæum in platea civitatis, et impositum equo præcedebat, atque clamabat: Hoc honore condignus est, quemcumque rex voluerit honorare.",
    ),
    (
        6,
        12,
        "Reversusque est Mardochæus ad januam palatii: et Aman festinavit ire in domum suam, lugens et operto capite:",
    ),
    (
        6,
        13,
        "narravitque Zares uxori suæ, et amicis, omnia quæ evenissent sibi. Cui responderunt sapientes quos habebat in consilio, et uxor ejus: Si de semine Judæorum est Mardochæus, ante quem cadere cœpisti, non poteris ei resistere, sed cades in conspectu ejus.",
    ),
    (
        6,
        14,
        "Adhuc illis loquentibus, venerunt eunuchi regis, et cito eum ad convivium, quod regina paraverat, pergere compulerunt.",
    ),
    (7, 1, "Intravit itaque rex et Aman, ut biberent cum regina."),
    (
        7,
        2,
        "Dixitque ei rex etiam secunda die, postquam vino incaluerat: Quæ est petitio tua, Esther, ut detur tibi? et quid vis fieri? etiam si dimidiam partem regni mei petieris, impetrabis.",
    ),
    (
        7,
        3,
        "Ad quem illa respondit: Si inveni gratiam in oculis tuis o rex, et si tibi placet, dona mihi animam meam pro qua rogo, et populum meum pro quo obsecro.",
    ),
    (
        7,
        4,
        "Traditi enim sumus ego et populus meus, ut conteramur, jugulemur, et pereamus. Atque utinam in servos et famulas venderemur: esset tolerabile malum, et gemens tacerem: nunc autem hostis noster est, cujus crudelitas redundat in regem.",
    ),
    (7, 5, "Respondensque rex Assuerus, ait: Quis est iste, et cujus potentiæ, ut hæc audeat facere?"),
    (
        7,
        6,
        "Dixitque Esther: Hostis et inimicus noster pessimus iste est Aman. Quod ille audiens, illico obstupuit, vultum regis ac reginæ ferre non sustinens.",
    ),
    (
        7,
        7,
        "Rex autem iratus surrexit, et de loco convivii intravit in hortum arboribus consitum. Aman quoque surrexit ut rogaret Esther reginam pro anima sua: intellexit enim a rege sibi paratum malum.",
    ),
    (
        7,
        8,
        "Qui cum reversus esset de horto nemoribus consito, et intrasset convivii locum, reperit Aman super lectulum corruisse in quo jacebat Esther, et ait: Etiam reginam vult opprimere, me præsente, in domo mea. Necdum verbum de ore regis exierat, et statim operuerunt faciem ejus.",
    ),
    (
        7,
        9,
        "Dixitque Harbona, unus de eunuchis, qui stabant in ministerio regis: En lignum quod paraverat Mardochæo, qui locutus est pro rege, stat in domo Aman, habens altitudinis quinquaginta cubitos. Cui dixit rex: Appendite eum in eo.",
    ),
    (7, 10, "Suspensus est itaque Aman in patibulo quod paraverat Mardochæo: et regis ira quievit."),
    (
        8,
        1,
        "Die illo dedit rex Assuerus Esther reginæ domum Aman adversarii Judæorum, et Mardochæus ingressus est ante faciem regis. Confessa est enim ei Esther quod esset patruus suus.",
    ),
    (
        8,
        2,
        "Tulitque rex annulum, quem ab Aman recipi jusserat, et tradidit Mardochæo. Esther autem constituit Mardochæum super domum suam.",
    ),
    (
        8,
        3,
        "Nec his contenta, procidit ad pedes regis, flevitque, et locuta ad eum oravit ut malitiam Aman Agagitæ, et machinationes ejus pessimas quas excogitaverat contra Judæos, juberet irritas fieri.",
    ),
    (
        8,
        4,
        "At ille ex more sceptrum aureum protendit manu, quo signum clementiæ monstrabatur: illaque consurgens stetit ante eum,",
    ),
    (
        8,
        5,
        "et ait: Si placet regi, et si inveni gratiam in oculis ejus, et deprecatio mea non ei videtur esse contraria, obsecro ut novis epistolis, veteres Aman litteræ, insidiatoris et hostis Judæorum, quibus eos in cunctis regis provinciis perire præceperat, corrigantur.",
    ),
    (8, 6, "Quomodo enim potero sustinere necem et interfectionem populi mei?"),
    (
        8,
        7,
        "Responditque rex Assuerus Esther reginæ, et Mardochæo Judæo: Domum Aman concessi Esther, et ipsum jussi affigi cruci, quia ausus est manum mittere in Judæos.",
    ),
    (
        8,
        8,
        "Scribite ergo Judæis, sicut vobis placet, regis nomine, signantes litteras annulo meo. Hæc enim consuetudo erat, ut epistolis, quæ ex regis nomine mittebantur et illius annulo signatæ erant, nemo auderet contradicere.",
    ),
    (
        8,
        9,
        "Accitisque scribis et librariis regis (erat autem tempus tertii mensis, qui appellatur Siban) vigesima et tertia die illius scriptæ sunt epistolæ, ut Mardochæus voluerat, ad Judæos, et ad principes, procuratoresque et judices, qui centum viginti septem provinciis ab India usque ad Æthiopiam præsidebant: provinciæ atque provinciæ, populo et populo juxta linguas et litteras suas, et Judæis, prout legere poterant et audire.",
    ),
    (
        8,
        10,
        "Ipsæque epistolæ, quæ regis nomine mittebantur, annulo ipsius obsignatæ sunt, et missæ per veredarios: qui per omnes provincias discurrentes, veteres litteras novis nuntiis prævenirent.",
    ),
    (
        8,
        11,
        "Quibus imperavit rex, ut convenirent Judæos per singulas civitates, et in unum præciperent congregari ut starent pro animabus suis, et omnes inimicos suos cum conjugibus ac liberis et universis domibus, interficerent atque delerent, et spolia eorum diriperent.",
    ),
    (8, 12, "Et constituta est per omnes provincias una ultionis dies, id est tertiadecima mensis duodecimi Adar."),
    (
        8,
        13,
        "Summaque epistolæ hæc fuit, ut in omnibus terris ac populis qui regis Assueri subjacebant imperio, notum fieret paratos esse Judæos ad capiendam vindictam de hostibus suis.",
    ),
    (8, 14, "Egressique sunt veredarii celeres nuntia perferentes, et edictum regis pependit in Susan."),
    (
        8,
        15,
        "Mardochæus autem de palatio et de conspectu regis egrediens, fulgebat vestibus regiis, hyacinthinis videlicet et æriis, coronam auream portans in capite, et amictus serico pallio atque purpureo. Omnisque civitas exultavit atque lætata est.",
    ),
    (8, 16, "Judæis autem nova lux oriri visa est, gaudium, honor, et tripudium."),
    (
        8,
        17,
        "Apud omnes populos, urbes, atque provincias, quocumque regis jussa veniebant, mira exultatio, epulæ atque convivia, et festus dies: in tantum ut plures alterius gentis et sectæ eorum religioni et cæremoniis jungerentur. Grandis enim cunctos judaici nominis terror invaserat.",
    ),
    (
        9,
        1,
        "Igitur duodecimi mensis, quem Adar vocari ante jam diximus, tertiadecima die, quando cunctis Judæis interfectio parabatur, et hostes eorum inhiabant sanguini, versa vice Judæi superiores esse cœperunt, et se de adversariis vindicare.",
    ),
    (
        9,
        2,
        "Congregatique sunt per singulas civitates, oppida, et loca, ut extenderent manum contra inimicos, et persecutores suos. Nullusque ausus est resistere, eo quod omnes populos magnitudinis eorum formido penetrarat.",
    ),
    (
        9,
        3,
        "Nam et provinciarum judices, et duces, et procuratores, omnisque dignitas quæ singulis locis ac operibus præerat, extollebant Judæos timore Mardochæi,",
    ),
    (
        9,
        4,
        "quem principem esse palatii, et plurimum posse cognoverant: fama quoque nominis ejus crescebat quotidie, et per cunctorum ora volitabat.",
    ),
    (
        9,
        5,
        "Itaque percusserunt Judæi inimicos suos plaga magna, et occiderunt eos, reddentes eis quod sibi paraverant facere:",
    ),
    (
        9,
        6,
        "in tantum ut etiam in Susan quingentos viros interficerent, extra decem filios Aman Agagitæ hostis Judæorum: quorum ista sunt nomina:",
    ),
    (9, 7, "Pharsandatha, et Delphon, et Esphatha,"),
    (9, 8, "et Phoratha, et Adalia, et Aridatha,"),
    (9, 9, "et Phermesta, et Arisai, et Aridai, et Jezatha."),
    (9, 10, "Quos cum occidissent, prædas de substantiis eorum tangere noluerunt."),
    (9, 11, "Statimque numerus eorum, qui occisi erant in Susan, ad regem relatus est."),
    (
        9,
        12,
        "Qui dixit reginæ: In urbe Susan interfecerunt Judæi quingentos viros, et alios decem filios Aman: quantam putas eos exercere cædem in universis provinciis? quid ultra postulas, et quid vis ut fieri jubeam?",
    ),
    (
        9,
        13,
        "Cui illa respondit: Si regi placet, detur potestas Judæis, ut sicut fecerunt hodie in Susan, sic et cras faciant, et decem filii Aman in patibulis suspendantur.",
    ),
    (9, 14, "Præcepitque rex ut ita fieret. Statimque in Susan pependit edictum, et decem filii Aman suspensi sunt."),
    (
        9,
        15,
        "Congregatis Judæis quartadecima die mensis Adar, interfecti sunt in Susan trecenti viri: nec eorum ab illis direpta substantia est.",
    ),
    (
        9,
        16,
        "Sed et per omnes provincias quæ ditioni regis subjacebant, pro animabus suis steterunt Judæi, interfectis hostibus ac persecutoribus suis: in tantum ut septuaginta quinque millia occisorum implerentur, et nullus de substantiis eorum quidquam contingeret.",
    ),
    (
        9,
        17,
        "Dies autem tertiusdecimus mensis Adar primus apud omnes interfectionis fuit, et quartadecima die cædere desierunt. Quem constituerunt esse solemnem, ut in eo omni tempore deinceps vacarent epulis, gaudio, atque conviviis.",
    ),
    (
        9,
        18,
        "At hi, qui in urbe Susan cædem exercuerant, tertiodecimo et quartodecimo die ejusdem mensis in cæde versati sunt: quintodecimo autem die percutere desierunt. Et idcirco eumdem diem constituerunt solemnem epularum atque lætitiæ.",
    ),
    (
        9,
        19,
        "Hi vero Judæi, qui in oppidis non muratis ac villis morabantur, quartumdecimum diem mensis Adar conviviorum et gaudii decreverunt, ita ut exultent in eo, et mittant sibi mutuo partes epularum et ciborum.",
    ),
    (
        9,
        20,
        "Scripsit itaque Mardochæus omnia hæc, et litteris comprehensa misit ad Judæos qui in omnibus regis provinciis morabantur, tam in vicino positis, quam procul,",
    ),
    (
        9,
        21,
        "ut quartamdecimam et quintamdecimam diem mensis Adar pro festis susciperent, et revertente semper anno solemni celebrarent honore:",
    ),
    (
        9,
        22,
        "quia in ipsis diebus se ulti sunt Judæi de inimicis suis, et luctus atque tristitia in hilaritatem gaudiumque conversa sunt, essentque dies isti epularum atque lætitiæ, et mitterent sibi invicem ciborum partes, et pauperibus munuscula largirentur.",
    ),
    (
        9,
        23,
        "Susceperuntque Judæi in solemnem ritum cuncta quæ eo tempore facere cœperant, et quæ Mardochæus litteris facienda mandaverat.",
    ),
    (
        9,
        24,
        "Aman enim, filius Amadathi stirpis Agag, hostis et adversarius Judæorum, cogitavit contra eos malum, ut occideret illos atque deleret: et misit phur, quod nostra lingua vertitur in sortem.",
    ),
    (
        9,
        25,
        "Et postea ingressa est Esther ad regem, obsecrans ut conatus ejus litteris regis irriti fierent, et malum quod contra Judæos cogitaverat, reverteretur in caput ejus. Denique et ipsum et filios ejus affixerunt cruci,",
    ),
    (
        9,
        26,
        "atque ex illo tempore dies isti appellati sunt phurim, id est sortium: eo quod phur, id est sors, in urnam missa fuerit. Et cuncta quæ gesta sunt, epistolæ, id est, libri hujus volumine, continentur:",
    ),
    (
        9,
        27,
        "quæque sustinuerunt, et quæ deinceps immutata sunt, susceperunt Judæi super se et semen suum, et super cunctos qui religioni eorum voluerunt copulari, ut nulli liceat duos hos dies absque solemnitate transigere, quos scriptura testatur, et certa expetunt tempora, annis sibi jugiter succedentibus.",
    ),
    (
        9,
        28,
        "Isti sunt dies, quos nulla umquam delebit oblivio, et per singulas generationes cunctæ in toto orbe provinciæ celebrabunt: nec est ulla civitas, in qua dies phurim, id est sortium, non observentur a Judæis, et ab eorum progenie, quæ his cæremoniis obligata est.",
    ),
    (
        9,
        29,
        "Scripseruntque Esther regina filia Abihail, et Mardochæus Judæus, etiam secundam epistolam, ut omni studio dies ista solemnis sanciretur in posterum:",
    ),
    (
        9,
        30,
        "et miserunt ad omnes Judæos qui in centum viginti septem provinciis regis Assueri versabantur, ut haberent pacem, et susciperent veritatem,",
    ),
    (
        9,
        31,
        "observantes dies sortium, et suo tempore cum gaudio celebrarent: sicut constituerant Mardochæus et Esther, et illi observanda susceperunt a se, et a semine suo, jejunia, et clamores, et sortium dies,",
    ),
    (9, 32, "et omnia quæ libri hujus, qui vocatur Esther, historia continentur."),
    (10, 1, "Rex vero Assuerus omnem terram et cunctas maris insulas fecit tributarias:"),
    (
        10,
        2,
        "cujus fortitudo et imperium, et dignitas atque sublimitas, qua exaltavit Mardochæum, scripta sunt in libris Medorum, atque Persarum:",
    ),
    (
        10,
        3,
        "et quomodo Mardochæus judaici generis secundus a rege Assuero fuerit, et magnus apud Judæos, et acceptabilis plebi fratrum suorum, quærens bona populo suo, et loquens ea quæ ad pacem seminis sui pertinerent.",
    ),
]
