"""Translation: vulgate-clementine · Book: lje

AUTO-GENERATED by scripts/extract_translation.py.
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "vulgate-clementine"
BOOK = "lje"
VERSES = [
    (
        1,
        2,
        "Propter peccata quæ peccastis ante Deum, abducemini in Babyloniam captivi a Nabuchodonosor rege Babylonis.",
    ),
    (
        1,
        3,
        "Ingressi itaque in Babylonem, eritis ibi annis plurimis, et temporibus longis, usque ad generationes septem: post hoc autem educam vos inde cum pace.",
    ),
    (
        1,
        4,
        "Nunc autem videbitis in Babylonia deos aureos et argenteos, et lapideos et ligneos, in humeris portari, ostentantes metum gentibus.",
    ),
    (1, 5, "Videte ergo ne et vos similes efficiamini factis alienis, et metuatis, et metus vos capiat in ipsis."),
    (1, 6, "Visa itaque turba de retro et ab ante, adorantes dicite in cordibus vestris: Te oportet adorari, Domine."),
    (1, 7, "Angelus enim meus vobiscum est: ipse autem exquiram animas vestras."),
    (1, 8, "Nam lingua ipsorum polita a fabro; ipsa etiam inaurata et inargentata: falsa sunt, et non possunt loqui."),
    (1, 9, "Et sicut virgini amanti ornamenta, ita accepto auro fabricati sunt."),
    (
        1,
        10,
        "Coronas certe aureas habent super capita sua dii illorum: unde subtrahunt sacerdotes ab eis aurum et argentum, et erogant illud in semetipsos.",
    ),
    (
        1,
        11,
        "Dant autem et ex ipso prostitutis, et meretrices ornant: et iterum cum receperint illud a meretricibus, ornant deos suos.",
    ),
    (1, 12, "Hi autem non liberantur ab ærugine et tinea."),
    (
        1,
        13,
        "Opertis autem illis veste purpurea, extergunt faciem ipsorum propter pulverem domus qui est plurimus inter eos.",
    ),
    (1, 14, "Sceptrum autem habet ut homo, sicut judex regionis, qui in se peccantem non interficit."),
    (
        1,
        15,
        "Habet etiam in manu gladium et securim, se autem de bello et a latronibus non liberat. Unde vobis notum sit quia non sunt dii:",
    ),
    (1, 16, "non ergo timueritis eos. Sicut enim vas hominis confractum inutile efficitur, tales sunt et dii illorum."),
    (1, 17, "Constitutis illis in domo, oculi eorum pleni sunt pulvere a pedibus introëuntium."),
    (
        1,
        18,
        "Et sicut alicui qui regem offendit circumseptæ sunt januæ, aut sicut ad sepulchrum adductum mortuum: ita tutantur sacerdotes ostia clausuris et seris, ne a latronibus expolientur.",
    ),
    (
        1,
        19,
        "Lucernas accendunt illis, et quidem multas, ex quibus nullam videre possunt: sunt autem sicut trabes in domo.",
    ),
    (
        1,
        20,
        "Corda vero eorum dicunt elingere serpentes qui de terra sunt, dum comedunt eos, et vestimentum ipsorum, et non sentiunt.",
    ),
    (1, 21, "Nigræ fiunt facies eorum a fumo qui in domo fit."),
    (1, 22, "Supra corpus eorum et supra caput eorum volant noctuæ, et hirundines, et aves etiam, similiter et cattæ."),
    (1, 23, "Unde sciatis quia non sunt dii: ne ergo timueritis eos."),
    (
        1,
        24,
        "Aurum etiam quod habent ad speciem est: nisi aliquis exterserit æruginem, non fulgebunt: neque enim dum conflarentur, sentiebant.",
    ),
    (1, 25, "Ex omni pretio empta sunt, in quibus spiritus non inest ipsis."),
    (
        1,
        26,
        "Sine pedibus, in humeris portantur, ostentantes ignobilitatem suam hominibus: confundantur etiam qui colunt ea.",
    ),
    (
        1,
        27,
        "Propterea si ceciderint in terram, a semetipsis non consurgunt: neque si quis eum statuerit rectum, per semetipsum stabit: sed sicut mortuis munera eorum illis apponentur.",
    ),
    (
        1,
        28,
        "Hostias illorum vendunt sacerdotes ipsorum, et abutuntur: similiter et mulieres eorum decerpentes, neque infirmo, neque mendicanti, aliquid impertiunt.",
    ),
    (
        1,
        29,
        "De sacrificiis eorum fœtæ et menstruatæ contingunt. Sciens itaque ex his quia non sunt dii, ne timeatis eos.",
    ),
    (1, 30, "Unde enim vocantur dii? quia mulieres apponunt diis argenteis, et aureis, et ligneis:"),
    (
        1,
        31,
        "et in domibus eorum sacerdotes sedent habentes tunicas scissas, et capita et barbam rasam, quorum capita nuda sunt.",
    ),
    (1, 32, "Rugiunt autem clamantes contra deos suos sicut in cœna mortui."),
    (1, 33, "Vestimenta eorum auferunt sacerdotes, et vestiunt uxores suas et filios suos."),
    (
        1,
        34,
        "Neque si quid mali patiuntur ab aliquo, neque si quid boni, poterunt retribuere: neque regem constituere possunt, neque auferre.",
    ),
    (
        1,
        35,
        "Similiter neque dare divitias possunt, neque malum retribuere. Si quis illis votum voverit et non reddiderit, neque hoc requirunt.",
    ),
    (1, 36, "Hominem a morte non liberant, neque infirmum a potentiori eripiunt."),
    (1, 37, "Hominem cæcum ad visum non restituunt; de necessitate hominem non liberabunt."),
    (1, 38, "Viduæ non miserebuntur, neque orphanis benefacient."),
    (
        1,
        39,
        "Lapidibus de monte similes sunt dii illorum, lignei, et lapidei, et aurei, et argentei: qui autem colunt ea, confundentur.",
    ),
    (1, 40, "Quomodo ergo æstimandum est aut dicendum illos esse deos?"),
    (
        1,
        41,
        "Adhuc enim ipsis Chaldæis non honorantibus ea: qui cum audierint mutum non posse loqui, offerunt illud ad Bel, postulantes ab eo loqui:",
    ),
    (
        1,
        42,
        "quasi possint sentire qui non habent motum ! Et ipsi, cum intellexerint, relinquent ea: sensum enim non habent ipsi dii illorum.",
    ),
    (
        1,
        43,
        "Mulieres autem circumdatæ funibus in viis sedent, succendentes ossa olivarum: cum autem aliqua ex ipsis, attracta ab aliquo transeunte, dormierit cum eo, proximæ suæ exprobrat quod ea non sit digna habita, sicut ipsa, neque funis ejus diruptus sit.",
    ),
    (1, 44, "Omnia autem quæ illi fiunt, falsa sunt: quomodo æstimandum aut dicendum est illos esse deos?"),
    (1, 45, "A fabris autem et ab aurificibus facta sunt: nihil aliud erunt, nisi id quod volunt esse sacerdotes."),
    (
        1,
        46,
        "Artifices etiam ipsi, qui ea faciunt, non sunt multi temporis: numquid ergo possunt ea, quæ fabricata sunt ab ipsis, esse dii?",
    ),
    (1, 47, "Reliquerunt autem falsa et opprobrium postea futuris."),
    (1, 48, "Nam cum supervenerit illis prælium et mala, cogitant sacerdotes apud se ubi se abscondant cum illis."),
    (1, 49, "Quomodo ergo sentiri debeant quoniam dii sunt, qui nec de bello se liberant, neque de malis se eripiunt?"),
    (
        1,
        50,
        "Nam cum sint lignea, inaurata et inargentata, scietur postea quia falsa sunt ab universis gentibus et regibus: quæ manifesta sunt quia non sunt dii, sed opera manuum hominum, et nullum Dei opus cum illis.",
    ),
    (1, 51, "Unde ergo notum est quia non sunt dii, sed opera manuum hominum, et nullum Dei opus in ipsis est."),
    (1, 53, "Regem regioni non suscitant, neque pluviam hominibus dabunt."),
    (
        1,
        54,
        "Judicium quoque non discernent, neque regiones liberabunt ab injuria, quia nihil possunt, sicut corniculæ inter medium cæli et terræ.",
    ),
    (
        1,
        55,
        "Etenim cum inciderit ignis in domum deorum ligneorum, argenteorum et aureorum, sacerdotes quidem ipsorum fugient, et liberabuntur: ipsi vero sicut trabes in medio comburentur.",
    ),
    (1, 56, "Regi autem et bello non resistent. Quomodo ergo æstimandum est aut recipiendum quia dii sunt?"),
    (
        1,
        57,
        "Non a furibus, neque a latronibus se liberabunt dii lignei, et lapidei, et inaurati, et inargentati: quibus hi qui fortiores sunt,",
    ),
    (1, 58, "aurum et argentum, et vestimentum quo operti sunt, auferent illis, et abibunt, nec sibi auxilium ferent."),
    (
        1,
        59,
        "Itaque melius est esse regem ostentantem virtutem suam, aut vas in domo utile, in quo gloriabitur qui possidet illud, vel ostium in domo, quod custodit quæ in ipsa sunt, quam falsi dii.",
    ),
    (1, 60, "Sol quidem et luna ac sidera, cum sint splendida et emissa ad utilitates, obaudiunt:"),
    (1, 61, "similiter et fulgur cum apparuerit, perspicuum est: idipsum autem et spiritus in omni regione spirat:"),
    (
        1,
        62,
        "et nubes, quibus cum imperatum fuerit a Deo perambulare universum orbem, perficiunt quod imperatum est eis:",
    ),
    (
        1,
        63,
        "ignis etiam missus desuper, ut consumat montes et silvas, facit quod præceptum est ei: hæc autem neque speciebus, neque virtutibus, uni eorum similia sunt.",
    ),
    (
        1,
        64,
        "Unde neque existimandum est, neque dicendum illos esse deos, quando non possunt neque judicium judicare, neque quidquam facere hominibus.",
    ),
    (1, 65, "Scientes itaque quia non sunt dii, ne ergo timueritis eos."),
    (1, 66, "Neque enim regibus maledicent, neque benedicent."),
    (1, 67, "Signa etiam in cælo gentibus non ostendunt: neque ut sol lucebunt, neque illuminabunt ut luna."),
    (1, 68, "Bestiæ meliores sunt illis, quæ possunt fugere sub tectum ac prodesse sibi."),
    (1, 69, "Nullo itaque modo nobis est manifestum quia sunt dii: propter quod ne timeatis eos."),
    (1, 70, "Nam sicut in cucumerario formido nihil custodit, ita sunt dii illorum lignei, et argentei, et inaurati."),
    (
        1,
        71,
        "Eodem modo et in horto spina alba, supra quam omnis avis sedet, similiter et mortuo projecto in tenebris, similes sunt dii illorum lignei, et inaurati, et inargentati.",
    ),
    (
        1,
        72,
        "A purpura quoque et murice, quæ supra illos tineant, scietis itaque quia non sunt dii: ipsi etiam postremo comeduntur, et erunt opprobrium in regione.",
    ),
    (1, 73, "Melior est homo justus qui non habet simulacra, nam erit longe ab opprobriis."),
]
