"""Translation: vulgate-clementine · Book: man

AUTO-GENERATED by scripts/extract_vulgate_appendix.py (Clementine appendix, la.wikisource).
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "vulgate-clementine"
BOOK = "man"
VERSES = [
    (1, 1, "Domine omnipotens, Deus patrum nostrorum, Abraham, et Isaac, et Jacob, et seminis eorum justi,"),
    (1, 2, "qui fecisti cælum, et terram cum omni ornatu eorum,"),
    (
        1,
        3,
        "qui ligasti mare verbo præcepti tui, qui conclusisti abyssum, et signasti eam terribili et laudabili nomine tuo :",
    ),
    (1, 4, "quem omnia pavent, et tremunt a vultu virtutis tuæ, quia importabilis est magnificentia gloriæ tuæ,"),
    (1, 5, "et insustentabilis ira comminationis tuæ super peccatores :"),
    (1, 6, "immensa vero et investigabilis misericordia promissionis tuæ :"),
    (
        1,
        7,
        "quoniam tu es Dominus, altissimus, benignus, longanimis, et multum misericors, et pœnitens super malitias hominum. Tu Domine, secundum multitudinem bonitatis tuæ promisisti pœnitentiam, et remissionem iis, qui peccaverunt tibi, et multitudinem miserationum tuarum decrevisti pœnitentiam peccatoribus, in salutem.",
    ),
    (
        1,
        8,
        "Tu igitur Domine Deus justorum, non posuisti pœnitentiam justis, Abraham, et Isaac, et Jacob, iis qui tibi non peccaverunt : sed posuisti pœnitentiam propter me peccatorem :",
    ),
    (
        1,
        9,
        "quoniam peccavi super numerum arenæ maris : multiplicatæ sunt iniquitates meæ Domine, multiplicatæ sunt iniquitates meæ, et non sum dignus intueri et aspicere altitudinem cæli, præ multitudine iniquitatum mearum.",
    ),
    (
        1,
        10,
        "Incurvatus sum multo vinculo ferreo, ut non possim attollere caput meum, et non est respiratio mihi : quia excitavi iracundiam tuam, et malum coram te feci : non feci voluntatem tuam, et mandata tua non custodivi : statui abominationes, et multiplicavi offensiones.",
    ),
    (1, 11, "Et nunc flecto genu cordis mei, precans a te bonitatem."),
    (1, 12, "Peccavi Domine, peccavi, et iniquitates meas agnosco."),
    (
        1,
        13,
        "Quare peto rogans te, remitte mihi Domine, remitte mihi, et ne simul perdas me cum iniquitatibus meis, neque in æternum, iratus, reserves mala mihi, neque damnes me in infima terræ loca :",
    ),
    (
        1,
        14,
        "quia tu es Deus, Deus, inquam pœnitentium : et in me ostendes omnem bonitatem tuam, quia indignum salvabis me secundum magnam misericordiam tuam,",
    ),
    (
        1,
        15,
        "et laudabo te semper omnibus diebus vitæ meæ : quoniam te laudat omnis virtus cælorum, et tibi est gloria in sæcula sæculorum. Amen.",
    ),
]
