"""Translation: vulgate-clementine · Book: sus

AUTO-GENERATED by scripts/extract_translation.py.
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "vulgate-clementine"
BOOK = "sus"
VERSES = [
    (1, 1, "Et erat vir habitans in Babylone, et nomen ejus Joakim:"),
    (1, 2, "et accepit uxorem nomine Susannam, filiam Helciæ, pulchram nimis, et timentem Deum:"),
    (1, 3, "parentes enim illius, cum essent justi, erudierunt filiam suam secundum legem Moysi."),
    (
        1,
        4,
        "Erat autem Joakim dives valde, et erat ei pomarium vicinum domui suæ: et ad ipsum confluebant Judæi, eo quod esset honorabilior omnium.",
    ),
    (
        1,
        5,
        "Et constituti sunt de populo duo senes judices in illo anno, de quibus locutus est Dominus: Quia egressa est iniquitas de Babylone a senioribus judicibus, qui videbantur regere populum.",
    ),
    (1, 6, "Isti frequentabant domum Joakim, et veniebant ad eos omnes qui habebant judicia."),
    (1, 7, "Cum autem populus revertisset per meridiem, ingrediebatur Susanna, et deambulabat in pomario viri sui."),
    (1, 8, "Et videbant eam senes quotidie ingredientem et deambulantem, et exarserunt in concupiscentiam ejus:"),
    (
        1,
        9,
        "et everterunt sensum suum, et declinaverunt oculos suos ut non viderent cælum, neque recordarentur judiciorum justorum.",
    ),
    (1, 10, "Erant ergo ambo vulnerati amore ejus, nec indicaverunt sibi vicissim dolorem suum:"),
    (1, 11, "erubescebant enim indicare sibi concupiscentiam suam, volentes concumbere cum ea."),
    (1, 12, "Et observabant quotidie sollicitius videre eam. Dixitque alter ad alterum:"),
    (1, 13, "Eamus domum, quia hora prandii est. Et egressi, recesserunt a se."),
    (
        1,
        14,
        "Cumque revertissent, venerunt in unum: et sciscitantes ab invicem causam, confessi sunt concupiscentiam suam: et tunc in communi statuerunt tempus quando eam possent invenire solam.",
    ),
    (
        1,
        15,
        "Factum est autem, cum observarent diem aptum, ingressa est aliquando sicut heri et nudiustertius, cum duabus solis puellis, voluitque lavari in pomario: æstus quippe erat:",
    ),
    (1, 16, "et non erat ibi quisquam, præter duos senes absconditos, et contemplantes eam."),
    (1, 17, "Dixit ergo puellis: Afferte mihi oleum, et smigmata, et ostia pomarii claudite, ut laver."),
    (
        1,
        18,
        "Et fecerunt sicut præceperat: clauseruntque ostia pomarii, et egressæ sunt per posticum ut afferrent quæ jusserat; nesciebantque senes intus esse absconditos.",
    ),
    (1, 19, "Cum autem egressæ essent puellæ, surrexerunt duo senes, et accurrerunt ad eam, et dixerunt:"),
    (
        1,
        20,
        "Ecce ostia pomarii clausa sunt, et nemo nos videt, et nos in concupiscentia tui sumus: quam ob rem assentire nobis, et commiscere nobiscum.",
    ),
    (
        1,
        21,
        "Quod si nolueris, dicemus contra te testimonium, quod fuerit tecum juvenis, et ob hanc causam emiseris puellas a te.",
    ),
    (
        1,
        22,
        "Ingemuit Susanna, et ait: Angustiæ sunt mihi undique: si enim hoc egero, mors mihi est: si autem non egero, non effugiam manus vestras.",
    ),
    (1, 23, "Sed melius est mihi absque opere incidere in manus vestras, quam peccare in conspectu Domini."),
    (1, 24, "Et exclamavit voce magna Susanna: exclamaverunt autem et senes adversus eam."),
    (1, 25, "Et cucurrit unus ad ostia pomarii, et aperuit."),
    (1, 26, "Cum ergo audissent clamorem famuli domus in pomario, irruerunt per posticum ut viderent quidnam esset."),
    (
        1,
        27,
        "Postquam autem senes locuti sunt, erubuerunt servi vehementer, quia numquam dictus fuerat sermo hujuscemodi de Susanna. Et facta est dies crastina.",
    ),
    (
        1,
        28,
        "Cumque venisset populus ad Joakim virum ejus, venerunt et duo presbyteri, pleni iniqua cogitatione adversus Susannam ut interficerent eam.",
    ),
    (1, 29, "Et dixerunt coram populo: Mittite ad Susannam filiam Helciæ uxorem Joakim. Et statim miserunt."),
    (1, 30, "Et venit cum parentibus, et filiis, et universis cognatis suis."),
    (1, 31, "Porro Susanna erat delicata nimis, et pulchra specie."),
    (1, 32, "At iniqui illi jusserunt ut discooperiretur (erat enim cooperta), ut vel sic satiarentur decore ejus."),
    (1, 33, "Flebant igitur sui, et omnes qui noverant eam."),
    (1, 34, "Consurgentes autem duo presbyteri in medio populi, posuerunt manus suas super caput ejus."),
    (1, 35, "Quæ flens suspexit ad cælum: erat enim cor ejus fiduciam habens in Domino."),
    (
        1,
        36,
        "Et dixerunt presbyteri: Cum deambularemus in pomario soli, ingressa est hæc cum duabus puellis: et clausit ostia pomarii, et dimisit a se puellas.",
    ),
    (1, 37, "Venitque ad eam adolescens, qui erat absconditus, et concubuit cum ea."),
    (
        1,
        38,
        "Porro nos cum essemus in angulo pomarii, videntes iniquitatem, cucurrimus ad eos, et vidimus eos pariter commisceri.",
    ),
    (1, 39, "Et illum quidem non quivimus comprehendere, quia fortior nobis erat, et apertis ostiis exilivit:"),
    (
        1,
        40,
        "hanc autem cum apprehendissemus, interrogavimus, quisnam esset adolescens, et noluit indicare nobis: hujus rei testes sumus.",
    ),
    (1, 41, "Credidit eis multitudo quasi senibus et judicibus populi, et condemnaverunt eam ad mortem."),
    (
        1,
        42,
        "Exclamavit autem voce magna Susanna, et dixit: Deus æterne, qui absconditorum es cognitor, qui nosti omnia antequam fiant,",
    ),
    (
        1,
        43,
        "tu scis quoniam falsum testimonium tulerunt contra me: et ecce morior, cum nihil horum fecerim, quæ isti malitiose composuerunt adversum me.",
    ),
    (1, 44, "Exaudivit autem Dominus vocem ejus."),
    (1, 45, "Cumque duceretur ad mortem, suscitavit Dominus spiritum sanctum pueri junioris, cujus nomen Daniel:"),
    (1, 46, "et exclamavit voce magna: Mundus ego sum a sanguine hujus."),
    (1, 47, "Et conversus omnis populus ad eum, dixit: Quis est iste sermo, quem tu locutus es?"),
    (
        1,
        48,
        "Qui cum staret in medio eorum, ait: Sic fatui filii Israël, non judicantes, neque quod verum est cognoscentes, condemnastis filiam Israël?",
    ),
    (1, 49, "revertimini ad judicium, quia falsum testimonium locuti sunt adversus eam."),
    (
        1,
        50,
        "Reversus est ergo populus cum festinatione, et dixerunt ei senes: Veni, et sede in medio nostrum, et indica nobis: quia tibi Deus dedit honorem senectutis.",
    ),
    (1, 51, "Et dixit ad eos Daniel: Separate illos ab invicem procul, et dijudicabo eos."),
    (
        1,
        52,
        "Cum ergo divisi essent alter ab altero, vocavit unum de eis, et dixit ad eum: Inveterate dierum malorum, nunc venerunt peccata tua, quæ operabaris prius:",
    ),
    (
        1,
        53,
        "judicans judicia injusta, innocentes opprimens, et dimittens noxios, dicente Domino: Innocentem et justum non interficies.",
    ),
    (1, 54, "Nunc ergo, si vidisti eam, dic sub qua arbore videris eos colloquentes sibi. Qui ait: Sub schino."),
    (
        1,
        55,
        "Dixit autem Daniel: Recte mentitus es in caput tuum: ecce enim angelus Dei, accepta sententia ab eo, scindet te medium.",
    ),
    (
        1,
        56,
        "Et, amoto eo, jussit venire alium, et dixit ei: Semen Chanaan, et non Juda, species decepit te, et concupiscentia subvertit cor tuum:",
    ),
    (
        1,
        57,
        "sic faciebatis filiabus Israël, et illæ timentes loquebantur vobis: sed filia Juda non sustinuit iniquitatem vestram.",
    ),
    (1, 58, "Nunc ergo, dic mihi sub qua arbore comprehenderis eos loquentes sibi. Qui ait: Sub prino."),
    (
        1,
        59,
        "Dixit autem ei Daniel: Recte mentitus es et tu in caput tuum: manet enim angelus Domini, gladium habens, ut secet te medium, et interficiat vos.",
    ),
    (1, 60, "Exclamavit itaque omnis cœtus voce magna, et benedixerunt Deum, qui salvat sperantes in se."),
    (
        1,
        61,
        "Et consurrexerunt adversus duos presbyteros (convicerat enim eos Daniel ex ore suo falsum dixisse testimonium), feceruntque eis sicut male egerant adversus proximum,",
    ),
    (1, 62, "ut facerent secundum legem Moysi. Et interfecerunt eos, et salvatus est sanguis innoxius in die illa."),
    (
        1,
        63,
        "Helcias autem et uxor ejus laudaverunt Deum pro filia sua Susanna cum Joakim marito ejus, et cognatis omnibus, quia non esset inventa in ea res turpis.",
    ),
    (1, 64, "Daniel autem factus est magnus in conspectu populi a die illa, et deinceps."),
]
