"""
Notes for Paul’s Second Letter to the Thessalonians (2th).

No notes yet — add tuples to the NOTES list below or use:
    python3 scripts/add_note.py --book 2th --ch <N> --v <V> --anchor "…" \
        --kind comm --title "…" --body "…"

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    (
        1,
        1,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "c",
        "church",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ekklēsía (<em>ἐκκλησία</em>).</strong> a calling out, i.e. (concretely) a popular meeting, especially a religious congregation (Jewish synagogue, or Christian community of members on earth or saints in heaven or both).",
        "Strong's G1577, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "d",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, CHURCH, PAUL, SILAS, THESSALONICA.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        2,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "c",
        "Grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude).",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "d",
        "peace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Eirḗnē (<em>εἰρήνη</em>).</strong> peace (literally or figuratively); by implication, prosperity.",
        "Strong's G1515, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "e",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "f",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PAUL.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        3,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FAITH, FAITH, PAUL, THANKFULNESS, THANKFULNESS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        3,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Thanksgiving, Thanksgiving.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        4,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "b",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective).",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FAITH, FAITH, MEEKNESS, PATIENCE, PAUL.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        4,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted Saints, Patience.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        5,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "a",
        "righteous",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Díkaios (<em>δίκαιος</em>).</strong> equitable (in character or act); by implication, innocent, holy (absolutely or relatively).",
        "Strong's G1342, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "b",
        "judgment",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Krísis (<em>κρίσις</em>).</strong> decision (subjectively or objectively, for or against); by extension, a tribunal; by implication, justice (especially, divine law).",
        "Strong's G2920, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "c",
        "kingdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Basileía (<em>βασιλεία</em>).</strong> properly, royalty, i.e. (abstractly) rule, or (concretely) a realm (literally or figuratively).",
        "Strong's G932, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FAITH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        6,
        "a",
        "righteous",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Díkaios (<em>δίκαιος</em>).</strong> equitable (in character or act); by implication, innocent, holy (absolutely or relatively).",
        "Strong's G1342, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        6,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflictions of the Wicked, The, Persecution, Punishment of the Wicked, The, Righteousness of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        7,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANER, REST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        7,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>REVELATION OF CHRIST</strong> the second advent of Christ. Three different Greek words are used by the apostles to express this, (1) apokalupsis (1 Corinthians 1;7; 2 Thessalonians 1:7; 1 Peter 1:7, 13); (2) parousia (Matthew 24:3, 27; 1 Thessalonians 2:19; James 5:7, 8); (3) epiphaneia (1 Timothy 6:14; 2 Timothy 1:10; 4:1-8; Titus 2:13). There existed among Christians a wide expectation, founded on Matthew 24:29, 30, 34, of the speedy return of Christ. (See MILLENNIUM.)",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        7,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Announced, Death, Eternal, Death of Saints, The, Gifts of God, The, Second Coming of Christ, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        8,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b80-c4">1Pe 4:17</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        1,
        8,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "c",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "d",
        "gospel",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Euangélion (<em>εὐαγγέλιον</em>).</strong> a good message, i.e. the gospel.",
        "Strong's G2098, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHARACTER.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        8,
        "f",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Anger of God, The, Character of the Wicked, Death, Eternal, Fruit of, illustrative, Gospel, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        9,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "a",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective).",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "b",
        "everlasting",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Aiṓnios (<em>αἰώνιος</em>).</strong> perpetual (also used of past time, or past and future as well).",
        "Strong's G166, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: POWER, POWER.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        9,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Death, Eternal, Death, Eternal, Gospel, The, Hell, Power of Christ, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        10,
        "",
        "believe",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ).",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        10,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>TESTIMONY</strong> (1.) Witness or evidence (2 Thessalonians 1:10). (2.) The Scriptures, as the revelation of God’s will (2 Kings 11:12; Psalm 19:7; 119:88; Isaiah 8:16, 20). (3.) The altar raised by the Gadites and Reubenites (Joshua 22:10).",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        10,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Second Coming of Christ, The, Second Coming of Christ, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        11,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        11,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        11,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Goodness of God, The, Grace, Prayer, Intercessory.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        12,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "c",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude).",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "d",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character).',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GLORIFYING GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        12,
        "f",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Glorifying God, Grace.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        1,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "b",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect.",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        2,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b82-c4">1Jn 4:1</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        2,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "c",
        "spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit.",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "d",
        "mind",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Noûs (<em>νοῦς</em>).</strong> the intellect, i.e. mind (divine or human; in thought, feeling, or will); by implication, meaning.",
        "Strong's G3563, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALL.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        3,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_052.html#ch-b60-c24">Mat 24:4</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        3,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_052.html#ch-b60-c24">Mat 24:4</a> · <a href="index_split_059.html#ch-b82-c2">1Jn 2:18</a> · <a href="index_split_058.html#ch-b69-c5">Eph 5:6</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        3,
        "b",
        "son",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Huiós (<em>υἱός</em>).</strong> a "son" (sometimes of animals), used very widely of immediate, remote or figuratively, kinship.',
        "Strong's G5207, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "c",
        "sin",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hamartía (<em>ἁμαρτία</em>).</strong> a sin (properly abstract).",
        "Strong's G266, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, APOSTASY, BLASPHEMY, MIRACLES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        3,
        "e",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>MAN OF SIN</strong> a designation of Antichrist given in 2 Thessalonians 2:3-10, usually regarded as descriptive of the Papal power; but “in whomsoever these distinctive features are found, whoever wields temporal and spiritual power in any degree similar to that in which the man of sin is here described as wielding it, he, be he pope or potentate, is beyond all doubt a distinct type of Antichrist.”",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        2,
        3,
        "f",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Apostates, Miracles Through Evil Agents.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        4,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        4,
        "a",
        "temple",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Naós (<em>ναός</em>).</strong> a fane, shrine, temple.",
        "Strong's G3485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        4,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, BLASPHEMY, TEMPLE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        4,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ambition, Presumption.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        7,
        "",
        "mystery",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Mystḗrion (<em>μυστήριον</em>).</strong> a secret or "mystery" (through the idea of silence imposed by initiation into religious rites).',
        "Strong's G3466, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "a",
        "way",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hodós (<em>ὁδός</em>).</strong> a road; by implication, a progress (the route, act or distance); figuratively, a mode or means.",
        "Strong's G3598, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        8,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "a",
        "spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit.",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "b",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect.",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        8,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Second Coming of Christ, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        9,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_052.html#ch-b60-c24">Mat 24:24</a> · <a href="index_split_060.html#ch-b86-c19">Rev 19:20</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        9,
        "a",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect.",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        9,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, MIRACLES, MIRACLES, SORCERY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        9,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Devil, The, Devil, The, Lying, Miracles Through Evil Agents, Miracles Through Evil Agents.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        10,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_056.html#ch-b66-c1">1Co 1:18</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        10,
        "a",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast.",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "b",
        "saved",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively).",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "c",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth.",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, DECEIT, MIRACLES, SELF-DELUSION, TRUTH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        10,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Call of God, The, Deceit, Miracles Through Evil Agents, Self-Delusion, The gospel as.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        11,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_056.html#ch-b65-c1">Rom 1:28</a> · <a href="index_split_054.html#ch-b63-c12">Jhn 12:39</a> · <a href="index_split_059.html#ch-b74-c4">1Ti 4:1</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        11,
        "a",
        "believe",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ).",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, MIRACLES, SELF-DELUSION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        11,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Call of God, The, Doctrines, False, Miracles Through Evil Agents, Self-Delusion.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        12,
        "",
        "believed",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ).",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "a",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth.",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, MIRACLES, TRUTH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        12,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Miracles Through Evil Agents, Righteousness, The gospel as, The king of Babylon to be rewarded with the spoil of Egypt for his service against..",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        13,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b75-c1">2Ti 1:9</a> · <a href="index_split_058.html#ch-b69-c1">Eph 1:4</a> · <a href="index_split_058.html#ch-b72-c1">1Th 1:4</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        13,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "c",
        "Spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit.",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "d",
        "salvation",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōtēría (<em>σωτηρία</em>).</strong> rescue or safety (physically or morally).",
        "Strong's G4991, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "e",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth.",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "f",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALL, ELECTION, TRUTH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        13,
        "g",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>FAITH F</strong> aith is in general the persuasion of the mind that a certain statement is true (Phil. 1:27; 2 Thessalonians 2:13). Its primary idea is trust. A thing is true, and therefore worthy of trust. It admits of many degrees up to full assurance of faith, in accordance with the evidence on which it rests. Faith is the result of teaching (Romans 10:14-17). Knowledge is an essential element in all faith, and is sometimes spoken of as an equivalent to faith (John 10:38; 1 John 2:3). Yet…",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        2,
        13,
        "h",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Election, Election, Salvation, Sanctification, The gospel as.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        14,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "b",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective).",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "c",
        "gospel",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Euangélion (<em>εὐαγγέλιον</em>).</strong> a good message, i.e. the gospel.",
        "Strong's G2098, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALL, GLORY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        14,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Call of God, The, Call of God, The, Glory.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        15,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_057.html#ch-b66-c11">1Co 11:2</a> · <a href="index_split_058.html#ch-b73-c3">2Th 3:6</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        15,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        15,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHARACTER, TRADITION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        15,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Steadfastness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        16,
        "",
        "loved",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agapáō (<em>ἀγαπάω</em>).</strong> to love (in a social or moral sense).",
        "Strong's G25, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "c",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "d",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude).",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "e",
        "hope",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Elpís (<em>ἐλπίς</em>).</strong> expectation (abstractly or concretely) or confidence.",
        "Strong's G1680, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "f",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "g",
        "everlasting",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Aiṓnios (<em>αἰώνιος</em>).</strong> perpetual (also used of past time, or past and future as well).",
        "Strong's G166, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "h",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Consolation Under, Affliction, Consolation Under, Christ is God, Grace, Grace.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        17,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        17,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Consolation Under, Christ is God, Should be manifested, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        1,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        1,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        1,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: INTERCESSION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "",
        "",
        "text-witness",
        "Witness",
        "MS.",
        "<strong>Manuscript witness.</strong> entury. It is now in the British Museum (MS. Or. 4717 (10) ). Unfortunately, it is only a fragment con- sisting of four pages. The page exhibited, which is reproduced in its original size, contains 2 Thess. 3. 2-11. No imjwrtant variations of reading occur in this passage. The remaining Coptic versions may be dismissed very briefly. They have only recently been discovered, they are known as yet only in",
        "Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.",
    ),
    (
        3,
        2,
        "a",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The, Persecution.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        3,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b75-c4">2Ti 4:18</a> · <a href="index_split_058.html#ch-b72-c5">1Th 5:24</a> · <a href="index_split_057.html#ch-b66-c10">1Co 10:13</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        3,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b75-c4">2Ti 4:18</a> · <a href="index_split_058.html#ch-b72-c5">1Th 5:24</a> · <a href="index_split_057.html#ch-b66-c10">1Co 10:13</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        3,
        "b",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        3,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHARACTER.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        3,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Faithfulness of God, The, Protection, Protection.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        4,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_034.html#ch-b30-c119">Psa 119:36</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        5,
        "a",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast.",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "b",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "c",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "d",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Heart, The, Holy Spirit, The, is God, Love to God, Love to God, Patience.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        6,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:10</a> · <a href="index_split_058.html#ch-b73-c3">2Th 3:7</a> · <a href="index_split_058.html#ch-b71-c3">Col 3:17</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        6,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "c",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character).',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: TRADITION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        6,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Alliance and Society With the Enemies of God, Conduct, Christian.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        7,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:6</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        7,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:6</a> · <a href="index_split_058.html#ch-b73-c3">2Th 3:9</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EXAMPLE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        8,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_051.html#ch-b60-c6">Mat 6:11</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        8,
        "a",
        "bread",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ártos (<em>ἄρτος</em>).</strong> bread (as raised) or a loaf.",
        "Strong's G740, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EXAMPLE, INDUSTRY, PAUL, UNSELFISHNESS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        9,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:7</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        9,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:7</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        9,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EXAMPLE, MINIAMIN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        9,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Mills.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        10,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_000.html#vnote-gen-3-19">Gen 3:19</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        10,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_000.html#vnote-gen-3-19">Gen 3:19</a> · <a href="index_split_036.html#ch-b32-c13">Pro 13:4</a> · <a href="index_split_058.html#ch-b72-c4">1Th 4:11</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        10,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EXAMPLE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BUSYBODY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Busy-Bodies, Hyke or Upper Garment.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        12,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        12,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        12,
        "b",
        "bread",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ártos (<em>ἄρτος</em>).</strong> bread (as raised) or a loaf.",
        "Strong's G740, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        12,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BUSYBODY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        12,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Peace.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        13,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b68-c6">Gal 6:9</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        13,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b68-c6">Gal 6:9</a> · <a href="index_split_059.html#ch-b78-c12">Heb 12:3</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        13,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Perseverance.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        14,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        15,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Missionaries, All Christians Should Be As, Reproof.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        16,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c29">Psa 29:11</a> · <a href="index_split_054.html#ch-b63-c16">Jhn 16:33</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        16,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c29">Psa 29:11</a> · <a href="index_split_054.html#ch-b63-c16">Jhn 16:33</a> · <a href="index_split_051.html#ch-b60-c1">Mat 1:23</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        16,
        "b",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        16,
        "c",
        "peace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Eirḗnē (<em>εἰρήνη</em>).</strong> peace (literally or figuratively); by implication, prosperity.",
        "Strong's G1515, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        16,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Peace, Spiritual, Peace, Spiritual.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        17,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SALUTATIONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        17,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Salutations.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        18,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "b",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude).",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    # (ch, v, suf, anchor, kind, title, label, body_html),
]

NOTES_2TH = NOTES  # backward-compat alias
