"""
Notes for Paul’s Second Letter to the Thessalonians (2th).

No notes yet — add tuples to the NOTES list below or use:
    python3 scripts/add_note.py --book 2th --ch <N> --v <V> --anchor "…" \
        --kind comm --title "…" --body "…"

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    (
        1,
        1,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "c",
        "church",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ekklēsía (<em>ἐκκλησία</em>).</strong> a calling out, i.e. (concretely) a popular meeting, especially a religious congregation (Jewish synagogue, or Christian community of members on earth or saints in heaven or both). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1577, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "d",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHRISTIAN, PAUL, GOD, JESUS, SILAS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        2,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "c",
        "Grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "d",
        "peace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Eirḗnē (<em>εἰρήνη</em>).</strong> peace (literally or figuratively); by implication, prosperity. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1515, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "e",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "f",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APOSTOLIC, GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        3,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FAITH, FAITH, GOZAX, RIGHTEOUSNESS, THANKFULNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        4,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "b",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DKLIVEIIANCE FROM, PRAYER FOR THE AFFLICTED, GOD, LOVE, MEEKNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        5,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "a",
        "righteous",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Díkaios (<em>δίκαιος</em>).</strong> equitable (in character or act); by implication, innocent, holy (absolutely or relatively). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1342, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "b",
        "judgment",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Krísis (<em>κρίσις</em>).</strong> decision (subjectively or objectively, for or against); by extension, a tribunal; by implication, justice (especially, divine law). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2920, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "c",
        "kingdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Basileía (<em>βασιλεία</em>).</strong> properly, royalty, i.e. (abstractly) rule, or (concretely) a realm (literally or figuratively). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G932, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PROMISES TO, WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        6,
        "a",
        "righteous",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Díkaios (<em>δίκαιος</em>).</strong> equitable (in character or act); by implication, innocent, holy (absolutely or relatively). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1342, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        6,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: TIES. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        7,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BENEFITS OF, ANGEL, ANGEL, IMMORTALITY, JESUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        8,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b80-c4">1Pe 4:17</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        1,
        8,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "c",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "d",
        "gospel",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Euangélion (<em>εὐαγγέλιον</em>).</strong> a good message, i.e. the gospel. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2098, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BLINDNESS, CHAPITER, WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        9,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "a",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "b",
        "everlasting",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Aiṓnios (<em>αἰώνιος</em>).</strong> perpetual (also used of past time, or past and future as well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G166, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JEWS, HELL, JESUS, POWER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        10,
        "",
        "believe",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GOSPEL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        11,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        11,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        11,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALL, GOD, INTERCESSION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        12,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "c",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "d",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GLORIFYING GOD, JESUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        1,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "b",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DECEPTION, GOD, HOLINESS TO THE LORD, HOPE, JESUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        2,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b82-c4">1Jn 4:1</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        2,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "c",
        "spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "d",
        "mind",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Noûs (<em>νοῦς</em>).</strong> the intellect, i.e. mind (divine or human; in thought, feeling, or will); by implication, meaning. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3563, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_052.html#ch-b60-c24">Mat 24:4</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        3,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_052.html#ch-b60-c24">Mat 24:4</a> · <a href="index_split_059.html#ch-b82-c2">1Jn 2:18</a> · <a href="index_split_058.html#ch-b69-c5">Eph 5:6</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        3,
        "b",
        "son",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Huiós (<em>υἱός</em>).</strong> a "son" (sometimes of animals), used very widely of immediate, remote or figuratively, kinship. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G5207, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "c",
        "sin",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hamartía (<em>ἁμαρτία</em>).</strong> a sin (properly abstract). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G266, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANTICHRIST, APOSTASY, APOSTASY, BLASPHEMY, MIRACLES. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        4,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        4,
        "a",
        "temple",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Naós (<em>ναός</em>).</strong> a fane, shrine, temple. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        4,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BLASPHEMY, SELF-EXALTATION, TEMPLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PHILIPPIANS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PHILIPPIANS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        7,
        "",
        "mystery",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Mystḗrion (<em>μυστήριον</em>).</strong> a secret or "mystery" (through the idea of silence imposed by initiation into religious rites). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G3466, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "a",
        "way",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hodós (<em>ὁδός</em>).</strong> a road; by implication, a progress (the route, act or distance); figuratively, a mode or means. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3598, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MYSTERIES, REPROBACY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        8,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "a",
        "spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "b",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONTINGENCIES, WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        9,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_052.html#ch-b60-c24">Mat 24:24</a> · <a href="index_split_060.html#ch-b86-c19">Rev 19:20</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        9,
        "a",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        9,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MIRACLES, SATAN, SORCERY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        10,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_056.html#ch-b66-c1">1Co 1:18</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        10,
        "a",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "b",
        "saved",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "c",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALL, DECEIT, GOSPEL, MIRACLES, SELF-DELUSION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        11,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_056.html#ch-b65-c1">Rom 1:28</a> · <a href="index_split_054.html#ch-b63-c12">Jhn 12:39</a> · <a href="index_split_059.html#ch-b74-c4">1Ti 4:1</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        11,
        "a",
        "believe",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BLINDNESS, UNBELIEF. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        12,
        "",
        "believed",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "a",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PLEASURE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        13,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b75-c1">2Ti 1:9</a> · <a href="index_split_058.html#ch-b69-c1">Eph 1:4</a> · <a href="index_split_058.html#ch-b72-c1">1Th 1:4</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        13,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "c",
        "Spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "d",
        "salvation",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōtēría (<em>σωτηρία</em>).</strong> rescue or safety (physically or morally). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4991, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "e",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "f",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: TO SFECIAJ, FAITH, HOLY SPIRIT, JESUS, PROMISES TO. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        14,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "b",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "c",
        "gospel",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Euangélion (<em>εὐαγγέλιον</em>).</strong> a good message, i.e. the gospel. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2098, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALL, CALL, GLORY, HEAVEN, WORD OF GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        15,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_057.html#ch-b66-c11">1Co 11:2</a> · <a href="index_split_058.html#ch-b73-c3">2Th 3:6</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        15,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        15,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DEFAMATION OF, COMMANDMENTS, PERSEVERANCE, STABILITY, TRADITION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        16,
        "",
        "loved",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agapáō (<em>ἀγαπάω</em>).</strong> to love (in a social or moral sense). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G25, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "c",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "d",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "e",
        "hope",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Elpís (<em>ἐλπίς</em>).</strong> expectation (abstractly or concretely) or confidence. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1680, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "f",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "g",
        "everlasting",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Aiṓnios (<em>αἰώνιος</em>).</strong> perpetual (also used of past time, or past and future as well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G166, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "h",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BENEFITS OF, LONGSUFFERING OF, PROVIDENCE OF, INTERCESSION, JESUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        17,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        17,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AVOUDS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        1,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        1,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        1,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: INTERCESSION, PRAYER FOR. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "",
        "",
        "text-witness",
        "Witness",
        "MS.",
        "<strong>Manuscript witness.</strong> entury. It is now in the British Museum (MS. Or. 4717 (10) ). Unfortunately, it is only a fragment con- sisting of four pages. The page exhibited, which is reproduced in its original size, contains 2 Thess. 3. 2-11. No imjwrtant variations of reading occur in this passage. The remaining Coptic versions may be dismissed very briefly. They have only recently been discovered, they are known as yet only in <em>[Reviewer: trim to the relevant clause; the surrounding context is provided so you can judge which version / witness Kenyon is discussing.]</em>",
        "Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.",
    ),
    (
        3,
        2,
        "a",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: UNBELIEF. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        3,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b75-c4">2Ti 4:18</a> · <a href="index_split_058.html#ch-b72-c5">1Th 5:24</a> · <a href="index_split_057.html#ch-b66-c10">1Co 10:13</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        3,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_059.html#ch-b75-c4">2Ti 4:18</a> · <a href="index_split_058.html#ch-b72-c5">1Th 5:24</a> · <a href="index_split_057.html#ch-b66-c10">1Co 10:13</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        3,
        "b",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        3,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DEFAMATION OF, GOD, JESUS, STABILITY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        4,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MINISTER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        5,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_034.html#ch-b30-c119">Psa 119:36</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        5,
        "a",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "b",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "c",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "d",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: INTERCESSION, JESUS, LOVE, LOVE, MEEKNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        6,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:10</a> · <a href="index_split_058.html#ch-b73-c3">2Th 3:7</a> · <a href="index_split_058.html#ch-b71-c3">Col 3:17</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        6,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "b",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "c",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: COMMANDMENTS, COMPANY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        7,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:6</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        7,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:6</a> · <a href="index_split_058.html#ch-b73-c3">2Th 3:9</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PAUL, LABOR, MINISTER, ZEAL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        8,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_051.html#ch-b60-c6">Mat 6:11</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        8,
        "a",
        "bread",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ártos (<em>ἄρτος</em>).</strong> bread (as raised) or a loaf. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G740, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: PAUL, INDUSTRY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        9,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        9,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b73-c3">2Th 3:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        9,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MINISTER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        10,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_000.html#vnote-gen-3-19">Gen 3:19</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        10,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_000.html#vnote-gen-3-19">Gen 3:19</a> · <a href="index_split_036.html#ch-b32-c13">Pro 13:4</a> · <a href="index_split_058.html#ch-b72-c4">1Th 4:11</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        10,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: IDLENESS, INDUSTRY, SLING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BUSYBODY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        12,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        12,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        12,
        "b",
        "bread",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ártos (<em>ἄρτος</em>).</strong> bread (as raised) or a loaf. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G740, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        13,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b68-c6">Gal 6:9</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        13,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_058.html#ch-b68-c6">Gal 6:9</a> · <a href="index_split_059.html#ch-b78-c12">Heb 12:3</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        13,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DECEPTION, PERSEVERANCE, ZEAL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        14,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        14,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FRATERNITY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        16,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c29">Psa 29:11</a> · <a href="index_split_054.html#ch-b63-c16">Jhn 16:33</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        16,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c29">Psa 29:11</a> · <a href="index_split_054.html#ch-b63-c16">Jhn 16:33</a> · <a href="index_split_051.html#ch-b60-c1">Mat 1:23</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        16,
        "b",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        16,
        "c",
        "peace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Eirḗnē (<em>εἰρήνη</em>).</strong> peace (literally or figuratively); by implication, prosperity. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G1515, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        16,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: UCV, PEACE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        17,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SALUTATIONS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        18,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "b",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APOSTOLIC. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    # (ch, v, suf, anchor, kind, title, label, body_html),
]

NOTES_2TH = NOTES  # backward-compat alias
