"""
Notes for The Letter from James (jam).

No notes yet — add tuples to the NOTES list below or use:
    python3 scripts/add_note.py --book jam --ch <N> --v <V> --anchor "…" \
        --kind comm --title "…" --body "…"

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    (
        1,
        1,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "a",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JAMES, MINIAMIN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        1,
        "c",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>DISPERSION</strong> (Gr. diaspora, “scattered,” James 1:1; 1 Peter 1:1) of the Jews. At various times, and from the operation of divers causes, the Jews were separated and scattered into foreign countries “to the outmost parts of heaven” (Deuteronomy 30:4). (1.) Many were dispersed over Assyria, Media, Babylonia, and Persia, descendants of those who had been transported thither by the Exile. The ten tribes, after existing as a separate kingdom for two hundred and fifty-five years, were carried…",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        1,
        "d",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Jews, The, Titles and Names of Ministers, Tribes of Israel, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        2,
        "",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>TEMPTATION</strong> (1.) Trial; a being put to the test. Thus God “tempted [Genesis 22: 1; R.V., ‘did prove’] Abraham;” and afflictions are said to tempt, i.e., to try, men (James 1:2, 12; comp. Deuteronomy 8:2), putting their faith and patience to the test. (2.) Ordinarily, however, the word means solicitation to that which is evil, and hence Satan is called “the tempter” (Matthew 4:3). Our Lord was in this way tempted in the wilderness. That temptation was not internal, but by a real, active,…",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        2,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Holiness, Joy, Temptation, Temptation.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        3,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflictions Made Beneficial, Eye, The, Holiness, Patience, Temptation.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        4,
        "",
        "perfect",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Téleios (<em>τέλειος</em>).</strong> complete (in various applications of labor, growth, mental and moral character, etc.); neuter (as noun, with G3588 (ὁ)) completeness.",
        "Strong's G5046, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted Saints, Patience, Perfection, Sun, The, Temptation.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        5,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "a",
        "wisdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sophía (<em>σοφία</em>).</strong> wisdom (higher or lower, worldly or spiritual).",
        "Strong's G4678, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GIFTS FROM GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        5,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Gifts of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        6,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        6,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HEART.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The, Prayer, Prayer, Answers To, Seas mentioned in scripture, Steadfastness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        7,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        7,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prayer, Answers To, Steadfastness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        8,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Decision, Steadfastness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        8,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HEART, INDECISION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        9,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Poor, The, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GRASS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Flowers, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        11,
        "",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude).",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        11,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GRASS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        11,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Flowers, Riches, Sun, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        12,
        "",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast.",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "b",
        "life",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Zōḗ (<em>ζωή</em>).</strong> life (literally or figuratively).",
        "Strong's G2222, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ASSURANCE, CROWN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        12,
        "d",
        "Blessed",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Makários (<em>μακάριος</em>).</strong> supremely blest; by extension, fortunate, well off.",
        "Strong's G3107, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Consolation Under, Assurance, Blessed, The, Love to Christ, Love to God.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        13,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        13,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Temptation, Temptation.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        14,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Temptation.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        15,
        "",
        "sin",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hamartía (<em>ἁμαρτία</em>).</strong> a sin (properly abstract).",
        "Strong's G266, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        15,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Death, Eternal, Sin, Sin, Temptation.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        17,
        "",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        17,
        "a",
        "",
        "comm-ethiopian",
        "Tewahedo — Athanasius of Alexandria",
        "Athanasius of Alexandria (350).",
        '<aside class="note-comm-ethiopian"><strong>Athanasius of Alexandria</strong> <em>Festal Letters 39 (367 AD)</em> <small>(c. 350 AD)</small><p>&#x27;Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning&#x27; — Athanasius marks ho Patēr tōn phōtōn par&#x27; hō ouk eni parallagē ē tropēs aposkiasma (the Father of lights, with-whom is-not variation or shadow-of-turning) as the DIVINE-IMMUTABILITY anchor. The atrepton (un-turning) and aparal-lakton (un-varying) of the Father&#x27;s-essence are direct anti-Arian: the divine-Light cannot vary or turn (i.e. cannot become what-it-was-not, cannot beget-a-creature-rather-than-eternal-Word). Athanasius&#x27;s inclusion of James in the NT-canon (Festal Letter 39, 367 AD) was the canonical-decision that gave the Catholic-Epistle its full-apostolic-authority in the Eastern tradition; Jas 1:17 anchors the canon-inclusion with a direct-Trinitarian-essence prooftext.</p></aside>',
        "Athanasius of Alexandria, Festal Letters (selections, including the canon-defining Letter 39 of 367 AD), in Select Writings and Letters of Athanasius, Nicene and Post-Nicene Fathers (NPNF), Series 2, Vol. 4, ed. Archibald Robertson (Oxford / T&T Clark, 1892). PD.",
    ),
    (
        1,
        17,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        17,
        "c",
        "perfect",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Téleios (<em>τέλειος</em>).</strong> complete (in various applications of labor, growth, mental and moral character, etc.); neuter (as noun, with G3588 (ὁ)) completeness.",
        "Strong's G5046, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        17,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Gifts of God, The, Goat, The, Goat, The, Grace, Light.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        18,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FIRST FRUITS, WORD OF GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        18,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        18,
        "b",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth.",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        18,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: First Fruits, The, Gospel, The, New Birth, The, New Birth, The, Scriptures, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        19,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Anger, Conduct, Christian, Heedfulness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        20,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        20,
        "a",
        "righteousness",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dikaiosýnē (<em>δικαιοσύνη</em>).</strong> equity (of character or act); specially (Christian) justification.",
        "Strong's G1343, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        21,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORD OF GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        21,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        21,
        "b",
        "save",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively).",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        21,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Meekness, Salvation, Scriptures, The, Scriptures, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        22,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOER, WORD OF GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        22,
        "a",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        22,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Scriptures, The, Scriptures, The, Scriptures, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        23,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        23,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOER, MIRROR, PARABLES, WORD OF GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        23,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Scriptures, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        24,
        "",
        "way",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hodós (<em>ὁδός</em>).</strong> a road; by implication, a progress (the route, act or distance); figuratively, a mode or means.",
        "Strong's G3598, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        24,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOER, MIRROR, PARABLES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        24,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Blessed, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        25,
        "",
        "blessed",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Makários (<em>μακάριος</em>).</strong> supremely blest; by extension, fortunate, well off.",
        "Strong's G3107, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        25,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOER, FORGETTING GOD, PARABLES, WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        25,
        "b",
        "perfect",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Téleios (<em>τέλειος</em>).</strong> complete (in various applications of labor, growth, mental and moral character, etc.); neuter (as noun, with G3588 (ὁ)) completeness.",
        "Strong's G5046, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        25,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Forgetting God, Liberty, Christian, Obedience to God, Perfection, Perseverance.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        26,
        "",
        "heart",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kardía (<em>καρδία</em>).</strong> the heart, i.e. (figuratively) the thoughts or feelings (mind); also (by analogy) the middle.",
        "Strong's G2588, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        26,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Heart, Character of the Unrenewed, Slander, Vanity.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        26,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDLE, DOER, SELF-DECEPTION, VANITY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        27,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        27,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOER, SICK, THE, SYMPATHY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        27,
        "b",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        1,
        27,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted, Duty Toward The, Conduct, Christian, Fatherless, Love to Man, Missionaries, All Christians Should Be As.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        1,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JESUS, THE CHRIST, JESUS, THE CHRIST, RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        1,
        "c",
        "Christ",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Christós (<em>Χριστός</em>).</strong> anointed, i.e. the Messiah, an epithet of Jesus.",
        "Strong's G5547, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "d",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective).",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Christ is God, Christ, the King, Contempt.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        2,
        "",
        "assembly",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ekklēsía (<em>ἐκκλησία</em>).</strong> a calling out, i.e. (concretely) a popular meeting, especially a religious congregation (Jewish synagogue, or Christian community of members on earth or saints in heaven or both).",
        "Strong's G1577, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS, SYNAGOGUE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        2,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Contempt, Courts of Justice, Gardens, Gold, Poor, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Contempt, Poor, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Poor, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        5,
        "",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast.",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        5,
        "a",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        5,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HEIR, RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        5,
        "c",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        5,
        "d",
        "kingdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Basileía (<em>βασιλεία</em>).</strong> properly, royalty, i.e. (abstractly) rule, or (concretely) a realm (literally or figuratively).",
        "Strong's G932, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        5,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Poor, The, Promises of God, The, Riches, Titles and Names of Saints, Titles and Names of Saints.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        6,
        "a",
        "judgment",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Krísis (<em>κρίσις</em>).</strong> decision (subjectively or objectively, for or against); by extension, a tribunal; by implication, justice (especially, divine law).",
        "Strong's G2920, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        6,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Contempt, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        7,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        7,
        "a",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character).',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "",
        "love",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Agápē (<em>ἀγάπη</em>).</strong> love, i.e. affection or benevolence; specially (plural) a love-feast.",
        "Strong's G26, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        8,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        8,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Law of Moses, The, Love to Man, Selfishness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        9,
        "",
        "sin",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hamartía (<em>ἁμαρτία</em>).</strong> a sin (properly abstract).",
        "Strong's G266, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        9,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RESPECT OF PERSONS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        10,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Justification Before God, Law of God, The, Law of God, The, Sin.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        11,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Sin.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        12,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Judgment, The, Liberty, Christian.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        13,
        "",
        "judgment",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Krísis (<em>κρίσις</em>).</strong> decision (subjectively or objectively, for or against); by extension, a tribunal; by implication, justice (especially, divine law).",
        "Strong's G2920, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Forgiveness of Injuries, Mercy.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        14,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: VANITY, WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        14,
        "b",
        "save",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively).",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        14,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Liberality, Vanity, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        15,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Liberality, Poor, The, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        15,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        16,
        "",
        "body",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōma (<em>σῶμα</em>).</strong> the body (as a sound whole), used in a very wide application, literally or figuratively.",
        "Strong's G4983, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        16,
        "b",
        "peace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Eirḗnē (<em>εἰρήνη</em>).</strong> peace (literally or figuratively); by implication, prosperity.",
        "Strong's G1515, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        16,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Liberality, Poor, The, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        17,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        17,
        "a",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        17,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dead, The, Eye, The, Poor, The, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        18,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        18,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        18,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        19,
        "",
        "believe",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ).",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        19,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DEMONS, REVERENCE, REVERENCE, WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        19,
        "b",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        19,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Unity of God, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        20,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        20,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORKS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        20,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The, Malice, Unity of God, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        21,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ABRAHAM, ABRAHAM, ISAAC, OBEDIENCE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        21,
        "a",
        "son",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Huiós (<em>υἱός</em>).</strong> a "son" (sometimes of animals), used very widely of immediate, remote or figuratively, kinship.',
        "Strong's G5207, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        21,
        "b",
        "father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        21,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        22,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ABRAHAM.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        22,
        "a",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        22,
        "b",
        "perfect",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Téleios (<em>τέλειος</em>).</strong> complete (in various applications of labor, growth, mental and moral character, etc.); neuter (as noun, with G3588 (ὁ)) completeness.",
        "Strong's G5046, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        22,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        23,
        "",
        "believed",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pisteúō (<em>πιστεύω</em>).</strong> to have faith (in, upon, or with respect to, a person or thing), i.e. credit; by implication, to entrust (especially one's spiritual well-being to Christ).",
        "Strong's G4100, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        23,
        "a",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        23,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ABRAHAM, ABRAHAM.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        23,
        "c",
        "righteousness",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dikaiosýnē (<em>δικαιοσύνη</em>).</strong> equity (of character or act); specially (Christian) justification.",
        "Strong's G1343, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        23,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The, Gardens, Privileges of Saints, Titles and Names of Saints.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        24,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        24,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ABRAHAM.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        24,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        25,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RAHAB.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        25,
        "a",
        "way",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hodós (<em>ὁδός</em>).</strong> a road; by implication, a progress (the route, act or distance); figuratively, a mode or means.",
        "Strong's G3598, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        25,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Eye, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        26,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        26,
        "a",
        "spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit.",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        26,
        "b",
        "body",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōma (<em>σῶμα</em>).</strong> the body (as a sound whole), used in a very wide application, literally or figuratively.",
        "Strong's G4983, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        2,
        26,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dead, The, Dead, The, Eye, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        2,
        "",
        "word",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Lógos (<em>λόγος</em>).</strong> something said (including the thought); by implication, a topic (subject of discourse), also reasoning (the mental faculty) or motive; by extension, a computation; specially, (with the article in John) the Divine Expression (i.e. Christ).",
        "Strong's G3056, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WORDS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "b",
        "body",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōma (<em>σῶμα</em>).</strong> the body (as a sound whole), used in a very wide application, literally or figuratively.",
        "Strong's G4983, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "c",
        "perfect",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Téleios (<em>τέλειος</em>).</strong> complete (in various applications of labor, growth, mental and moral character, etc.); neuter (as noun, with G3588 (ὁ)) completeness.",
        "Strong's G5046, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Perfection.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        3,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BIT, HORSE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        3,
        "a",
        "body",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōma (<em>σῶμα</em>).</strong> the body (as a sound whole), used in a very wide application, literally or figuratively.",
        "Strong's G4983, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        3,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Horse, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HELM, SHIP.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ships, Ships, Ships, When violent called, When violent called.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BOASTING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        5,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruit of, illustrative, Fruit of, illustrative.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        6,
        "",
        "body",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sōma (<em>σῶμα</em>).</strong> the body (as a sound whole), used in a very wide application, literally or figuratively.",
        "Strong's G4983, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruit of, illustrative.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        7,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANIMALS, BIRDS, BIRDS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        7,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beard, The, Birds, Serpents.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        9,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        9,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: IMAGE, MAN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        9,
        "b",
        "Father",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Patḗr (<em>πατήρ</em>).</strong> a "father" (literally or figuratively, near or more remote).',
        "Strong's G3962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        9,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Malice.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        11,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fountains and Springs, Fountains and Springs.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        11,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SPRING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        12,
        "",
        "vine",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ámpelos (<em>ἄμπελος</em>).</strong> a vine (as coiling about a support).",
        "Strong's G288, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Olive Tree, The, Salt.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        13,
        "",
        "knowledge",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Gnōsis (<em>γνῶσις</em>).</strong> knowing (the act), i.e. (by implication) knowledge.",
        "Strong's G1108, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        13,
        "a",
        "wisdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sophía (<em>σοφία</em>).</strong> wisdom (higher or lower, worldly or spiritual).",
        "Strong's G4678, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        13,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Meekness, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        13,
        "c",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>MEEKNESS</strong> a calm temper of mind, not easily provoked (James 3:13). Peculiar promises are made to the meek (Matthew 5:5; Isaiah 66:2). The cultivation of this spirit is enjoined (Colossians 3:12; 1 Timothy 6:11; Zephaniah 2:3), and is exemplified in Christ (Matthew 11:29), Abraham (Genesis 13; 16:5, 6) Moses (Numbers 12:3), David (Zechariah 12:8; 2 Samuel 16:10, 12), and Paul (1 Corinthians 9:19).",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        3,
        14,
        "",
        "glory",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dóxa (<em>δόξα</em>).</strong> glory (as very apparent), in a wide application (literal or figurative, objective or subjective).",
        "Strong's G1391, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        14,
        "a",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth.",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        14,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Envy, Strife.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        15,
        "",
        "wisdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sophía (<em>σοφία</em>).</strong> wisdom (higher or lower, worldly or spiritual).",
        "Strong's G4678, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        16,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Envy, Strife.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        17,
        "",
        "wisdom",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sophía (<em>σοφία</em>).</strong> wisdom (higher or lower, worldly or spiritual).",
        "Strong's G4678, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        17,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Meekness, Peace, Works, Good, Works, Good.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        17,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GENTLENESS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        18,
        "",
        "peace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Eirḗnē (<em>εἰρήνη</em>).</strong> peace (literally or figuratively); by implication, prosperity.",
        "Strong's G1515, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "a",
        "righteousness",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Dikaiosýnē (<em>δικαιοσύνη</em>).</strong> equity (of character or act); specially (Christian) justification.",
        "Strong's G1343, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Peace.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        1,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ambition, Strife, War.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        2,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ambition.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prayer, Answers To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        4,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CARNAL MINDEDNESS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        4,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Titles and Names of the Wicked.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        5,
        "",
        "spirit",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pneûma (<em>πνεῦμα</em>).</strong> a current of air, i.e. breath (blast) or a breeze; by analogy or figuratively, a spirit, i.e. (human) the rational soul, (by implication) vital principle, mental disposition, etc., or (superhuman) an angel, demon, or (divine) God, Christ's spirit, the Holy Spirit.",
        "Strong's G4151, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        5,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Envy.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        6,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        6,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GIFTS FROM GOD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        6,
        "b",
        "grace",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Cháris (<em>χάρις</em>).</strong> graciousness (as gratifying), of manner or act (abstract or concrete; literal, figurative or spiritual; especially the divine influence upon the heart, and its reflection in the life; including gratitude).",
        "Strong's G5485, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        6,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Gifts of God, The, Grace, Humility, Pride.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        7,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WAR.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        7,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Consolation Under, Devil, The, Devil, The, Warfare of Saints.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        8,
        "",
        "God",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Theós (<em>θεός</em>).</strong> figuratively, a magistrate; by Hebraism, very.",
        "Strong's G2316, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        8,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HEART.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        8,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Access to God, Access to God, Heart, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        9,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JOY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        9,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Joy, Repentance.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        10,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Humility, Repentance.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOER.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Slander, Slander.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        12,
        "",
        "save",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively).",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Death, Eternal, Slander.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        13,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SELF-DELUSION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        13,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Commerce, Happiness of the Wicked, The, Life, Natural, Presumption, Self-Delusion.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        14,
        "",
        "life",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Zōḗ (<em>ζωή</em>).</strong> life (literally or figuratively).",
        "Strong's G2222, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Happiness of the Wicked, The, Life, Natural, Life, Natural.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        15,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        15,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Life, Natural.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        16,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BOASTING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        17,
        "",
        "sin",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hamartía (<em>ἁμαρτία</em>).</strong> a sin (properly abstract).",
        "Strong's G266, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        4,
        17,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Sin.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        17,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: INDECISION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        1,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AMUSEMENTS AND WORLDLY PLEASURES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        1,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Amusements and Pleasures, Worldly, Condemnation, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        2,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MOTH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        2,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Condemnation, Gardens, Moth, The, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        3,
        "",
        "flesh",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sárx (<em>σάρξ</em>).</strong> flesh (as stripped of the skin), i.e. (strictly) the meat of an animal (as food), or (by extension) the body (as opposed to the soul (or spirit), or as the symbol of what is external, or as the means of kindred), or (by implication) human nature (with its frailties (physically or morally) and passions), or (specially), a human being (as such).",
        "Strong's G4561, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        3,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Condemnation, Gold, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        4,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EMPLOYEE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        4,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Condemnation, Harvest, The, Injustice, Masters, Money.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        5,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Amusements and Pleasures, Worldly, Condemnation, Riches, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        5,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AMUSEMENTS AND WORLDLY PLEASURES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        6,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Happiness of the Wicked, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        7,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        7,
        "a",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect.",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AGRICULTURE, WAITING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        7,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Agriculture or Husbandry, Fruits, Harvest, The, Patience, Second Coming of Christ, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        8,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        8,
        "a",
        "coming",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Parousía (<em>παρουσία</em>).</strong> a being near, i.e. advent (often, return; specially, of Christ to punish Jerusalem, or finally the wicked); (by implication) physically, aspect.",
        "Strong's G3952, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        8,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Second Coming of Christ, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        10,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EXAMPLE, MINIAMIN, PATIENCE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        10,
        "b",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character).',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        10,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted Saints, Patience, Prophecy, Prophets, Predictions of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        11,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflictions, Happiness of Saints In This Life, Patience.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        11,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES, EXAMPLE, JOB, MEEKNESS, PATIENCE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        12,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Nineveh, Swearing, Profane.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        12,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONVERSATION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        13,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Prayer Under, Joy, Praise, Plead in the.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        14,
        "",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        14,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANOINTING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        14,
        "b",
        "church",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Ekklēsía (<em>ἐκκλησία</em>).</strong> a calling out, i.e. (concretely) a popular meeting, especially a religious congregation (Jewish synagogue, or Christian community of members on earth or saints in heaven or both).",
        "Strong's G1577, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        14,
        "c",
        "name",
        "lang-greek",
        "Greek",
        "Greek.",
        '<strong>Ónoma (<em>ὄνομα</em>).</strong> a "name" (literally or figuratively) (authority, character).',
        "Strong's G3686, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        14,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted, Duty Toward The, Anointing, Diseases, Diseases, Oil.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        15,
        "",
        "faith",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Pístis (<em>πίστις</em>).</strong> persuasion, i.e. credence; moral conviction (of religious truth, or the truthfulness of God or a religious teacher), especially reliance upon Christ for salvation; abstractly, constancy in such profession; by extension, the system of religious (Gospel) truth itself.",
        "Strong's G4102, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        15,
        "a",
        "Lord",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Kýrios (<em>κύριος</em>).</strong> supreme in authority, i.e. (as noun) controller; by implication, Master (as a respectful title).",
        "Strong's G2962, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        15,
        "b",
        "save",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively).",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        15,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted, Duty Toward The, Diseases, Life, Natural, Pardon, Prayer, Answers To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        16,
        "",
        "righteous",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Díkaios (<em>δίκαιος</em>).</strong> equitable (in character or act); by implication, innocent, holy (absolutely or relatively).",
        "Strong's G1342, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        16,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted, Duty Toward The, Confession of Sin, Missionaries, All Christians Should Be As, Prayer, Prayer, Answers To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        16,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>EFFECTUAL PRAYER</strong> occurs in Authorized Version, James 5:16. The Revised Version renders appropriately: “The supplication of a righteous man availeth much in its working”, i.e., “it moves the hand of Him who moves the world.”",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        5,
        17,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Moses and Aaron, Prayer, Prayer, Answers To, Purifications.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        17,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BLESSING, ELIJAH, ELIJAH, PRAYER, RAIN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        18,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruits, Moses and Aaron, Prayer, Answers To, Purifications.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        18,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BLESSING, ELIJAH, RAIN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        19,
        "",
        "truth",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Alḗtheia (<em>ἀλήθεια</em>).</strong> truth.",
        "Strong's G225, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        19,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Backsliding, Conversion, Missionaries, All Christians Should Be As.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        20,
        "",
        "soul",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Psychḗ (<em>ψυχή</em>).</strong> breath, i.e. (by implication) spirit, abstractly or concretely (the animal sentient principle only; thus distinguished on the one hand from G4151 (πνεῦμα), which is the rational and immortal soul; and on the other from G2222 (ζωή), which is mere vitality, even of plants: these terms thus exactly correspond respectively to the Hebrew H05315, H07307 and H02416).",
        "Strong's G5590, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        20,
        "a",
        "save",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Sṓzō (<em>σώζω</em>).</strong> to save, i.e. deliver or protect (literally or figuratively).",
        "Strong's G4982, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        20,
        "b",
        "way",
        "lang-greek",
        "Greek",
        "Greek.",
        "<strong>Hodós (<em>ὁδός</em>).</strong> a road; by implication, a progress (the route, act or distance); figuratively, a mode or means.",
        "Strong's G3598, A Concise Dictionary of the Words in the Greek Testament, James Strong (1894). PD.",
    ),
    (
        5,
        20,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Backsliding, Conversion, Death, Eternal, Missionaries, All Christians Should Be As.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    # (ch, v, suf, anchor, kind, title, label, body_html),
]

NOTES_JAM = NOTES  # backward-compat alias
