"""
Notes for The Book of Joshua (jos).

Migrated to content/notes/ in the Phase-1 refactor (2026-05-05). This is the
canonical home; legacy locations remain in place but should be considered frozen.

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    # ---- ch 1 ----
    (
        1,
        1,
        "",
        "Now after the death of Moses",
        "word",
        "Hebrew",
        "Hebrew",
        "<strong>Y’hoshu‘a (<em>יְהוֹשֻׁעַ</em>) — “Yahweh saves.”</strong> The Hebrew name from which Greek <em>Iēsous</em> (Jesus) descends. Joshua is the first person in the Bible to bear what is, etymologically, the name of Jesus. The book opens with a deliberate compositional move: <em>after the death of Moses</em>, exactly the cadence the Pentateuch closes with (Deut 34:5). The prose is signaling that this book continues the story rather than starting a new one — the Deuteronomistic History (Joshua–2 Kings) reads as a single literary arc.",
        'User original',
    ),
    (
        1, 3, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-deu-11-24">Deu 11:24</a> · <a href="#vnote-jos-14-9">Jos 14:9</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 3, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-deu-11-24">Deu 11:24</a> · <a href="#vnote-jos-14-9">Jos 14:9</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 5, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-rom-8-31">Rom 8:31</a> · <a href="#vnote-deu-31-6">Deu 31:6</a> · <a href="#vnote-mat-28-20">Mat 28:20</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 5, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-rom-8-31">Rom 8:31</a> · <a href="#vnote-deu-31-6">Deu 31:6</a> · <a href="#vnote-mat-28-20">Mat 28:20</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 6, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-dan-10-19">Dan 10:19</a> · <a href="#vnote-eph-6-10">Eph 6:10</a> · <a href="#vnote-jos-1-7">Jos 1:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 7, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ch-22-13">1Ch 22:13</a> · <a href="#vnote-deu-5-32">Deu 5:32</a> · <a href="#vnote-jos-1-8">Jos 1:8</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1,
        8,
        "",
        "meditate on it day and night",
        "comm",
        "Note",
        "Note",
        "<strong>The first commandment to a leader.</strong> Joshua’s commission opens not with military instruction but with Torah-meditation. The verb <em>hagah</em> (“meditate”) means to murmur or recite under one’s breath — Torah study as a continuous bodily practice, not silent reading. Psalm 1:2 echoes this verse almost verbatim, transferring the leader’s discipline to every righteous person. The juxtaposition is striking: Israel’s most aggressive military campaign begins with an order to recite a book.",
        'User original',
    ),
    (
        1, 8, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-psa-119-15">Psa 119:15</a> · <a href="#vnote-psa-19-14">Psa 19:14</a> · <a href="#vnote-col-3-16">Col 3:16</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 8, 'b', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-psa-119-15">Psa 119:15</a> · <a href="#vnote-psa-19-14">Psa 19:14</a> · <a href="#vnote-col-3-16">Col 3:16</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 9, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-gen-28-15">Gen 28:15</a> · <a href="#vnote-jer-1-7">Jer 1:7</a> · <a href="#vnote-jos-1-6">Jos 1:6</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        1, 9, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-gen-28-15">Gen 28:15</a> · <a href="#vnote-jer-1-7">Jer 1:7</a> · <a href="#vnote-jos-1-6">Jos 1:6</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    # ---- ch 2 ----
    (
        2,
        1,
        "",
        "a prostitute whose name was Rahab",
        "comm",
        "Note",
        "Note",
        "<strong>Rahab the Canaanite.</strong> A Canaanite woman, a prostitute, who hides Israelite spies and bargains for her family’s survival. The narrative protects her actively — she is the chapter’s moral center despite being a triple outsider (Canaanite, woman, sex worker). Matthew 1:5 lists her in the genealogy of Jesus; Hebrews 11:31 names her among the heroes of faith; James 2:25 cites her alongside Abraham as a model of justifying works. The book of Joshua contains both <em>ḥerem</em> (devoted destruction) and Rahab’s rescue — its theology is more layered than its surface campaign narrative suggests.",
        'User original',
    ),
    (
        3, 5, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-lev-20-7">Lev 20:7</a> · <a href="#vnote-jos-7-13">Jos 7:13</a> · <a href="#vnote-jol-2-16">Jol 2:16</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        3, 7, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-jos-4-14">Jos 4:14</a> · <a href="#vnote-jos-1-5">Jos 1:5</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    # ---- ch 3 ----
    (
        3,
        17,
        "",
        "on dry ground in the middle of the Jordan",
        "comm",
        "Note",
        "Note",
        "<strong>The Jordan crossing.</strong> The Red Sea miracle (Exod 14) now repeated at the Jordan — a deliberate literary frame around the wilderness generation. Moses led Israel <em>out</em> of Egypt through dry-ground waters; Joshua leads them <em>into</em> the land through dry-ground waters. The Ark of the Covenant replaces Moses’ staff as the agent of the miracle, signaling the transfer of mediation from prophet to cult. The flood-stage timing (3:15) is a historical detail; the upper Jordan blockage at Adam (about 30 km upstream) is geologically plausible — landslides have done it in recorded history (most recently 1927).",
        'User original',
    ),
    # ---- ch 5 ----
    (
        5,
        2,
        "",
        "Make flint knives, and circumcise",
        "comm",
        "Note",
        "Note",
        "<strong>Mass circumcision at Gilgal.</strong> The wilderness generation had not been circumcised (5:5) — a striking detail that the text explains by reference to ongoing journey conditions. The mass rite at Gilgal (“rolling place,” a wordplay on the “rolling away” of Egyptian reproach in 5:9) marks the threshold from wilderness wandering to covenantal land-life. The use of <em>flint</em> knives — a Bronze Age anachronism by the late settlement period — preserves an ancient ritual conservatism, like the use of unhewn stones for altars in Exod 20:25.",
        'User original',
    ),
    (
        5,
        13,
        "",
        "a man stood in front of him with his sword drawn",
        "comm",
        "Note",
        "Note",
        "<strong>The commander of Yahweh’s army.</strong> One of the more enigmatic theophanies in the Hebrew Bible. The figure is called “commander of Yahweh’s army” (5:14), refuses both human sides of the question (“Are you for us or for our adversaries?” — “No”), and demands Joshua remove his sandals (5:15) — a direct echo of Moses at the burning bush (Exod 3:5). Christian tradition reads the figure as a pre-incarnate Christ; rabbinic tradition reads him as the angel Michael. The narrative leaves the question deliberately open.",
        'User original',
    ),
    # ---- ch 6 ----
        (
        6, 20, '', 'the wall fell down flat',
        'comm-contextual', 'Note',
        'Note',
        '<strong>Jericho.</strong> Excavations at Tell es-Sultan (the site of ancient Jericho) have produced a famously contested archaeological record. Kathleen Kenyon’s mid-20th-century excavations dated the destruction layer to ~1550 BCE — significantly before any plausible Joshua timeframe (~1400–1200 BCE depending on chronology). Bryant Wood’s reanalysis in the 1990s argued for a later date (~1400 BCE) based on pottery typology, more consistent with the biblical narrative. The matter remains unsettled. Whatever the historical layer, the textual narrative is theologically focused: the wall falls because Israel marches and trumpets, not because they breach it — the city is given, not taken.',
        'User original',
    ),
    (
        6, 20, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-heb-11-30">Heb 11:30</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        6,
        21,
        "",
        "utterly destroyed all that was in the city",
        "word",
        "Hebrew",
        "Hebrew",
        "<strong>Ḥerem (<em>חֵרֶם</em>).</strong> “Devoted to destruction.” One of the most theologically and ethically difficult concepts in the Hebrew Bible — the absolute ban requiring destruction of all life in a captured city. Modern scholarship reads <em>ḥerem</em> through several lenses: as ancient Near Eastern total-war rhetoric (paralleled in the 9th-c. BCE Mesha Stele, where King Mesha of Moab claims to have devoted the Israelites of Nebo to <em>ḥerem</em>); as a theological category about radical separation from the land’s previous religious systems (Deut 7:1–6); or as a literary trope of completed conquest. The category troubled later Jewish and Christian readers alike — the rabbis declared the original ethnic referents extinct (and so the law inoperative); Christian readers have wrestled with it from Origen forward.",
        'User paraphrase; references Origen',
    ),
    (
        6, 26, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ki-16-34">1Ki 16:34</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        6, 26, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ki-16-34">1Ki 16:34</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    # ---- ch 7 ----
    (
        7,
        21,
        "",
        "a beautiful Babylonian robe",
        "comm",
        "Note",
        "Note",
        "<strong>The Achan story.</strong> A counter-narrative to Rahab. Where the Canaanite woman is saved with her household, the Israelite man is destroyed with his. Both stories turn on the question of <em>ḥerem</em>: Rahab is preserved <em>from</em> the ban by oath; Achan violates the ban and falls under it. The two stories together suggest that the narrative’s moral lines run through individuals, not through ethnic categories. The Hebrew of v. 21 specifies a “Shinar mantle” — Shinar being the biblical name for Babylonia, an early instance of the “Babylon as locus of luxurious idolatry” motif that recurs throughout scripture.",
        'User original',
    ),
    # ---- ch 8 ----
        (
        8, 30, '', 'Joshua built an altar to Yahweh, the God of Israel, on Mount Ebal',
        'comm-contextual', 'Note',
        'Note',
        '<strong>The Ebal altar.</strong> Joshua follows the Deuteronomic command (Deut 27:4–8) to build an altar on Mount Ebal upon entering the land. Adam Zertal’s excavations on Mount Ebal in the 1980s uncovered a large rectangular stone structure dated to the early Iron Age, which he identified as Joshua’s altar. The identification remains contested — alternative readings have been proposed (a watchtower, a different cultic installation) — but the site has become a focal point in the archaeology of early Israelite religion. A small lead curse tablet (the “Mount Ebal lead tablet,” published 2022) was recovered nearby, with a contested early Hebrew inscription invoking divine curse.',
        'User original',
    ),
    (
        9, 4, '', '',
        'text-witness', 'Witness',
        'MS.',
        "<strong>Manuscript witness.</strong> hat which has come down to us. The student of the Variorum Bible will find many passages in which they are quoted as differing fi'om the received text, sometimes for the better ; e.g. Deut. 33. 26 ; Josh. 9. 4 ; Judg. 5. 30 ; 2 Sam. 18. 13 ; 1 Kin. 13. 12 ; Ps. 100. 3 ; Isa. 49. 5 ; etc. They have this advantage at least over most of the other versions, that whenever we can be sure of the Hebrew text whic <em>[Reviewer: trim to the relevant clause; the surrounding context is provided so you can judge which version / witness Kenyon is discussing.]</em>",
        'Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.',
    ),
    # ---- ch 10 ----
    (
        10,
        12,
        "",
        "Sun, stand still on Gibeon",
        "comm",
        "Note",
        "Note",
        "<strong>The long day.</strong> One of the most dramatic miracle reports in scripture, framed as direct address: Joshua addresses the sun and moon. The book of Jashar (cited in v. 13) is one of about a dozen lost works the Hebrew Bible references — see also 2 Sam 1:18. Modern interpreters split: literal cosmological miracle, atmospheric refraction phenomenon, or poetic hyperbole quoted from a battle song. The text itself acknowledges its unusual character (10:14 — “there was no day like that before it or after it”), and the framing as quotation from a separate poetic source suggests the narrator is preserving an older tradition rather than asserting plain prose history.",
        'User original',
    ),
    (
        10, 12, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-hab-3-11">Hab 3:11</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        12, 12, '', '',
        'text-witness', 'Witness',
        'MS.',
        '<strong>Manuscript witness.</strong> en in the fifth century, with three columns to the page, and having (what is very unusual in early manuscripts) punctuation, accents, and breathings by the -- original scribe. It contains Gen. 31. 15 Josh. 12. 12, with many losses, however, from mutilation, and small fragments of Isaiah A and Malachi. Its evidence is valuable, and where and B differ it generally agrees with A. G. Codex Sarravianus, at L <em>[Reviewer: trim to the relevant clause; the surrounding context is provided so you can judge which version / witness Kenyon is discussing.]</em>',
        'Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.',
    ),
    # ---- ch 13 ----
    (
        13,
        1,
        "",
        "old and advanced in years",
        "comm",
        "Note",
        "Note",
        "<strong>The unfinished conquest.</strong> Chapter 13 marks a decisive narrative turn: Joshua is old, the land is not all conquered, and Yahweh tells him to assign the unconquered territories anyway. The book’s second half (chs 13–24) is concerned with land allotment, not with battles. The honest acknowledgment that significant Canaanite presence remained becomes a key theme of the book of Judges, which opens by listing precisely the territories Joshua failed to take. The conquest narrative is internally self-correcting — the Bible itself complicates the simple picture often associated with Joshua.",
        'User original',
    ),
    # ---- ch 14 ----
    (
        14,
        9,
        "",
        "because you have wholly followed Yahweh my God",
        "comm",
        "Note",
        "Note",
        "<strong>Caleb’s portion.</strong> The Kenizzite Caleb (a non-Israelite by ancestry — see Num 32:12, Josh 14:6) receives Hebron as his inheritance for fidelity at Kadesh-barnea forty-five years earlier (14:10). The narrative quietly preserves the genealogical complexity of early Israel: a non-Israelite of demonstrated loyalty receives one of the most sacred sites in the land — the patriarchal burial place at Machpelah. The Caleb tradition coexists with the more rigid genealogical boundaries of later texts.",
        'User original',
    ),
    # ---- ch 15 ----
    (
        15,
        63,
        "",
        "the Jebusites live with the children of Judah at Jerusalem",
        "comm",
        "Note",
        "Note",
        "<strong>The Jebusite remnant.</strong> Jerusalem is named, but it is not yet Israelite. The text matter-of-factly admits that Judah did not dispossess the city’s inhabitants. The capture of Jerusalem is delayed until David’s reign (2 Sam 5:6–9) — a foundational narrative in the Israelite monarchy. The “to this day” formula occurs ~80 times in the Deuteronomistic History; it almost always points to a state of affairs the editor wants the reader to understand as ongoing in their own time, providing internal evidence for the date of redaction.",
        'User original',
    ),
    (
        16, 59, '', '',
        'text-witness', 'Witness',
        'MS.',
        '<strong>Manuscript witness.</strong> that they had never formed part of it, and were never quoted or used on the same level as the books recognised as inspired. It is true that one verse has dropped out of a long list of towns (after Josh. 16. 59), in which was contained (as the Septuagint shows see Variorum ; fo <em>[Reviewer: trim to the relevant clause; the surrounding context is provided so you can judge which version / witness Kenyon is discussing.]</em>',
        'Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.',
    ),
    # ---- ch 20 ----
    (
        20,
        2,
        "",
        "cities of refuge",
        "comm",
        "Note",
        "Note",
        "<strong>The cities of refuge.</strong> Six designated cities (three in Cisjordan, three in Transjordan) where someone who killed accidentally could flee from the avenger of blood until trial. The system is one of the earliest known mechanisms for distinguishing manslaughter from murder, and replacing immediate retaliation with judicial process. Comparable institutions exist in Greek and Roman law (the Athenian Areopagus, Roman <em>asylum</em>), but the Hebrew system’s integration into the priestly cities and its religious framing are distinctive.",
        'User original',
    ),
    (
        21, 45, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ki-8-56">1Ki 8:56</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        21, 45, 'b', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ki-8-56">1Ki 8:56</a> · <a href="#vnote-jos-23-14">Jos 23:14</a> · <a href="#vnote-num-23-19">Num 23:19</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        22, 5, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-mat-22-37">Mat 22:37</a> · <a href="#vnote-exo-20-6">Exo 20:6</a> · <a href="#vnote-rom-8-28">Rom 8:28</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        22, 5, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-mat-22-37">Mat 22:37</a> · <a href="#vnote-exo-20-6">Exo 20:6</a> · <a href="#vnote-rom-8-28">Rom 8:28</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        23, 10, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-deu-32-30">Deu 32:30</a> · <a href="#vnote-lev-26-8">Lev 26:8</a> · <a href="#vnote-deu-3-22">Deu 3:22</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        23, 10, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-deu-32-30">Deu 32:30</a> · <a href="#vnote-lev-26-8">Lev 26:8</a> · <a href="#vnote-deu-3-22">Deu 3:22</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        23, 14, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-luk-21-33">Luk 21:33</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        24, 14, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1sa-12-24">1Sa 12:24</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        24, 14, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1sa-12-24">1Sa 12:24</a> · <a href="#vnote-deu-10-12">Deu 10:12</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    # ---- ch 24 ----
        (
        24, 15, '', 'choose today whom you will serve',
        'comm-contextual', 'Note',
        'Note',
        '<strong>The Shechem covenant.</strong> Joshua’s farewell ceremony at Shechem (24:1–28) reads as a covenant renewal in formal ancient Near Eastern shape: historical prologue (24:2–13), stipulations (24:14–15), people’s acceptance (24:16–18), warning (24:19–20), witnesses (24:22, 27), written record (24:25–26), monument (24:26b–27). The same pattern underlies the Sinai covenant in Exodus and the Hittite suzerainty treaties of the second millennium BCE. The “for me and my house” formula (24:15) has become one of the most-quoted lines in the book.',
        'User original',
    ),
    (
        24, 15, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ki-18-21">1Ki 18:21</a> · <a href="#vnote-jhn-6-67">Jhn 6:67</a> · <a href="#vnote-rut-1-15">Rut 1:15</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        24, 15, 'b', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-1ki-18-21">1Ki 18:21</a> · <a href="#vnote-jhn-6-67">Jhn 6:67</a> · <a href="#vnote-rut-1-15">Rut 1:15</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        24,
        29,
        "",
        "Joshua the son of Nun, the servant of Yahweh, died",
        "comm",
        "Note",
        "Note",
        "<strong>The closing.</strong> Joshua dies at 110 — the same age as Joseph (Gen 50:26), one of several literary symmetries between the two figures. The book closes with three burials: Joshua’s, Joseph’s bones (carried up from Egypt as promised in Gen 50:25), and Eleazar’s. The triple burial closes the Pentateuchal patriarchal arc and prepares the ground for the Judges era — when, the next book opens (Judg 2:10), <em>another generation arose who didn’t know Yahweh, nor the work which he had done for Israel</em>.",
        'User original',
    ),
    # ---- expansion (May 2026) ----
    (
        3,
        5,
        "",
        "Sanctify yourselves",
        "word",
        "Hebrew",
        "Hebrew",
        "<strong>Hitqaddashu (<em>הִתְקַדָּשׁוּ</em>).</strong> The reflexive of <em>qadash</em>, “make oneself holy.” In priestly contexts (Lev 11:44) holiness is a state cultivated through ritual purity; here on the eve of the Jordan crossing, the people are charged with the same disciplinary preparation soldiers undergo before holy war (Deut 23:9–14). The verb’s repetition across the conquest narratives signals that the campaign is framed not as land-acquisition but as ritual procession.",
        'User original',
    ),
    (
        6,
        17,
        "",
        "Only Rahab the prostitute shall live",
        "comm",
        "Note",
        "Note",
        "<strong>Rahab’s covenant.</strong> The instruction to spare Rahab is given in the same breath as the order to <em>ḥerem</em> the city. The book of Joshua holds these two together without resolving them — covenantal loyalty trumps ethnic boundary, and yet ethnic boundary is the announced rationale for ḥerem. The book’s ethics are not as flat as later readers sometimes assumed; the text itself complicates the rules it states.",
        'User original',
    ),
        (
        8, 1, '', 'go up to Ai',
        'comm-contextual', 'Note',
        'Note',
        '<strong>The second attempt at Ai.</strong> The Ai narrative is unusually long (chs 7–8) for a single town because of its theological work: Achan’s sin must be exposed and resolved before Israel can advance. The site of biblical Ai is contested — et-Tell, the most-discussed candidate, was unoccupied in the conquest period — and excavators have proposed alternative identifications (Khirbet el-Maqatir most prominently). As with Jericho, the archaeology and the text don’t cleanly align; reading both together remains an open scholarly question.',
        'User original',
    ),
    (
        9,
        15,
        "",
        "made a  covenant with them, to let them live",
        "comm",
        "Note",
        "Note",
        "<strong>The Gibeonite deception.</strong> The Gibeonites pretend to be from a far country to extract a covenant of peace, exempting themselves from the ḥerem of nearby cities (Deut 20:16–18). When the deception is exposed, Joshua honors the oath anyway (9:19) — covenants once sworn before Yahweh cannot be broken even when extracted by trickery. The principle resurfaces dramatically in 2 Sam 21, where Saul’s breach of this very covenant brings famine on Israel a generation later.",
        'User original',
    ),
    (
        11,
        20,
        "",
        "Yahweh to harden their hearts",
        "comm",
        "Note",
        "Note",
        "<strong>Hardening the heart, again.</strong> The same theological framing as Pharaoh in Exodus (4:21, 7:3, etc.). Israelite narrative attributes ultimate causation to God even where human agency is real. Modern readers tend to want a clean separation; the Hebrew Bible consistently refuses one. Compare 2 Sam 24:1 vs. 1 Chr 21:1 (Yahweh / Satan) — the narrators are willing to use either framing because the underlying theology of dual causation is unsystematic by design.",
        'User original',
    ),
    (
        17,
        3,
        "",
        "had no sons, but daughters",
        "comm",
        "Note",
        "Note",
        "<strong>Zelophehad’s daughters, again.</strong> The case from Numbers 27 is invoked as precedent: the five daughters of Zelophehad receive their inheritance in the actual land allotment. The narrative confirms that the legal innovation of Numbers actually went through — a small but meaningful detail. The Hebrew Bible is unusual in returning to specific legal cases by name across multiple books, treating them as binding precedent.",
        'User original',
    ),
        (
        20, 4, '', 'declare his case in the ears of the elders',
        'comm-contextual', 'Note',
        'Note',
        '<strong>The cities of refuge in operation.</strong> Joshua’s allotment chapters realize the Numbers 35 / Deut 19 institution. The cities — Kedesh, Shechem, Hebron west of the Jordan; Bezer, Ramoth, Golan east — are spaced to keep any Israelite within a day’s flight from refuge. The institution’s practical sophistication (assembly trial, burden of proof on the killer, distinction between intentional and accidental homicide) is one of the most advanced legal frameworks of the ancient Near East.',
        'User original',
    ),
    (
        22,
        28,
        "",
        "the pattern of Yahweh’s altar",
        "comm",
        "Note",
        "Note",
        "<strong>The altar by the Jordan.</strong> The trans-Jordanian tribes build a large altar; the cis-Jordanian tribes mobilize for civil war, suspecting apostasy. Resolution comes through a delegation and discussion: the altar is a memorial, not a sacrifice site (22:26–28). The episode is one of the few Old Testament cases where threatened intra-Israel violence is averted through dialogue. The Deuteronomistic insistence on <em>one</em> sanctuary (Deut 12) makes the question of additional altars instantly explosive.",
        'User original',
    ),
        (
        24, 2, '', 'Your fathers lived of old time beyond the River',
        'comm-rabbinic', 'Note',
        'Note',
        '<strong>The patriarchs in idolatry.</strong> Joshua’s farewell speech opens with an admission rarely highlighted: Israel’s ancestors served other gods before the call of Abraham. Genesis is silent on Terah’s religion, but Joshua (and Jewish midrash later, expansively) takes for granted that Abraham came out from idolatry rather than from prior monotheism. The implication: covenant election is not the recovery of an original Israelite identity but the creation of one out of pagan stock.',
        'User paraphrase; references midrash',
    ),
    # ---- heavy-pass: Joshua deepening (chs 4, 7, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23) ----
    (
        4,
        9,
        "",
        "twelve stones in the middle of the Jordan",
        "comm",
        "Note",
        "Note",
        '<strong>The two memorials.</strong> The chapter records two stone-monuments commemorating the Jordan crossing: twelve stones taken from the riverbed and set up at Gilgal (4:8, 20), and a parallel set placed in the riverbed where the priests stood (4:9). The doubling has long puzzled commentators — the underwater set is invisible once the river resumes flowing — and many critical readers (so Noth, Soggin) treat 4:9 as preserving an older Gilgal cult-etiology incompletely harmonized with the dominant Gilgal-stones tradition. Theologically, the two sets work together: the visible monument at Gilgal becomes the catechetical site (4:21–24, "when your children ask"), while the submerged stones inscribe the crossing into the very ground of the river — a permanent witness regardless of human attention. The duplication is one of the OT’s small, deliberate excesses: the redundancy is itself the testimony.',
        'User original',
    ),
    (
        7,
        25,
        "",
        "Why have you troubled us? Yahweh will trouble you today",
        "comm",
        "Note",
        "Note",
        '<strong>The pun on Achor.</strong> Joshua’s judgment plays on Achan’s name and the resulting place-name "Valley of Achor": the Hebrew root <em>‘kr</em> ("to trouble") generates "trouble-er" (Achan) and "Place of Trouble" (Achor) — the locale becomes a permanent linguistic monument to the violation. The execution is stark: stoning, burning, more stoning, with Achan’s family and livestock included (under the assumption that the contamination of <em>ḥerem</em> goods spreads through the household). Hosea will later invert the place-name: "I will give her the Valley of Achor for a door of hope" (Hos 2:15) — eschatological reversal of the place where covenant breach was punished into the place where covenant restoration begins. The OT preserves both directions of the etymology, holding judgment and mercy in the same toponym.',
        'User original',
    ),
    (
        9,
        23,
        "",
        "wood cutters and drawers of water",
        "comm",
        "Note",
        "Note",
        '<strong>The Gibeonite settlement.</strong> Joshua’s curse on the deceiving Gibeonites — perpetual servitude as wood-cutters and water-drawers for the sanctuary — institutionalizes their Israelite incorporation at the lowest cultic-economic rung. The arrangement carries forward: 2 Sam 21 narrates Saul’s violation of the oath sworn to them and David’s required atonement; Ezra 2:43 and 8:20 list the <em>n’tinim</em> ("the given ones") among returnees from exile, plausibly the Gibeonites’ liturgical successors. The chapter is one of the OT’s most morally complex texts on covenant, oath-keeping, and incorporation: a treaty obtained by deception is honored because the oath was taken in Yahweh’s name (9:18–20). The principle — that an oath sworn in good faith binds even when the basis is false — runs counter to ANE legal practice and registers an early Israelite theology of the irrevocable nature of vows pronounced before the deity.',
        'User original',
    ),
    (
        11,
        6,
        "",
        "hamstring their horses and burn their chariots",
        "comm",
        "Note",
        "Note",
        "<strong>Hamstringing the horses.</strong> The command to disable the captured horses and burn the chariots is theologically calibrated rather than militarily wasteful: chariots and horses were the elite military technology of the era (cf. Egyptian and Hittite chariot corps), and their possession by Israel would substitute reliance on weapons for reliance on Yahweh. Deut 17:16 explicitly forbids the future king to multiply horses; David later partially complies (2 Sam 8:4, hamstrings most chariot horses but keeps 100); Solomon abandons the principle entirely (1 Kgs 10:26–29, mass importing of Egyptian horses and chariots). Joshua’s obedience here — destroying the most valuable spoil rather than absorbing it into Israel’s military — sets a benchmark that the monarchy progressively fails. The verse is a quiet anticipation of the Deuteronomistic critique of the kings’ military buildup.",
        'User original',
    ),
        (
        12, 9, '', 'the king of Jericho, one',
        'comm-contextual', 'Note',
        'Note',
        '<strong>The catalog of thirty-one kings.</strong> The chapter’s formal list — thirty-one defeated city-kings, named individually with the laconic formula "one" appended — preserves the political geography of late Bronze Age Canaan with surprising precision. Most of the cities named (Jericho, Ai, Jerusalem, Hebron, Lachish, Gezer, Megiddo, Hazor, etc.) are archaeologically attested as Canaanite city-state capitals in the Late Bronze / early Iron I horizon, each governed independently — exactly the political fragmentation reflected in the Amarna correspondence (14th c. BCE), where Canaanite city-rulers individually petition the Egyptian pharaoh. The literary form of the list (king-by-king, with the repeated "one") echoes Egyptian royal triumph-inscriptions; the chapter is using a recognized ANE genre. Whether the historical pattern of conquest matches this catalog is hotly debated (Albright vs. Alt vs. Mendenhall vs. Finkelstein), but the political tableau the list assumes — many small kingdoms, no Egyptian over-presence — is consistent with the actual political reality of the relevant period.',
        'User original',
    ),
    (
        13,
        14,
        "",
        "no inheritance to the tribe of Levi",
        "comm",
        "Note",
        "Note",
        '<strong>Levi’s missing inheritance.</strong> The Levites receive no contiguous tribal territory; their "inheritance" is the offerings of Yahweh (here and in 13:33; cf. Num 18:20, Deut 18:1–2). The arrangement is theologically and politically calibrated: Levi’s scattering across forty-eight cities (Josh 21) embeds priestly-instructional presence in every tribal area, and the absence of a Levitical territorial bloc prevents the priesthood from accumulating a political base. The structure becomes one of the OT’s great institutional innovations — a priestly class supported by the entire confederation rather than by control of land — and it preserves a meaningful church-state separation across the tribal era. The price is Levitical economic vulnerability: when the offering system is disrupted (cf. Neh 13:10, Levites returning to their fields because tithes have stopped), the institution’s viability collapses immediately.',
        'User original',
    ),
    (
        14,
        6,
        "",
        "You know the thing that Yahweh spoke to Moses",
        "comm",
        "Note",
        "Note",
        '<strong>Caleb’s claim at Gilgal.</strong> Caleb invokes the divine promise from Num 14:24, made at Kadesh forty-five years earlier: because Caleb (alone with Joshua, of the wilderness generation) trusted the spies’ minority report, he was promised a portion in the land. The verse is one of the OT’s clearest cases of long-deferred personal promise: forty-five years of wilderness wandering and conquest separate the oath from its fulfillment. Caleb’s extraordinary status — at 85 he is still strong "to go out and to come in" (14:11) — is the narrative reward for forty-five years of waiting. The episode also registers the chapter’s central principle: territorial allotment is not arbitrary distribution but the working out of accumulated covenantal obligations, with named persons receiving named promises across generational distance.',
        'User original',
    ),
    (
        15,
        18,
        "",
        "She got off her donkey",
        "comm",
        "Note",
        "Note",
        "<strong>Achsah’s springs.</strong> Caleb’s daughter, given to Othniel for the capture of Debir, dismounts to ask her father not just for land (the dry Negev field already promised) but also for water sources — the upper and lower springs (15:19). The episode preserves a rare narrative window on female property-claim in pre-monarchic Israel: Achsah negotiates directly with her father over the conditions of her dowry, and the request is granted in full. Her dismounting is significant — descending from one’s donkey to make a request was a recognized gesture of formal petition (cf. Abigail’s similar dismounting in 1 Sam 25:23). The Caleb-Achsah-Othniel triangle is one of the OT’s small portraits of effective female agency within the patriarchal property system, and it directly precedes Othniel’s appearance as the first major judge in Judg 3 — the marriage produces the deliverer.",
        'User original',
    ),
    (
        16,
        10,
        "",
        "didn’t drive out the Canaanites who lived in Gezer",
        "comm",
        "Note",
        "Note",
        '<strong>The unfinished conquest.</strong> The chapter’s closing verse is one of seven similar admissions sprinkled through Joshua and Judges 1: a tribe’s conquest is incomplete; Canaanites remain. The narrative tension with chapters like 11:23 ("Joshua took the whole land") is real and editorial. Most scholars (so M. Noth) read the conquest narrative as compressing decades or centuries of intermittent and incomplete settlement into a stylized conquest-rhetoric, with verses like 16:10, 17:12–13, 19:47 preserving the historical residue. Gezer specifically remained Canaanite until Solomon’s reign (1 Kgs 9:16), when the pharaoh of Egypt captured it and gave it to Solomon as his daughter’s dowry — a four-century gap between this verse and the city’s eventual incorporation. The geography of incomplete conquest sets up the entire deliverer-cycle of Judges.',
        'User original',
    ),
    (
        17,
        14,
        "",
        "Why have you given me just one lot and one part for an inheritance",
        "comm",
        "Note",
        "Note",
        "<strong>The Joseph tribes’ complaint.</strong> Ephraim and Manasseh — the two Joseph-derived tribes — protest that their allotment is inadequate for their numbers. Joshua’s response is structurally significant: rather than redistribute, he tells them to clear the forested hill country themselves, including dispossessing the Canaanites who hold the iron chariots in the valleys (17:18). The episode is one of the OT’s frankest acknowledgments of demographic-territorial pressure within the tribal system, and Joshua’s reply embodies a recurring biblical pattern: divine gift of land does not exempt the recipients from labor and risk. The Joseph tribes’ complaint will produce, centuries later, the political base of the northern kingdom — Ephraim’s sense of insufficient honor and territory will be the structural grievance Jeroboam I exploits at the schism in 1 Kgs 12.",
        'User original',
    ),
        (
        18, 1, '', 'set up the Tent of Meeting there',
        'comm-contextual', 'Note',
        'Note',
        '<strong>The move to Shiloh.</strong> The Tent of Meeting — the wilderness sanctuary, with the Ark inside — relocates from Gilgal (the original conquest base camp) to Shiloh, in central Ephraim. The shift inaugurates roughly three and a half centuries of Shiloh as Israel’s premier cult site, until the Philistine destruction of Shiloh in the eleventh century BCE (cf. Jer 7:12, 26:6, where the prophet repeatedly invokes Shiloh’s ruin as a warning to Jerusalem; archaeological excavation at Khirbet Seilun has confirmed the eleventh-century destruction layer). The verse is the institutional founding of the Shiloh sanctuary, where Eli will preside at the opening of 1 Samuel and where Hannah will dedicate Samuel. The choice of central Ephraim (rather than Jerusalem or Hebron) reflects pre-monarchic geography: the central hill country was the sociological core of early Israel, and Shiloh’s position made it accessible from all the tribal territories.',
        'User original',
    ),
    (
        19,
        50,
        "",
        "Timnathserah",
        "comm",
        "Note",
        "Note",
        '<strong>Joshua’s own inheritance.</strong> The chapter ends with Joshua receiving his personal inheritance — but only after every other tribe has received theirs. The order is theologically calibrated: Israel’s leader takes his portion last, after seeing every other family settled. The town he selects, Timnath-serah ("portion of the sun" or "extra portion"), in the hill country of Ephraim, becomes his burial site (Josh 24:30). The implicit contrast with later monarchical practice is sharp: David takes Jerusalem first (2 Sam 5), Solomon builds his palace before Yahweh’s temple (1 Kgs 7), Ahab seizes Naboth’s vineyard for landscaping (1 Kgs 21). Joshua’s last-place inheritance is the inverse — the leader who gives before he receives, who builds his city only after every other tribe has its city. The pattern becomes a long-running counter-image to royal land-greed.',
        'User original',
    ),
    (
        21,
        45,
        "",
        "Nothing failed of any good thing",
        "comm",
        "Note",
        "Note",
        '<strong>The covenant fulfillment formula.</strong> The verse is a Deuteronomistic theological summary: every promise Yahweh made to the patriarchs about the land has been kept. The formula is rhetorically absolute ("not one word"), and its placement is structural — it closes the conquest-and-allotment narrative arc that began in Josh 1, before the farewell-and-renewal section of chs 22–24. The same formula recurs at 23:14 ("not one word has failed of all the good words"). The deuteronomistic editor frames the conquest as a complete divine performance, even as the same book has admitted (16:10, 17:12, etc.) that the conquest was practically incomplete. The theological judgment overrides the geographical reality: from the editor’s perspective, what Yahweh promised was given; what Israel has not taken is Israel’s own deferred work, not Yahweh’s default. The verse is the load-bearing summary of the book’s theology of land.',
        'User original',
    ),
    (
        22,
        10,
        "",
        "a  great altar",
        "comm",
        "Note",
        "Note",
        "<strong>The altar by the Jordan — and what it almost cost.</strong> The trans-Jordanian tribes’ memorial-altar nearly precipitates the OT’s first major Israelite-on-Israelite war: the cis-Jordanian tribes mobilize for full <em>ḥerem</em> against their kin (22:11–12), assuming the altar is an apostate sacrifice site competing with Shiloh. Phinehas leads the delegation that resolves it through direct dialogue (22:13–34), a striking OT precedent for averting religious civil war through structured conversation rather than force. The episode embeds the Deuteronomistic insistence on cult centralization (Deut 12) at the level of inter-tribal politics: even a memorial altar, built explicitly not for sacrifice, is dangerous because it could be misread. The chapter is one of the OT’s most thoughtful treatments of how shared symbols can become the focal points of unintended conflict — and how communication, not force, defuses them.",
        'User original',
    ),
    (
        23,
        12,
        "",
        "make marriages with them",
        "comm",
        "Note",
        "Note",
        "<strong>The intermarriage warning.</strong> Joshua’s farewell explicitly forbids intermarriage with the surviving Canaanites — not on ethnic grounds but on theological ones, on the principle that intermarriage produces religious assimilation (cf. Deut 7:3–4). The principle will become one of the most charged topics of post-exilic Yahwism: Ezra 9–10 and Nehemiah 13 record forced divorces from foreign wives as the founding act of restored Yahwistic identity. The OT’s own counter-tradition is significant: Moses married a Cushite (Num 12:1), Boaz married Ruth the Moabite (canonized as Davidic ancestor), and the prophets of the Solomonic-and-after period frequently move between cultures. Joshua’s warning is practical theology rather than ethnic prescription, but its later weaponization in post-exilic communal definition demonstrates how a single verse can be re-applied to political ends across centuries. The verse is a foundational text in the OT debate over Israelite identity by descent vs. by covenant fidelity.",
        'User original',
    ),
    # ---- close-out: bring chs 4, 12, 16, 18, 19, 21, 23 to ≥2 ----
    (
        4,
        21,
        "",
        "When your children ask their fathers in time to come",
        "comm",
        "Note",
        "Note",
        '<strong>The catechetical formula.</strong> The phrase "when your children ask" is one of the OT’s most distinctive pedagogical formulas, recurring in Exod 12:26, 13:14, Deut 6:20, and here. Each occurrence anchors a major covenantal memory (Passover, the firstborn, the covenant law, the Jordan crossing) to a household-level transmission rite: the answer is given in the form of a memorized historical confession, not a doctrine. The formula is one of the OT’s most explicit windows on early Israelite religious education — instruction was conducted at the level of the family, triggered by tangible memorials (matzah, mezuzah, stones), and structured around the child’s spontaneous question. The Passover Haggadah preserves the form to this day, with its four-questions framework descending directly from this textual pattern.',
        'User original',
    ),
    (
        12,
        24,
        "",
        "all the kings thirty-one",
        "comm",
        "Note",
        "Note",
        '<strong>The summary count.</strong> The chapter closes its catalog with a numeric total — thirty-one defeated kings — that itself functions as the chapter’s rhetorical climax. The number is large enough to register as comprehensive without being so symmetrical (e.g., not seventy or twelve) as to feel idealized. Comparable summary-counts appear in Egyptian conquest inscriptions of the Late Bronze Age (Thutmose III’s campaigns at Megiddo list 119 captured towns). The chapter functions as a kind of triumph-stele in narrative form, a rhetorical genre Israel’s scribes adopted from the surrounding empires and re-deployed in service of Yahweh’s sovereignty rather than a human king’s. The next chapter will turn from the conquest catalog to the unfinished work that remains (13:1, "much land yet to be possessed") — the book’s pivot from celebration to administration.',
        'User original',
    ),
    (
        16,
        3,
        "",
        "Beth Horon the lower",
        "comm",
        "Note",
        "Note",
        "<strong>The Beth-Horon corridor.</strong> The two Beth-Horons (Upper and Lower) sit on the strategic ascent from the coastal plain to the Benjamin-Ephraim hill country — the route an invader from the west had to use to reach the central highlands. The road’s tactical importance is attested across millennia: Joshua descends it to defeat the Amorite coalition (10:10–11), Saul defends it (1 Sam 13:18), Solomon fortifies the Upper city (2 Chr 8:5), the Maccabees ambush a Seleucid army on it (1 Macc 3:16, 7:39), and the Roman legate Cestius Gallus is destroyed in the same pass during the First Jewish War (66 CE). Few topographical features in the Holy Land have so consistently determined military outcomes. The verse’s placement of the road within Ephraim’s allotment is one of the chapter’s small geographic specifications that has long-running historical consequence.",
        'User original',
    ),
    (
        18,
        10,
        "",
        "cast lots for them in Shiloh",
        "comm",
        "Note",
        "Note",
        '<strong>The lottery procedure.</strong> Land-allotment by lot is one of the OT’s recurring divinely-mediated decision procedures (cf. the lots that identify Achan in Josh 7, Saul in 1 Sam 10:20–21, Jonah in Jonah 1:7, Matthias in Acts 1:26). The mechanism — likely involving inscribed stones drawn from a vessel, possibly the Urim and Thummim themselves — assumes that randomness, when invoked formally before Yahweh, is the medium through which divine choice manifests (cf. Prov 16:33, "the lot is cast into the lap, but its every decision is from Yahweh"). The use of lots for territorial allotment makes the resulting borders theologically nonnegotiable: a tribe’s portion is not the result of political calculation but of divine assignment. The principle becomes embedded in later Israelite property law (Lev 25, the Jubilee return of land to original allotments) — land cannot be permanently sold because it was never the seller’s in the first place; it was Yahweh’s, given to that family by lot.',
        'User original',
    ),
    (
        19,
        1,
        "",
        "Their inheritance was in the middle of the inheritance",
        "comm",
        "Note",
        "Note",
        '<strong>Simeon absorbed into Judah.</strong> The notice that Simeon’s allotment lay <em>inside</em> Judah’s territory is significant: Simeon receives no contiguous tribal bloc but is settled as enclaves within the larger southern tribe. The arrangement reflects Jacob’s deathbed pronouncement on Simeon and Levi in Gen 49:5–7 ("I will divide them in Jacob, and scatter them in Israel") — punishment for the Shechem massacre (Gen 34) realized two generations later as territorial dissolution. Simeon’s identity dwindles across the OT: minor notices in 1 Chr 4:24–43 record Simeonite migrations into Edomite territory; by the time of the post-exilic returns the tribe has functionally vanished. The verse is one of the OT’s most concrete demonstrations of how a deathbed prophecy becomes territorial fact, and of the principle that ancestral acts have generation-spanning political consequences.',
        'User original',
    ),
    (
        21,
        3,
        "",
        "these cities with their pasture lands",
        "comm",
        "Note",
        "Note",
        '<strong>The forty-eight Levitical cities.</strong> Forty-eight cities scattered across all twelve tribal territories, each with surrounding pasturage, distributed to the priestly tribe — six of them designated as cities of refuge (Num 35:6). The arrangement is one of the OT’s most institutionally creative provisions: a priestly class without territorial concentration, distributed throughout the federation, supported by tithe and offering rather than by contiguous land-rule. The system creates priestly-instructional presence in every region (cf. Deut 33:10, Levi’s vocation to "teach Jacob your ordinances and Israel your law") while preventing the priesthood from forming an independent political base. Whether all forty-eight cities were ever actually fully settled by Levites is debated by historians (some are clearly idealized), but the principle the chapter encodes — embedded religious instruction across all territorial divisions — became an enduring feature of Israelite institutional life.',
        'User original',
    ),
        (
        23, 14, '', 'I am going the way of all the earth',
        'comm-contextual', 'Note',
        'Note',
        '<strong>"The way of all the earth."</strong> Joshua’s phrase — picked up at David’s deathbed in 1 Kgs 2:2 — is one of the OT’s most graceful idioms for natural death. The phrase locates dying within universal creaturely existence rather than as defeat or as cultic problem; the Hebrew speaker is acknowledging mortality as the shared human inheritance. The idiom carries no resignation: Joshua immediately follows with the affirmation that not one of Yahweh’s good promises has failed (23:14b). The contrast with the surrounding ANE cultures is sharp — Mesopotamian death-laments tend toward despair (Gilgamesh, Akkadian wisdom literature), Egyptian funerary texts toward elaborate cosmic continuation. Israelite death-language at its best, as in Joshua’s and David’s farewell speeches, registers neither — only acceptance of mortality combined with confident testimony to the divine fidelity that has framed the life now ending.',
        'User paraphrase; references Gilgamesh',
    ),
    (
        1,
        8,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>The Torah-meditation theme.</strong> Joshua opens with the same theme that opens the Psalter (Ps 1:2). The verb <em>hagah</em> ("meditate") originally means to mutter or murmur — meditation in the Hebrew Bible is verbal, the lips moving. Joshua’s leadership is grounded not in his sword-arm but in his constant rumination on Torah. The chapter sets the model for the ideal Davidic king of Deut 17:18–20.""",
        'User original',
    ),
    (
        2,
        11,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>Rahab’s confession.</strong> A Canaanite prostitute makes the most theologically explicit confession in the entire conquest narrative. Hebrews 11:31 and James 2:25 both highlight her as a paradigm of faith. Matthew 1:5 includes her in Jesus’s genealogy — one of four named women in the line. The book of Joshua’s ostensible policy of <em>ḥerem</em> is repeatedly complicated by the texts surrounding it: Rahab spared, the Gibeonites preserved, exclusions and inclusions cutting across ethnic lines.""",
        'User original',
    ),
    (
        5,
        14,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>The mysterious commander.</strong> Joshua meets a figure with a drawn sword who refuses both the "for us" and "for our enemies" labels — "No, but I have come now as commander of Yahweh’s army." The episode parallels Moses at the burning bush ("take your sandals off"). Christian tradition has read the figure as a christophany; Jewish tradition as the angel of presence (cf. Exod 23:20–21). The encounter reframes the conquest: God is not a partisan; God’s side is its own.""",
        'User original',
    ),
    (
        10,
        13,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>The sun and moon at Gibeon.</strong> Cited from "the book of Jashar" (also referenced in 2 Sam 1:18) — a lost early collection of Israelite war-poetry. Whether read literally or as poetic hyperbole, the line memorialized a battle so decisive that nature itself seemed to participate. Habakkuk 3:11 echoes the imagery. Of the Bible’s many lost books — Jashar, the Wars of the LORD (Num 21:14) — only fragments survive in citation.""",
        'User original',
    ),
    (
        24,
        15,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>Joshua’s farewell.</strong> The closing chapter is structured as a covenant-renewal ceremony with all the formal elements: prologue (vv.2–13), stipulations (vv.14–15), oath (vv.16–24), witness (vv.25–28). "As for me and my house, we will serve Yahweh" has become one of the most quoted Old Testament lines in Christian household devotion.""",
        'User original',
    ),
]

NOTES_JOS = NOTES  # backward-compat alias
