"""
Notes for The Book of Micah (mic).

No notes yet — add tuples to the NOTES list below or use:
    python3 scripts/add_note.py --book mic --ch <N> --v <V> --anchor "…" \
        --kind comm --title "…" --body "…"

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    (
        1, 1, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 1, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: AHAZ, WARNINGS AOAINST, IVIICAH, PROPHETS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 2, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 2, 'a', 'GOD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 2, 'b', 'Lord',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 2, 'c', 'holy',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Qâdôwsh (<em>קָדוֹשׁ</em>).</strong> sacred (ceremonially or morally); (as noun) God (by eminence), an angel, a saint, a sanctuary. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6918, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 2, 'd', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CHURCH, TEMPLE, TEMPLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 3, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 3, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 3, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 4, '', 'waters',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Mayim (<em>מַיִם</em>).</strong> water; figuratively, juice; by euphemism, urine, semen. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H4325, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 4, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        "<strong>Topics.</strong> This verse appears under: MOUNTAIN, VOLCAIN'OES, WAX. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 5, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: JERUEL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 7, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: IDOLATRY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 8, '', 'naked',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʻârôwm (<em>עָרוֹם</em>).</strong> nude, either partially or totally. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6174, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 8, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DOXOLOGY, OSTRICHES, OSTRICHES, OWL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 10, '', 'dust',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʻâphâr (<em>עָפָר</em>).</strong> dust (as powdered or gray); hence, clay, earth, mud. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6083, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 10, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: APHRAH, BETH-EL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 11, '', 'naked',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʻârôwm (<em>עָרוֹם</em>).</strong> nude, either partially or totally. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6174, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 11, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: SAPH IK, ZAANAN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 12, '', 'good',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 12, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 12, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DKLIVEIIANCE FROM, MARKJIT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 13, '', 'sin',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chaṭṭâʼâh (<em>חַטָּאָה</em>).</strong> an offence (sometimes habitual sinfulness), and its penalty, occasion, sacrifice, or expiation; also (concretely) an offender. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2403, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 13, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CIIAKIOT, LACK. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 15, '', 'glory',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Kâbôwd (<em>כָּבוֹד</em>).</strong> properly, weight, but only figuratively in a good sense, splendor or copiousness. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H3519, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1, 15, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: ADULLAM, MARESHAH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1, 16, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BALANCES, EAGLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 1, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-32-7">Isa 32:7</a> · <a href="#vnote-psa-36-4">Psa 36:4</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        2, 1, 'a', 'light',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 1, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: LANCE, MALICE, IVIICAH, OPPRESSION, RISING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 2, '', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 2, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CHAPITER, COVETOUSNESS, MONOPOLY, OPPRESSION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 3, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 3, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 5, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 5, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CORD, LOT, ROPE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 6, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: WORD OF GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 7, '', 'spirit',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 7, 'a', 'good',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 7, 'b', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 7, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: HOLY SPIRIT, WORD OF GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 9, '', 'glory',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Kâbôwd (<em>כָּבוֹד</em>).</strong> properly, weight, but only figuratively in a good sense, splendor or copiousness. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H3519, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 9, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DIVORCE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 10, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: ISRAEL, WORLDLINESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 11, '', 'spirit',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 11, 'a', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 11, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DRUNKENNESS, MINISTER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 12, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BOZKAH, ISRAEL, IVIICAH, SHEEP. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2, 13, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-52-12">Isa 52:12</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        2, 13, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2, 13, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 1, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CHRISTIAN, GOVERNMENT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 2, '', 'good',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 2, 'a', 'love',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 2, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: EXTORTION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 4, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 4, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: NATIONAL, WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 5, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 5, 'a', 'Peace',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Shâlôwm (<em>שָׁלוֹם</em>).</strong> safe, i.e. (figuratively) well, happy, friendly; also (abstractly) welfare, i.e. health, prosperity, peace. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H7965, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 5, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: MINISTER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 6, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: ECLIPSE, SORCERY, SUN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 7, '', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 7, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: MOURNING, PROPHETS, SORCERY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 8, '', 'spirit',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 8, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 8, 'b', 'sin',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chaṭṭâʼâh (<em>חַטָּאָה</em>).</strong> an offence (sometimes habitual sinfulness), and its penalty, occasion, sacrifice, or expiation; also (concretely) an offender. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2403, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 8, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: HOLY SPIRIT, POWER, PROPHETS, ZEAL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3, 10, '', 'blood',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Dâm (<em>דָּם</em>).</strong> blood (as that which when shed causes death) of man or an animal; by analogy, the juice of the grape; figuratively (especially in the plural) bloodshed (i.e. drops of blood). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H1818, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 11, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3, 11, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CONFIDENCE, SENTENCE OF, COVETOUSNESS, HYPOCRISY, MONEY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 1, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-2-1">Isa 2:1</a> · <a href="#vnote-jer-3-17">Jer 3:17</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        4, 1, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 1, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GOSPEL, JESUS, JESUS, REVIVALS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 2, '', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 2, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 2, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CHURCH, JERUEL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 3, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-2-4">Isa 2:4</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        4, 3, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CHURCH, GENNESARET, JESUS, NATION, PKUXING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 4, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 4, 'a', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 5, '', 'god',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 5, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 5, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 6, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 7, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 7, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 8, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: EDAR, JERUEL, SHEPHERD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 9, '', 'woman',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 10, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 10, 'a', 'woman',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 10, 'b', 'redeem',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        "<strong>Gâʼal (<em>גָּאַל</em>).</strong> to be the next of kin (and as such to buy back a relative's property, marry his widow, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H1350, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 12, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 12, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BLINDNESS, PROVIDENCE OF. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4, 13, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 13, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4, 13, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: HORN, IRON. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 1, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: SENTENCE OF, JESUS, JESUS, PERSECUTION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 2, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-mat-2-6">Mat 2:6</a> · <a href="#vnote-jhn-7-42">Jhn 7:42</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        5, 2, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-mat-2-6">Mat 2:6</a> · <a href="#vnote-jhn-7-42">Jhn 7:42</a> · <a href="#vnote-isa-9-6">Isa 9:6</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        5, 2, 'b', '',
        'text-witness', 'Witness',
        'MS.',
        '<strong>Manuscript witness.</strong> ; seeing that the same identification is repeated in four other places, including the much more strongly Messianic passage in Micah 5. 2, the omission in Joshua alone would be perfectly useless for party purposes, and may much more fairly be explained as an accident. It is needless to add that the greater prophecies of the Messiah, <em>[Reviewer: trim to the relevant clause; the surrounding context is provided so you can judge which version / witness Kenyon is discussing.]</em>',
        'Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.',
    ),
    (
        5, 2, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BETH-JOAB, BETH-JOAB, CHURCH, EPHRATAH, ETERNITY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 4, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 4, 'a', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 4, 'b', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 4, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: JESUS, JESUS, JESUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 5, '', 'land',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 5, 'a', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 5, 'b', 'peace',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Shâlôwm (<em>שָׁלוֹם</em>).</strong> safe, i.e. (figuratively) well, happy, friendly; also (abstractly) welfare, i.e. health, prosperity, peace. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H7965, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 5, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: SEVEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 6, '', 'land',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 6, 'a', 'waste',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Tôhûw (<em>תֹּהוּ</em>).</strong> a desolation (of surface), i.e. desert; figuratively, a worthless thing; adverbially, in vain. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H8414, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 6, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: ASSYKIA. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 7, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 7, 'a', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 7, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: RIGHTEOUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 8, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: LION, RIGHTEOUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 10, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 11, '', 'land',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5, 12, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: SORCERY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 13, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: WARNINGS AOAINST. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 14, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GROUND. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5, 15, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: IDOLATRY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 1, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-jer-22-29">Jer 22:29</a> · <a href="#vnote-deu-32-1">Deu 32:1</a> · <a href="#vnote-mic-1-2">Mic 1:2</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        6, 1, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-jer-22-29">Jer 22:29</a> · <a href="#vnote-deu-32-1">Deu 32:1</a> · <a href="#vnote-mic-1-2">Mic 1:2</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        6, 1, 'b', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 1, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CONDEMNATION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 2, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 2, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 2, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: REASONING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 3, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: INGRATITUDE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 4, '', 'land',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 4, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: AARON, MIKIAM, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 5, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 5, 'a', 'righteousness',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Tsedeq (<em>צֶדֶק</em>).</strong> the right (natural, moral or legal); also (abstractly) equity or (figuratively) prosperity. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6664, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 5, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BALAAM, BALAK, MOAB, SHITTIM. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 6, '', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 6, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 6, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CALF, FORMALISM, MKAT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 7, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 7, 'a', 'soul',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 7, 'b', 'sin',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chaṭṭâʼâh (<em>חַטָּאָה</em>).</strong> an offence (sometimes habitual sinfulness), and its penalty, occasion, sacrifice, or expiation; also (concretely) an offender. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2403, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 7, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: IDOLATRY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 8, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-deu-10-12">Deu 10:12</a> · <a href="#vnote-pro-21-3">Pro 21:3</a> · <a href="#vnote-col-3-12">Col 3:12</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        6, 8, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-deu-10-12">Deu 10:12</a> · <a href="#vnote-pro-21-3">Pro 21:3</a> · <a href="#vnote-col-3-12">Col 3:12</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        6, 8, 'b', 'good',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 8, 'c', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 8, 'd', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 8, 'e', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 8, 'f', 'love',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 8, 'g', 'mercy',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chêçêd (<em>חֵסֵד</em>).</strong> kindness; by implication (towards God) piety; rarely (by opposition) reproof, or (subject.) beauty. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2617, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 8, 'h', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: HOLINESS TO THE LORD, HUMILITY, INTEGRITY, MERCY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 9, '', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 9, 'a', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 9, 'b', 'wisdom',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chokmâh (<em>חׇכְמָה</em>).</strong> wisdom (in a good sense). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2451, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6, 9, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DKLIVEIIANCE FROM, PRAYER FOR THE AFFLICTED, KESHEPH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 10, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DISHAN, MEASURE, WEIGHTS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 11, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BALANCES, PUKITY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 13, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 14, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: WORLDLINESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6, 16, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: AHAB, COMPANY, OMRI. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 1, '', 'soul',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 1, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DESPONDENCY, FEAR OF GOD, GLEANING, SUMMKK, ZEAL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 2, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 2, 'a', 'good',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 2, 'b', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 2, 'c', 'blood',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Dâm (<em>דָּם</em>).</strong> blood (as that which when shed causes death) of man or an animal; by analogy, the juice of the grape; figuratively (especially in the plural) bloodshed (i.e. drops of blood). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H1818, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 2, 'd', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DEPRAVITY OF MAN, WICKED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 3, '', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 3, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BRIBERY, CHAPITER, CHAPITER, SENTENCE OF, COVETOUSNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 4, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: HEDGE, THORN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 5, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-jer-9-4">Jer 9:4</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 5, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-jer-9-4">Jer 9:4</a> · <a href="#vnote-psa-118-8">Psa 118:8</a> · <a href="#vnote-mat-10-16">Mat 10:16</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 5, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: HYPOCRISY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 6, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-mat-10-35">Mat 10:35</a> · <a href="#vnote-luk-12-53">Luk 12:53</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 6, 'a', 'man',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 6, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CHILDREN, DAUGHTER, JESUS, IN THE NEW TESTAMENT FROM, WALLS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 7, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-lam-3-25">Lam 3:25</a> · <a href="#vnote-psa-37-7">Psa 37:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 7, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-lam-3-25">Lam 3:25</a> · <a href="#vnote-psa-37-7">Psa 37:7</a> · <a href="#vnote-1jn-5-14">1Jn 5:14</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 7, 'b', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 7, 'c', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 7, 'd', 'salvation',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Yᵉshûwʻâh (<em>יְשׁוּעָה</em>).</strong> something saved, i.e. (abstractly) deliverance; hence, aid, victory, prosperity. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H3444, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 7, 'e', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: TIES, FAITH, WAITING, WAITING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 8, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-jhn-8-12">Jhn 8:12</a> · <a href="#vnote-psa-27-1">Psa 27:1</a> · <a href="#vnote-isa-9-2">Isa 9:2</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 8, 'a', 'darkness',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chôshek (<em>חֹשֶׁךְ</em>).</strong> the dark; hence (literally) darkness; figuratively, misery, destruction, death, ignorance, sorrow, wickedness. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2822, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 8, 'b', 'light',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 8, 'c', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 8, 'd', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: DARKNESS, WALLS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 9, '', 'light',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 9, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 9, 'b', 'righteousness',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Tsedeq (<em>צֶדֶק</em>).</strong> the right (natural, moral or legal); also (abstractly) equity or (figuratively) prosperity. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6664, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 9, 'c', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: PRAYER FOR THE AFFLICTED, PROVIDENCE OF, REPENTANCE, KESHEPH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 10, '', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 10, 'a', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 10, 'b', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: INFIDELITY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 11, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: FKNCE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 13, '', 'land',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 13, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CONSEQUENCES OF. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 14, '', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: BARZILLAI, CAKEAH, INTERCESSION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 15, '', 'land',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, '', 'earth',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, 'a', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, 'b', 'LORD',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, 'c', 'dust',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʻâphâr (<em>עָפָר</em>).</strong> dust (as powdered or gray); hence, clay, earth, mud. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H6083, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, 'd', 'serpent',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Nâchâsh (<em>נָחָשׁ</em>).</strong> a snake (from its hiss). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H5175, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, 'e', 'fear',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Yirʼâh (<em>יִרְאָה</em>).</strong> fear (also used as infinitive); morally, reverence. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H3374, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 17, 'f', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: CONVICTION, SERPENT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 18, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-43-25">Isa 43:25</a> · <a href="#vnote-isa-44-22">Isa 44:22</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 18, 'a', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-43-25">Isa 43:25</a> · <a href="#vnote-isa-44-22">Isa 44:22</a> · <a href="#vnote-psa-103-8">Psa 103:8</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 18, 'b', 'God',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 18, 'c', 'mercy',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chêçêd (<em>חֵסֵד</em>).</strong> kindness; by implication (towards God) piety; rarely (by opposition) reproof, or (subject.) beauty. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2617, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 18, 'd', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: GOD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7, 19, '', '',
        'xref-citation', 'Cross-ref',
        'Cite.',
        '<strong>Cross-references.</strong> <a href="#vnote-isa-38-17">Isa 38:17</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        'Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.',
    ),
    (
        7, 20, '', 'mercy',
        'lang-hebrew', 'Hebrew',
        'Hebrew.',
        '<strong>Chêçêd (<em>חֵסֵד</em>).</strong> kindness; by implication (towards God) piety; rarely (by opposition) reproof, or (subject.) beauty. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>',
        "Strong's H2617, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7, 20, 'a', '',
        'topic-nave', 'Topic',
        'Topic.',
        '<strong>Topics.</strong> This verse appears under: ABRAHAM, COVENANT, TRUTH, TRUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>',
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    # (ch, v, suf, anchor, kind, title, label, body_html),
]

NOTES_MIC = NOTES  # backward-compat alias
