"""
Notes for The Book of Micah (mic).

No notes yet — add tuples to the NOTES list below or use:
    python3 scripts/add_note.py --book mic --ch <N> --v <V> --anchor "…" \
        --kind comm --title "…" --body "…"

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    (
        1,
        1,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AHAZ, JERUSALEM, MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        1,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Predictions of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        2,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "a",
        "GOD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "b",
        "Lord",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "c",
        "holy",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Qâdôwsh (<em>קָדוֹשׁ</em>).</strong> sacred (ceremonially or morally); (as noun) God (by eminence), an angel, a saint, a sanctuary.",
        "Strong's H6918, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        3,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "",
        "waters",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Mayim (<em>מַיִם</em>).</strong> water; figuratively, juice; by euphemism, urine, semen.",
        "Strong's H4325, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MOUNTAIN, WAX.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JERUSALEM.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Samaria the capital of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        7,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Samaria the capital of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        8,
        "",
        "naked",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʻârôwm (<em>עָרוֹם</em>).</strong> nude, either partially or totally.",
        "Strong's H6174, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DRAGON, OSTRICHES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        8,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dragon, The, Dragon, The, Owl, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        10,
        "",
        "dust",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʻâphâr (<em>עָפָר</em>).</strong> dust (as powdered or gray); hence, clay, earth, mud.",
        "Strong's H6083, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APHRAH, BETH-EL, GATH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        10,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>BETH-LE-APHRAH</strong> (R.V. Micah 1:10), house of dust. The Authorized Version reads “in the house of Aphrah.” This is probably the name of a town in the Shephelah, or “low country,” between Joppa and Gaza.",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        11,
        "",
        "naked",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʻârôwm (<em>עָרוֹם</em>).</strong> nude, either partially or totally.",
        "Strong's H6174, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        11,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BETH-EZEL, SAPHIR, ZAANAN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        11,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>SAPHIR</strong> beautiful, a town of Judah (Micah 1:11), identified with es-Suafir, 5 miles south-east of Ashdod.",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        11,
        "c",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>ZAANAN</strong> place of flocks, mentioned only in Micah 1:11. It may be identified with Zenan, in the plain country of Judah (Joshua 15:37).",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        12,
        "",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well).",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        12,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MAROTH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        12,
        "c",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>MAROTH</strong> bitterness; i.e., “perfect grief”, a place not far from Jerusalem; mentioned in connection with the invasion of the Assyrian army (Micah 1:12).",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        13,
        "",
        "sin",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chaṭṭâʼâh (<em>חַטָּאָה</em>).</strong> an offence (sometimes habitual sinfulness), and its penalty, occasion, sacrifice, or expiation; also (concretely) an offender.",
        "Strong's H2403, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        13,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHARIOT, LACHISH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        13,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Chariots, Horse, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        15,
        "",
        "glory",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Kâbôwd (<em>כָּבוֹד</em>).</strong> properly, weight, but only figuratively in a good sense, splendor or copiousness.",
        "Strong's H3519, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        15,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ADULLAM, MARESHAH, MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        16,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BALDNESS, EAGLE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        16,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Denunciations against, Head.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        1,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_039.html#ch-b37-c32">Isa 32:7</a> · <a href="index_split_033.html#ch-b30-c36">Psa 36:4</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        1,
        "a",
        "light",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.).",
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: LAND, MICAH, RISING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        1,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beds, Denunciations against.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        2,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHARACTER, LAND, MICAH, MONOPOLY, OPPRESSION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        2,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Character of the Wicked, Covetousness, Covetousness, Hospitality, Injustice.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        3,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        3,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Covetousness, Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        5,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        5,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CORD, MICAH, ROPE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        7,
        "",
        "spirit",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions).",
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "a",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well).",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "b",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        7,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Uprightness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        9,
        "",
        "glory",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Kâbôwd (<em>כָּבוֹד</em>).</strong> properly, weight, but only figuratively in a good sense, splendor or copiousness.",
        "Strong's H3519, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        9,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        9,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Divorce, Hospitality.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Sins, National.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        11,
        "",
        "spirit",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions).",
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BOZRAH, MICAH, SHEEP.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Jews, The, Sheep.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        13,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_040.html#ch-b37-c52">Isa 52:12</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        13,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MICAH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        1,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well).",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "a",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise).",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, EXTORTION, GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prayer, Answers To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        3,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, EXTORTION, GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        3,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prayer, Answers To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        4,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        4,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prayer, Answers To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        5,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "a",
        "Peace",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Shâlôwm (<em>שָׁלוֹם</em>).</strong> safe, i.e. (figuratively) well, happy, friendly; also (abstractly) welfare, i.e. health, prosperity, peace.",
        "Strong's H7965, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        5,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prophesied, Prophesied.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ECLIPSE, SORCERY, SUN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        6,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Doctrines, False.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        7,
        "",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MOURNING, SORCERY, SORCERY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        7,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Doctrines, False.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        8,
        "",
        "spirit",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions).",
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "b",
        "sin",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chaṭṭâʼâh (<em>חַטָּאָה</em>).</strong> an offence (sometimes habitual sinfulness), and its penalty, occasion, sacrifice, or expiation; also (concretely) an offender.",
        "Strong's H2403, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: POWER.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        8,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Boldness, Holy, Injustice, Inspiration of the Holy Spirit, The, Inspiration of the Holy Spirit, The, Power of the Holy Spirit, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        9,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        9,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Injustice, Justice.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        10,
        "",
        "blood",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Dâm (<em>דָּם</em>).</strong> blood (as that which when shed causes death) of man or an animal; by analogy, the juice of the grape; figuratively (especially in the plural) bloodshed (i.e. drops of blood).",
        "Strong's H1818, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        10,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Cities, Issachar, the Tribe Of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        11,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        11,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, COURT, GOVERNMENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        11,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Mills, Prophets, False, Selfishness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JERUSALEM.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: The porch of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        1,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_039.html#ch-b37-c2">Isa 2:1</a> · <a href="index_split_041.html#ch-b38-c3">Jer 3:17</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        4,
        1,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        1,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: REVIVALS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        2,
        "",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        2,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        2,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JERUSALEM, REVIVALS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        3,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_039.html#ch-b37-c2">Isa 2:4</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        4,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JESUS, THE CHRIST, PLOWSHARE, PRUNING, REVIVALS, SPEAR.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        3,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Armies of Israel, The, Performed, Spear, Sword, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        4,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        4,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        4,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: REVIVALS, TOLERATION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        4,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruit of, Vine, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        5,
        "",
        "god",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        5,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        5,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GOD, REVIVALS, TOLERATION.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        6,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        6,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: REVIVALS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        7,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: REVIVALS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: EDAR, JERUSALEM, REVIVALS, SHEPHERD.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        8,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Towers.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        9,
        "",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman.",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        10,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        10,
        "a",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman.",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        10,
        "b",
        "redeem",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Gâʼal (<em>גָּאַל</em>).</strong> to be the next of kin (and as such to buy back a relative's property, marry his widow, etc.).",
        "Strong's H1350, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        10,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Atonement, Under the Law.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        12,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Counsels and Purposes of God, The, The place for.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        13,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        13,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        13,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HORN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        13,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Brass, or Copper, Horns, The place for.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        1,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: COURT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        1,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Prophecies Respecting Christ, Sieges, Titles and Names of Christ.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        2,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_051.html#ch-b60-c2">Mat 2:6</a> · <a href="index_split_054.html#ch-b63-c7">Jhn 7:42</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        5,
        2,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_051.html#ch-b60-c2">Mat 2:6</a> · <a href="index_split_054.html#ch-b63-c7">Jhn 7:42</a> · <a href="index_split_039.html#ch-b37-c9">Isa 9:6</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        5,
        2,
        "b",
        "",
        "text-witness",
        "Witness",
        "MS.",
        "<strong>Manuscript witness.</strong> ; seeing that the same identification is repeated in four other places, including the much more strongly Messianic passage in Micah 5. 2, the omission in Joshua alone would be perfectly useless for party purposes, and may much more fairly be explained as an accident. It is needless to add that the greater prophecies of the Messiah,",
        "Frederic G. Kenyon, *Our Bible and the Ancient Manuscripts* (Eyre & Spottiswoode, London, 1895). Public domain.",
    ),
    (
        5,
        2,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BETHLEHEM, BETHLEHEM, EPHRATAH, ETERNITY, JESUS, THE CHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        2,
        "d",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>THOUSANDS</strong> (Micah 5:2), another name for “families” or “clans” (see Numbers 1:16; 10:4; Joshua 22:14, 21). Several “thousands” or “families” made up a “tribe.”",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        5,
        2,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Christ is God, Christ, the King, Prophecies Respecting Christ, Providence of God, The, Titles and Names of Christ.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        4,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        4,
        "a",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        4,
        "b",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        4,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JESUS, THE CHRIST, JESUS, THE CHRIST, JESUS, THE CHRIST, JESUS, THE CHRIST.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        4,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Christ, the Shepherd.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        5,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        5,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        5,
        "b",
        "peace",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Shâlôwm (<em>שָׁלוֹם</em>).</strong> safe, i.e. (figuratively) well, happy, friendly; also (abstractly) welfare, i.e. health, prosperity, peace.",
        "Strong's H7965, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        5,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SEVEN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        5,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ox, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        6,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        6,
        "a",
        "waste",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Tôhûw (<em>תֹּהוּ</em>).</strong> a desolation (of surface), i.e. desert; figuratively, a worthless thing; adverbially, in vain.",
        "Strong's H8414, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        6,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ASSYRIA, SEVEN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        6,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Assyria.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        7,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        7,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RIGHTEOUS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        7,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Grass, Saints, Compared To.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: LION, RIGHTEOUS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        8,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beard, The, Forests, Lion, The, Saints, Compared To, Sheep.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        10,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Chariots.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        11,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SORCERY.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GROVES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Groves.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        15,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Have.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        1,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_041.html#ch-b38-c22">Jer 22:29</a> · <a href="index_split_009.html#vnote-deu-32-1">Deu 32:1</a> · <a href="index_split_051.html#ch-b53-c1">Mic 1:2</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        6,
        1,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_041.html#ch-b38-c22">Jer 22:29</a> · <a href="index_split_009.html#vnote-deu-32-1">Deu 32:1</a> · <a href="index_split_051.html#ch-b53-c1">Mic 1:2</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        6,
        1,
        "b",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        2,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        2,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        2,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: REASONING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        2,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ingratitude to God.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Ingratitude to God.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        4,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MIRIAM, WOMEN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        4,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Righteousness of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        5,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        5,
        "a",
        "righteousness",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Tsedeq (<em>צֶדֶק</em>).</strong> the right (natural, moral or legal); also (abstractly) equity or (figuratively) prosperity.",
        "Strong's H6664, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        5,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BALAAM, BALAK, MOABITES, SHITTIM.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        5,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Righteousness of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        6,
        "",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        6,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        6,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CALF.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        6,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Busy-Bodies.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        7,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        7,
        "a",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental).",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        7,
        "b",
        "sin",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chaṭṭâʼâh (<em>חַטָּאָה</em>).</strong> an offence (sometimes habitual sinfulness), and its penalty, occasion, sacrifice, or expiation; also (concretely) an offender.",
        "Strong's H2403, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        7,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: First Born, The, Sin.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        8,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_008.html#vnote-deu-10-12">Deu 10:12</a> · <a href="index_split_036.html#ch-b32-c21">Pro 21:3</a> · <a href="index_split_058.html#ch-b71-c3">Col 3:12</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        6,
        8,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_008.html#vnote-deu-10-12">Deu 10:12</a> · <a href="index_split_036.html#ch-b32-c21">Pro 21:3</a> · <a href="index_split_058.html#ch-b71-c3">Col 3:12</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        6,
        8,
        "b",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well).",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        8,
        "c",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        8,
        "d",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        8,
        "e",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        8,
        "f",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise).",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        8,
        "g",
        "mercy",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chêçêd (<em>חֵסֵד</em>).</strong> kindness; by implication (towards God) piety; rarely (by opposition) reproof, or (subject.) beauty.",
        "Strong's H2617, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        8,
        "h",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Conduct, Christian, Humility, Justice.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        9,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        9,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        9,
        "b",
        "wisdom",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chokmâh (<em>חׇכְמָה</em>).</strong> wisdom (in a good sense).",
        "Strong's H2451, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        9,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflictions, Afflictions Made Beneficial, Judgments.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MEASURE, WEIGHTS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Measures.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BALANCES, CHARACTER, MEASURE, WEIGHTS.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Character of the Wicked, Weights.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MEASURE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Riches.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        15,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Anointing, Oil, Olive Tree, The, Purifications, Was made of.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        16,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AHAB, OMRI.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        1,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental).",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        1,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GLEANING, SUMMER.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        1,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Goat, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        2,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        2,
        "a",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well).",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        2,
        "b",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        2,
        "c",
        "blood",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Dâm (<em>דָּם</em>).</strong> blood (as that which when shed causes death) of man or an animal; by analogy, the juice of the grape; figuratively (especially in the plural) bloodshed (i.e. drops of blood).",
        "Strong's H1818, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        2,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Uprightness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        3,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHARACTER, CHARACTER, COURT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        3,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Character of the Wicked, Groves.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: HEDGE, THORN.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        4,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>BRIER</strong> This word occurs frequently, and is the translation of several different terms. (1.) Micah 7:4, it denotes a species of thorn shrub used for hedges. In Proverbs 15:19 the word is rendered “thorn” (Hebrews hedek, “stinging”), supposed by some to be what is called the “apple of Sodom” (q.v.). (2.) Ezekiel 28:24, sallon’, properly a “prickle,” such as is found on the shoots of the palm tree. (3.) Isaiah 55:13, probably simply a thorny bush. Some, following the Vulgate Version, regard it as the “nettle.” (4.) Isaiah 5:6; 7:23-25, etc., frequently used to denote thorny shrubs in general. In 10:17; 27:4, it means troublesome men. (5.) In Hebrews 6:8 the Greek word (tribolos) so rendered means “three-pronged,” and denotes the land caltrop, a low throny shrub resembling in its spikes the military “crow-foot.” Comp. Matthew 7:16, “thistle.”",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        7,
        4,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Day, Hedges, Uprightness.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        5,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_041.html#ch-b38-c9">Jer 9:4</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        5,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_041.html#ch-b38-c9">Jer 9:4</a> · <a href="index_split_034.html#ch-b30-c118">Psa 118:8</a> · <a href="index_split_051.html#ch-b60-c10">Mat 10:16</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        6,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_051.html#ch-b60-c10">Mat 10:35</a> · <a href="index_split_053.html#ch-b62-c12">Luk 12:53</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        6,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.).",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        6,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAUGHTER-IN-LAW, WAR.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        6,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Warfare of Saints.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        7,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_043.html#ch-b39-c3">Lam 3:25</a> · <a href="index_split_033.html#ch-b30-c37">Psa 37:7</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        7,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_043.html#ch-b39-c3">Lam 3:25</a> · <a href="index_split_033.html#ch-b30-c37">Psa 37:7</a> · <a href="index_split_059.html#ch-b82-c5">1Jn 5:14</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        7,
        "b",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        7,
        "c",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        7,
        "d",
        "salvation",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Yᵉshûwʻâh (<em>יְשׁוּעָה</em>).</strong> something saved, i.e. (abstractly) deliverance; hence, aid, victory, prosperity.",
        "Strong's H3444, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        7,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES, WAITING, WAITING.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        7,
        "f",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflictions, Vows, Vows.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        8,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_054.html#ch-b63-c8">Jhn 8:12</a> · <a href="index_split_033.html#ch-b30-c27">Psa 27:1</a> · <a href="index_split_039.html#ch-b37-c9">Isa 9:2</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        8,
        "a",
        "darkness",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chôshek (<em>חֹשֶׁךְ</em>).</strong> the dark; hence (literally) darkness; figuratively, misery, destruction, death, ignorance, sorrow, wickedness.",
        "Strong's H2822, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        8,
        "b",
        "light",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.).",
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        8,
        "c",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        8,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES, WAR.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        8,
        "e",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflictions, Privileges of Saints, Warfare of Saints.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        9,
        "",
        "light",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.).",
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        9,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        9,
        "b",
        "righteousness",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Tsedeq (<em>צֶדֶק</em>).</strong> the right (natural, moral or legal); also (abstractly) equity or (figuratively) prosperity.",
        "Strong's H6664, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        9,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        9,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Afflicted Saints, Afflictions, Anger of God, The, Resignation, Righteousness of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        10,
        "",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        10,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FENCE.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Anger of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        12,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: As a power, was.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        13,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BASHAN, CARMEL.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Forests.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        15,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land).",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "a",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "b",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only).",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "c",
        "dust",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʻâphâr (<em>עָפָר</em>).</strong> dust (as powdered or gray); hence, clay, earth, mud.",
        "Strong's H6083, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "d",
        "serpent",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nâchâsh (<em>נָחָשׁ</em>).</strong> a snake (from its hiss).",
        "Strong's H5175, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "e",
        "fear",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Yirʼâh (<em>יִרְאָה</em>).</strong> fear (also used as infinitive); morally, reverence.",
        "Strong's H3374, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        17,
        "f",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SERPENT.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        17,
        "g",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Insects, Serpents.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        18,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_040.html#ch-b37-c43">Isa 43:25</a> · <a href="index_split_040.html#ch-b37-c44">Isa 44:22</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        18,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_040.html#ch-b37-c43">Isa 43:25</a> · <a href="index_split_040.html#ch-b37-c44">Isa 44:22</a> · <a href="index_split_034.html#ch-b30-c103">Psa 103:8</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        18,
        "b",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative.",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        18,
        "c",
        "mercy",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chêçêd (<em>חֵסֵד</em>).</strong> kindness; by implication (towards God) piety; rarely (by opposition) reproof, or (subject.) beauty.",
        "Strong's H2617, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        18,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Consolation Under, Mercy of God, The, Pardon, Sin, Unity of God.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        19,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_040.html#ch-b37-c38">Isa 38:17</a>.',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        7,
        19,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Affliction, Consolation Under, Pardon, Pardon.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        20,
        "",
        "mercy",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Chêçêd (<em>חֵסֵד</em>).</strong> kindness; by implication (towards God) piety; rarely (by opposition) reproof, or (subject.) beauty.",
        "Strong's H2617, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        20,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ABRAHAM, TRUTH.",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        20,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Faithfulness of God, The, Mercy of God, The, Truth of God, The.",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    # (ch, v, suf, anchor, kind, title, label, body_html),
]

NOTES_MIC = NOTES  # backward-compat alias
