"""
Notes for The Book of Ruth (rut).

Migrated to content/notes/ in the Phase-1 refactor (2026-05-05). This is the
canonical home; legacy locations remain in place but should be considered frozen.

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    # ---- ch 1 ----
    (
        1,
        1,
        "",
        "In the days when the judges judged",
        "comm",
        "Note",
        "Note",
        "<strong>Ruth as counterweight to Judges.</strong> The book opens by anchoring itself to the same era as Judges — but its register is opposite: domestic, pastoral, quiet, ending in a marriage and a baby rather than civil war and a dismembered body. In the Jewish canon Ruth is one of the Five Megillot among the Writings (read on Shavuot, the harvest festival); in the Christian canon Ruth follows Judges, completing the Judges-era picture. The Megillot placement emphasizes Ruth’s liturgical and harvest themes; the Christian placement emphasizes the chronology and the bridge to David.",
        "User original",
    ),
    (
        1,
        1,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_001.html#vnote-gen-12-10">Gen 12:10</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        1,
        1,
        "b",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "c",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        1,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BETHLEHEM, BETHLEHEM, CANAAN, READINGS, SELECT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        2,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILION, ELIMELECH, MAHLON, READINGS, SELECT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        2,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>CHILION</strong> the pining one, the younger son of Elimelech and Naomi, and husband of Orpah, Ruth’s sister (Ruth 1:2; 4:9). <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        2,
        "c",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>ELIMELECH G</strong> od his king, a man of the tribe of Judah, of the family of the Hezronites, and kinsman of Boaz, who dwelt in Bethlehem in the days of the judges. In consequence of a great dearth he, with his wife Naomi and his two sons, went to dwell in the land of Moab. There he and his sons died (Ruth 1:2,3; 2:1,3; 4:3,9). Naomi afterwards returned to Palestine with her daughter Ruth. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        2,
        "d",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>EPHRATHITE</strong> a citizen of Ephratah, the old name of Bethlehem (Ruth 1:2; 1 Samuel 17:12), or Bethlehem-Judah. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        2,
        "e",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>MAHLON</strong> sickly, the elder of Elimelech the Bethlehemite’s two sons by Naomi. He married Ruth and died childless (Ruth 1:2, 5; 4:9, 10), in the land of Moab. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        3,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BEREAVEMENT, ELIMELECH, READINGS, SELECT, WIDOW. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILION, MOABITES, ORPAH, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        4,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>ORPAH</strong> forelock or fawn, a Moabitess, the wife of Chilion (Ruth 1:4; 4:10). On the death of her husband she accompanied Naomi, her mother-in-law, part of the way to Bethlehem, and then returned to Moab. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        5,
        "",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        5,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BEREAVEMENT, CHILION, MAHLON, READINGS, SELECT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        6,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        7,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        8,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        8,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BENEDICTIONS, PARENTS, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        9,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BENEDICTIONS, PARENTS, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAUGHTER-IN-LAW, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAUGHTER-IN-LAW, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        13,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        13,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAUGHTER-IN-LAW, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONSTANCY, DAUGHTER-IN-LAW, KISS, MOTHER-IN-LAW, ORPAH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        15,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILDREN, DAUGHTER-IN-LAW, MOTHER-IN-LAW, READINGS, SELECT, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        16,
        "",
        "Your people will be my people, and your God my God",
        "comm",
        "Note",
        "Note",
        "<strong>Ruth’s declaration.</strong> One of the most-quoted lines in scripture, often used in Christian wedding liturgies though originally addressed by a daughter-in-law to a mother-in-law. The Moabite woman’s commitment is total: people, place, God, even burial ground. In rabbinic tradition Ruth’s declaration is taken as the paradigmatic conversion formula — an outsider who joins Israel by binding her fate to a particular family and to YHWH. Hesed (covenant loyalty) is the book’s central virtue, and Ruth embodies it: the foreigner outdoes the natives in covenantal fidelity.",
        "User original",
    ),
    (
        1,
        16,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_012.html#vnote-2sa-15-21">2Sa 15:21</a> · <a href="index_split_010.html#vnote-rut-2-11">Rut 2:11</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        1,
        16,
        "b",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_012.html#vnote-2sa-15-21">2Sa 15:21</a> · <a href="index_split_010.html#vnote-rut-2-11">Rut 2:11</a> · <a href="index_split_015.html#ch-b11-c2">2Ki 2:2</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        1,
        16,
        "c",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        16,
        "d",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILDREN, CHILDREN, CONVERTS, DAUGHTER-IN-LAW, DECISION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        17,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        17,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILDREN, CHILDREN, DAUGHTER-IN-LAW, FRIENDSHIP, IMPRECATION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        18,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILDREN, DAUGHTER-IN-LAW, READINGS, SELECT, RUTH, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        19,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BETHLEHEM, READINGS, SELECT, RUTH, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        20,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES, BEREAVEMENT, READINGS, SELECT, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        20,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>MARA</strong> bitter; sad, a symbolical name which Naomi gave to herself because of her misfortunes (Ruth 1:20). <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        1,
        21,
        "",
        "empty",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Bôhûw (<em>בֹּהוּ</em>).</strong> a vacuity, i.e. (superficially) an undistinguishable ruin. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H922, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        21,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        21,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AFFLICTIONS AND ADVERSITIES, BEREAVEMENT, READINGS, SELECT, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        22,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: READINGS, SELECT, RUTH, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        1,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        1,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ELIMELECH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        2,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ELIMELECH, GLEANING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        3,
        "a",
        "light",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼôwr (<em>אוֹר</em>).</strong> illumination or (concrete) luminary (in every sense, including lightning, happiness, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H216, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        3,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GLEANING, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        4,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_035.html#ch-b30-c129">Psa 129:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        4,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        4,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BETHLEHEM, BETHLEHEM, EMPLOYEE, RUTH, SALUTATIONS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        7,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        9,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        10,
        "",
        "ground",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădâmâh (<em>אֲדָמָה</em>).</strong> soil (from its general redness). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H127, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        11,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    # ---- ch 2 ----
    (
        2,
        12,
        "",
        "under whose wings you have come to take refuge",
        "word",
        "Hebrew",
        "Hebrew",
        "<strong>Kanaf (<em>כָּנָף</em>) — “wing, corner of a garment.”</strong> The same word is used metaphorically here (refuge under God’s wings) and literally in 3:9 when Ruth asks Boaz to spread his <em>kanaf</em> over her — the marriage-protection idiom. The doubled use is intentional: Boaz invokes God’s sheltering wing in chapter 2; Ruth in chapter 3 invites Boaz to embody it. The book’s theological elegance is built on small verbal hooks like this.",
        "User original",
    ),
    (
        2,
        12,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c36">Psa 36:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        12,
        "b",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c36">Psa 36:7</a> · <a href="index_split_034.html#ch-b30-c91">Psa 91:4</a> · <a href="index_split_033.html#ch-b30-c63">Psa 63:7</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        2,
        12,
        "c",
        "God",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼĕlôhîym (<em>אֱלֹהִים</em>).</strong> gods in the ordinary sense; but specifically used (in the plural thus, especially with the article) of the supreme God; occasionally applied by way of deference to magistrates; and sometimes as a superlative. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H430, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "d",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "e",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        13,
        "",
        "lord",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CORN, FOOD, FOOD, POOR, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        15,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: POOR, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        16,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: POOR, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        17,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        19,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        19,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: THANKFULNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        20,
        "a",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        20,
        "b",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        20,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JOY, THANKFULNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        22,
        "",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        23,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: POOR. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        1,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_010.html#vnote-rut-1-9">Rut 1:9</a> · <a href="index_split_059.html#ch-b74-c5">1Ti 5:8</a> · <a href="index_split_035.html#ch-b30-c128">Psa 128:2</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        1,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH, THRESHING, WINNOWING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        2,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>WINNOW C</strong> orn was winnowed, (1.) By being thrown up by a shovel against the wind. As a rule this was done in the evening or during the night, when the west wind from the sea was blowing, which was a moderate breeze and fitted for the purpose. The north wind was too strong, and the east wind came in gusts. (2.) By the use of a fan or van, by which the chaff was blown away (Ruth 3:2; Isaiah 30:24; Jeremiah 4:11, 12; Matthew 3:12). <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        3,
        3,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANOINTING, RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        7,
        "",
        "heart",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Lêb (<em>לֵב</em>).</strong> the heart; also used (figuratively) very widely for the feelings, the will and even the intellect; likewise for the centre of anything. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3820, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        8,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "a",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    # ---- ch 3 ----
    (
        3,
        9,
        "",
        "spread the corner of your garment over your servant",
        "comm",
        "Note",
        "Note",
        "<strong>The threshing-floor scene.</strong> The chapter is masterfully ambiguous. Naomi’s instructions (uncover his feet — possibly a euphemism — and lie down) and Ruth’s execution of them have invited centuries of debate about exactly what passes between Ruth and Boaz that night. The text is reticent on purpose: what matters is that Ruth, again, takes the initiative; Boaz, again, blesses her for <em>hesed</em>; and the narrative resolves toward marriage rather than scandal. The scene is one of the few in the Hebrew Bible where a woman engineers her own legal status with full agency, and the narrator reports it approvingly.",
        "User original",
    ),
    (
        3,
        9,
        "a",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="#vnote-ezk-16-8">Ezk 16:8</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        9,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, COURTSHIP, RUTH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        10,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, COURTSHIP, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        11,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_036.html#ch-b32-c31">Pro 31:29</a> · <a href="index_split_036.html#ch-b32-c31">Pro 31:10</a> · <a href="index_split_036.html#ch-b32-c12">Pro 12:4</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        11,
        "a",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        11,
        "b",
        "fear",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Yirʼâh (<em>יִרְאָה</em>).</strong> fear (also used as infinitive); morally, reverence. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3374, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        11,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, COURTSHIP, THRESHING, WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        12,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, COURTSHIP, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        13,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        13,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHASTITY, CONTINENCE, COURTSHIP, OATH, THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        14,
        "",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        14,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: THRESHING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        15,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        15,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>VEIL</strong> , VAIL (1.) Hebrews mitpahath (Ruth 3:15; marg., “sheet” or “apron;” R.V., “mantle”). In Isaiah 3:22 this word is plural, rendered “wimples;” R.V., “shawls” i.e., wraps. (2.) Massekah (Isaiah 25:7; in Isaiah 28:20 rendered “covering”). The word denotes something spread out and covering or concealing something else (comp. 2 Corinthians 3:13-15). (3.) Masveh (Exodus 34:33, 35), the veil on the face of Moses. This verse should be read, “And when Moses had done speaking with… <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        3,
        16,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        17,
        "",
        "empty",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Bôhûw (<em>בֹּהוּ</em>).</strong> a vacuity, i.e. (superficially) an undistinguishable ruin. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H922, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        18,
        "",
        "",
        "xref-citation",
        "Cross-ref",
        "Cite.",
        '<strong>Cross-references.</strong> <a href="index_split_033.html#ch-b30-c37">Psa 37:3</a>. <em>[Reviewer: select 1–3 most relevant; rewrite as a thematic note rather than a list before promoting.]</em>',
        "Treasury of Scripture Knowledge (1830s). PD. Digital edition by openbible.info, CC-BY 4.0.",
    ),
    (
        3,
        18,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        1,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONTRACTS, COURT, GATES, MARRIAGE, WITNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        1,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>BOAZ</strong> alacrity. (1.) The husband of Ruth, a wealthy Bethlehemite. By the “levirate law” the duty devolved on him of marrying Ruth the Moabitess (Ruth 4:1-13). He was a kinsman of Mahlon, her first husband. (2.) The name given (for what reason is unknown) to one of the two (the other was called Jachin) brazen pillars which Solomon erected in the court of the temple (1 Kings 7:21; 2 Chronicles 3:17). These pillars were broken up and carried to Babylon by Nebuchadnezzar. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        4,
        2,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONTRACTS, JURY, MARRIAGE, WITNESS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        3,
        "",
        "land",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: COMMERCE, DAUGHTER, DOWRY, ELIMELECH, LAND. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        4,
        "",
        "redeem",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Gâʼal (<em>גָּאַל</em>).</strong> to be the next of kin (and as such to buy back a relative's property, marry his widow, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H1350, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOWRY, LAND, LAND, MARRIAGE, REDEMPTION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DOWRY, LAND, LAND, MARRIAGE, MARRIAGE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        6,
        "",
        "redeem",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Gâʼal (<em>גָּאַל</em>).</strong> to be the next of kin (and as such to buy back a relative's property, marry his widow, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H1350, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        6,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONTRACTS, DOWRY, LAND, LAND, MARRIAGE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    # ---- ch 4 ----
    (
        4,
        7,
        "",
        "a man took off his sandal",
        "comm",
        "Note",
        "Note",
        "<strong>The sandal transaction.</strong> The narrator pauses to explain a custom no longer current in his own day — “Now this was the custom in former time in Israel” — preserving an archaic legal procedure for the reader. The same custom appears in the leviratic obligation of Deut 25:5–10 in a more shaming form (the rejected widow removes the sandal of the brother who refuses to marry her, and spits in his face). Here the sandal is a quiet contractual seal, not a shaming gesture. The detail is one of the book’s many quiet markers of antiquity, suggesting a final composition some distance from the era it depicts.",
        "User original",
    ),
    (
        4,
        7,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        7,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONTRACTS, DOWRY, LAND, LAND, MARRIAGE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CONTRACTS, DOWRY, LAND, LAND, MARRIAGE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        9,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILION, DOWRY, ELIMELECH, LAND, LAND. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: LAND, MAHLON, MARRIAGE, MARRIAGE, REDEMPTION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        11,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        11,
        "a",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        11,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BENEDICTIONS, EPHRATAH, LAND, LAND, LEAH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        12,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        12,
        "a",
        "woman",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼishshâh (<em>אִשָּׁה</em>).</strong> a woman. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H802, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        12,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BENEDICTIONS, RUTH, TAMAR. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        13,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        13,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILDREN, RUTH, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        14,
        "",
        "LORD",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼădônây (<em>אֲדֹנָי</em>).</strong> the Lord (used as a proper name of God only). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H136, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        14,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JOY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        15,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAUGHTER-IN-LAW, SEVEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        16,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHILDREN, NURSE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        17,
        "",
        "He is the father of Jesse, the father of David",
        "comm",
        "Note",
        "Note",
        "<strong>The David connection.</strong> The book’s most surprising move comes in its final five verses. The whole pastoral domestic narrative is revealed to have been about David’s great-grandmother — a Moabite woman whose people, by the strict reading of Deut 23:3, were excluded from the assembly of Yahweh. Yet she stands at the head of the Davidic line, and so (Matt 1:5) of Jesus’ genealogy. The book is making a quiet but radical theological argument: covenantal belonging is determined by <em>hesed</em>, not ancestry. The book’s placement at the threshold of the monarchy reframes everything that follows.",
        "User original",
    ),
    # ---- expansion (May 2026) ----
    (
        2,
        3,
        "",
        "she happened to come to the portion of the field belonging to Boaz",
        "word",
        "Hebrew",
        "Hebrew",
        "<strong>Vayiqer miqreha (<em>וַיִּקֶר</em> <em>מִקְרֶהָ</em>).</strong> A doubled root: literally “her chance chanced upon her.” The narrator’s tongue is in his cheek — what looks like coincidence in the field is, by the book’s end, the providential arc that will produce King David. The Hebrew flagrantly highlights the chance-language at exactly the moment the reader is meant to see through it. Rabbinic and Christian commentary both seize on this verse as a programmatic statement of hidden providence.",
        "User original",
    ),
    (
        2,
        20,
        "",
        "one of our near kinsmen",
        "word",
        "Hebrew",
        "Hebrew",
        "<strong>Go’el (<em>גֹּאֵל</em>) — “redeemer, near kinsman.”</strong> The technical legal term first introduced here. The <em>go’el</em> is the male relative responsible for redeeming alienated property (Lev 25:25), avenging shed blood (Num 35:19), and — by extension — perpetuating a brother’s line (Deut 25:5–10). Naomi’s announcement that Boaz is <em>go’el</em> reframes the entire next two chapters as a legal drama. The same word becomes the dominant metaphor for God in Isaiah 40–55 — Yahweh as the kinsman-redeemer of exiled Israel.",
        "User original",
    ),
    (
        3,
        12,
        "",
        "there is a  kinsman nearer than I",
        "comm",
        "Note",
        "Note",
        "<strong>The nearer kinsman.</strong> A narrative complication that exposes the legal stakes — Boaz cannot simply act on his own desire; the law has an order of precedence, and a closer relative has first refusal. The chapter ends in suspense; chapter 4 opens with the resolution. The careful legal procedure that follows is part of the book’s argument: hesed and law are not opposed, they reinforce each other. Boaz embodies covenantal kindness within the discipline of legal form.",
        "User original",
    ),
    (
        4,
        1,
        "",
        "the gate",
        "comm",
        "Note",
        "Note",
        "<strong>The city gate as courtroom.</strong> The gate of an Israelite town was the standard place for legal transactions — its bench seats, public visibility, and ten-elder quorum (4:2) made it the equivalent of a court of record. Modern excavations at Iron Age sites (Beersheba, Dan, Gezer) have uncovered the multi-chambered gate complexes assumed by texts like this. Amos 5:15 (“establish justice in the gate”) takes the institution as so basic that it can stand for the entire judicial order.",
        "User original",
    ),
    (
        1,
        16,
        "m",
        "",
        "comm-ethiopian",
        "Note",
        "Note",
        '<strong>Ruth’s vow.</strong> One of the great speeches in scripture. A Moabite woman binds herself to her widowed Israelite mother-in-law in language that echoes covenant formulas: "your people will be my people; your God, my God." The verse has become foundational in conversion liturgies in many Jewish traditions — Ruth as the model proselyte. The Ethiopian Tewahedo and Eastern traditions read her as a paradigm of faithfulness across ethnic boundaries.',
        "User original",
    ),
    (
        2,
        12,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>Wings of refuge.</strong> Boaz blesses Ruth using the image of God’s wings (<em>k’nafav</em>) — the metaphor that runs from Pss 17:8, 36:7, 57:1, 91:4 to Jesus’s lament over Jerusalem ("how often I would have gathered your children, as a hen gathers her chicks under her wings," Matt 23:37). The cherubim’s wings cover the ark; God’s presence is wing-shaped.""",
        "User original",
    ),
    (
        4,
        13,
        "m",
        "",
        "comm",
        "Note",
        "Note",
        """<strong>The line of David.</strong> The closing genealogy (4:18–22) ties Ruth into the Davidic line and, through Matthew 1:5, into the line of Christ. Ruth is one of four women named in Matthew’s genealogy (with Tamar, Rahab, Bathsheba) — each carries a story of irregular sexuality or ethnic outsider status that yet becomes part of Israel’s salvation history. The book makes a quiet but radical theological claim: a Moabite great-grandmother sits in the Davidic line, and through her in the messianic line.""",
        "User original",
    ),
    (
        4,
        17,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JESSE, OBED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        17,
        "b",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>JESSE</strong> firm, or a gift, a son of Obed, the son of Boaz and Ruth (Ruth 4:17, 22; Matthew 1:5, 6; Luke 3:32). He was the father of eight sons, the youngest of whom was David (1 Samuel 17:12). The phrase “stem of Jesse” is used for the family of David (Isaiah 11:1), and “root of Jesse” for the Messiah (Isaiah 11:10; Revelation 5:5). Jesse was a man apparently of wealth and position at Bethlehem (1 Samuel 17:17, 18, 20; Psalm 78:71). The last reference to him is of David’s procuring… <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        4,
        18,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AMMINADAB, DAVID, GENEALOGY, OBED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        19,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AMMINADAB, DAVID, GENEALOGY, OBED, RAM. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        19,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>RAM</strong> exalted. (1.) The son of Hezron, and one of the ancestors of the royal line (Ruth 4:19). The margin of 1 Chronicles 2:9, also Matthew 1:3, 4 and Luke 3:33, have “Aram.” (2.) One of the sons of Jerahmeel (1 Chronicles 2:25, 27). (3.) A person mentioned in Job 32:2 as founder of a clan to which Elihu belonged. The same as Aram of Genesis 22:21. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        4,
        20,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AMMINADAB, DAVID, GENEALOGY, OBED, SALMA. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        20,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>SALMON</strong> garment, the son of Nashon (Ruth 4:20; Matthew 1:4, 5), possibly the same as Salma in 1 Chronicles 2:51. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        4,
        21,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAVID, GENEALOGY, OBED, RUTH, SALMA. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        21,
        "a",
        "",
        "dict-easton",
        "Dictionary",
        "Easton.",
        "<strong>Dictionary (Easton's).</strong> <strong>OBED</strong> serving; worshipping. (1.) A son of Boaz and Ruth (Ruth 4:21, 22), and the grandfather of David (Matthew 1:5). (2.) 1 Chronicles 2:34-38. (3.) 1 Chronicles 26:7. (4.) 2 Chronicles 23:1. <em>[Reviewer: condense Easton's entry as needed.]</em>",
        "Easton's Illustrated Bible Dictionary, M. G. Easton (1897). Public domain.",
    ),
    (
        4,
        22,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DAVID, GENEALOGY, OBED, RUTH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
]

NOTES_RUT = NOTES  # backward-compat alias
