"""
Notes for The Song of Songs, or Song of Solomon (sng).

No notes yet — add tuples to the NOTES list below or use:
    python3 scripts/add_note.py --book sng --ch <N> --v <V> --anchor "…" \
        --kind comm --title "…" --body "…"

Format (each tuple): (chapter, verse, suffix, anchor, kind, title, label, body_html [, attribution])
The 9th field (attribution) is optional during the v28a-* migration; identifies
the source / provenance of the note (e.g. "User original", "Strong's H7779 (PD)",
"Paraphrase summarising Westermann, Genesis 1-11 (1984)"). After migration
completes, validate_taxonomy.py will require it on every note.
See content/kinds.yaml for legal `kind` values; content/books.yaml for id_prefix.
"""

NOTES = [
    (
        1,
        2,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        2,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Was made of. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        3,
        "",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "a",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        3,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ANOINTING, OINTMENT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        3,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Preciousness of Christ, Woman. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        4,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Love to Christ, Uprightness, Was made of. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: KEDAR, TAPESTRY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        5,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Tents, Woman. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WOMEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        6,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Sun, The, Vineyards, Woman, Woman. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        7,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SHEPHERD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        7,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Love to Christ, Sheep. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        8,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Goat, The, Shepherds, Tents, Woman. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        9,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        9,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Chariots, Horse, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GOLD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SILVER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SPIKENARD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CAMPHIRE, CYPRESS, EN-GEDI, GRAPE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        1,
        15,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        1,
        15,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dove, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        1,
        17,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FIR TREE, HOUSE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        1,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JESUS, THE CHRIST, ROSE, SHARON. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        1,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Flowers, Flowers, Usury or Interest. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        2,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        2,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RIGHTEOUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        2,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Saints, Compared To. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        3,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APPLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        3,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Delighting In God, Fruits, Preciousness of Christ, Trees, Trees. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        4,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Love of Christ, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        5,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        5,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APPLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        5,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beard, The, Love to Christ, Was made of. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        6,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Groves. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        7,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        7,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Hart, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        8,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Mountains. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        9,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Hart, The, Roe, The, Walls. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        10,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SPRING, WINTER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fig Tree, The, Winter. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        12,
        "",
        "earth",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼerets (<em>אֶרֶץ</em>).</strong> the earth (at large, or partitively a land). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H776, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        12,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BIRDS, SPRING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        12,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Birds, Birds, Dove, The, Flowers. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        13,
        "",
        "good",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Ṭôwb (<em>טוֹב</em>).</strong> good (as an adjective) in the widest sense; used likewise as a noun, both in the masculine and the feminine, the singular and the plural (good, a good or good thing, a good man or woman; the good, goods or good things, good men or women), also as an adverb (well). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H2896, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "a",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        2,
        13,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SPRING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        13,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fig Tree, The, Vine, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dove, The, Dove, The, Dove, The, Dove, The, Excellency and Glory of the Church, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        15,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: FOX, FOX, SIN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        15,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fox, The, Fox, The, Vine, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        16,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Union With Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        2,
        17,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BETHER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        2,
        17,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Day, Hart, The, Roe, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        1,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        1,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beds, Night. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        2,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        2,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Cities, Love to Christ, Seeking God. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        3,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        3,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WATCHMAN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        3,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Cities, Were stationed. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        4,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Seeking God. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        5,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: COMMERCE, FRANKINCENSE, MYRRH, PERFUME. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        6,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Carried on by, Deserts. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        7,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        7,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beds. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        8,
        "",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "a",
        "fear",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Yirʼâh (<em>יִרְאָה</em>).</strong> fear (also used as infinitive); morally, reverence. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3374, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        8,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        8,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beds, War. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        9,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BED. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        9,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beds, Cedar, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        10,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Pillars. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        3,
        11,
        "",
        "heart",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Lêb (<em>לֵב</em>).</strong> the heart; also used (figuratively) very widely for the feelings, the will and even the intellect; likewise for the centre of anything. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3820, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        3,
        11,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CROWN, ZION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        3,
        11,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Marriage. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        1,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        1,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GILEAD, GOAT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        1,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Goat, The, Mountains. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        2,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Sheep, Sheep. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Head, Pomegranate Tree, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ARMORY, TOWER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Arms, Military, Shields, Towers, Towers, Towers. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        5,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Roe, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        6,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MYRRH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        6,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Incense, Mountains. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        7,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        7,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: AMANA, BRIDEGROOM, HERMON, LEOPARD, SHENIR. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        8,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Beard, The, Beard, The, Lebanon, Leopard, Lion, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        9,
        "",
        "heart",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Lêb (<em>לֵב</em>).</strong> the heart; also used (figuratively) very widely for the feelings, the will and even the intellect; likewise for the centre of anything. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3820, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        9,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        9,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Love of Christ, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        10,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        10,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM, OINTMENT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        10,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Anointing. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM, HONEY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Cedar, The, Gardens, Honey, Honey, Lebanon. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM, CHURCH, CHURCH, FENCE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fountains and Springs, Gardens, Gardens, Hedges, Seals. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        13,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM, CAMPHIRE, CYPRESS, RIGHTEOUS, SPIKENARD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        13,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Pomegranate Tree, The, Pomegranate Tree, The, Saints, Compared To. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ALOES, BRIDEGROOM, CALAMUS, CINNAMON, MYRRH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Herbs, & C, Herbs, & C, Herbs, & C, Herbs, & C, Herbs, & C. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        15,
        "",
        "waters",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Mayim (<em>מַיִם</em>).</strong> water; figuratively, juice; by euphemism, urine, semen. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H4325, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        15,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM, LEBANON. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        15,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Gardens, Lebanon, Wells, Wells. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        4,
        16,
        "",
        "wind",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Rûwach (<em>רוּחַ</em>).</strong> wind; by resemblance breath, i.e. a sensible (or even violent) exhalation; figuratively, life, anger, unsubstantiality; by extension, a region of the sky; by resemblance spirit, but only of a rational being (including its expression and functions). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H7307, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        4,
        16,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BRIDEGROOM, SYMBOLS AND SIMILITUDES. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        4,
        16,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruits, Gardens, Wind, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        1,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, FOOD, MILK, MYRRH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        1,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Diet of the Jews, The, Gardens, Gardens, Honey, Love of Christ, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        2,
        "",
        "heart",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Lêb (<em>לֵב</em>).</strong> the heart; also used (figuratively) very widely for the feelings, the will and even the intellect; likewise for the centre of anything. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3820, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        2,
        "a",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        2,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, CHURCH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        2,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dove, The, Night, Titles and Names of the Church. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        3,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: ABLUTION. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        3,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Feet, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BOWELS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: LOCK. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        5,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Hospitality. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        6,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        7,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: WATCHMAN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        7,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Cities, Usury or Interest, Walls, Were stationed. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        8,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        9,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Love to Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JESUS, THE CHRIST. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Excellency and Glory of Christ, The, Love to Christ, Preciousness of Christ, Preciousness of Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RAVEN. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Groves, Love to Christ, Preciousness of Christ, Purifications, Purifications. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        12,
        "",
        "waters",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Mayim (<em>מַיִם</em>).</strong> water; figuratively, juice; by euphemism, urine, semen. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H4325, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        5,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Dove, The, Dove, The, Love to Christ, Precious Stones, Preciousness of Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        13,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: LILY, MYRRH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        13,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Flowers, Flowers, Love to Christ, Preciousness of Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BERYL, GOLD, IVORY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Gold, Love to Christ, Preciousness of Christ, Rings, Rings. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        15,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MARBLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        5,
        15,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Cedar, The, Love to Christ, Pillars, Preciousness of Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        5,
        16,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Christ, Character Of, Love to Christ, Preciousness of Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        2,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Flowers, Gardens, Gardens. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Flowers. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        4,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        4,
        "a",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JERUSALEM, STANDARD, TIRZAH. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        4,
        "b",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Armies, Armies, Issachar, the Tribe Of. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GILEAD, GOAT. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        7,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Pomegranate Tree, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        10,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CHURCH, MOON, STANDARD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        10,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Armies, Moon, The, Moon, The, Morning, Sun, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: GRAPE, NUT, RIGHTEOUS. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        6,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Gardens, Pomegranate Tree, The, Saints, Compared To, Usury or Interest, Vine, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        6,
        12,
        "",
        "soul",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Nephesh (<em>נֶפֶשׁ</em>).</strong> properly, a breathing creature, i.e. animal of (abstractly) vitality; used very widely in a literal, accommodated or figurative sense (bodily or mental). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H5315, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        6,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Chariots. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        1,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Shoes, Shoes. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Roe, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        4,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BATH-RABBIM, FISH, FISHPOOL, HESHBON, IVORY. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        4,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fishes, Towers, Towers. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: CARMEL. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        6,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        7,
        7,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Palm Tree, The, Palm Tree, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        8,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APPLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        8,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Palm Tree, The, Vine, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        10,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Church, The, Union With Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: RISING. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Pomegranate Tree, The. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        7,
        13,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: MANDRAKE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        7,
        13,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruits, Herbs, & C. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        1,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BROTHER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        1,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Children. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        2,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: POMEGRANATE, WINE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        2,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Pomegranate Tree, The, Was made of, Was made of. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        3,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Groves. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        4,
        "",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        8,
        5,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: APPLE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        5,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Desert, Journey of Israel Through The, Deserts, Trees. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        6,
        "",
        "heart",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Lêb (<em>לֵב</em>).</strong> the heart; also used (figuratively) very widely for the feelings, the will and even the intellect; likewise for the centre of anything. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H3820, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        8,
        6,
        "a",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        8,
        6,
        "b",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: JEALOUSY, LOVE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        6,
        "c",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Fruit of, illustrative, High Priest, The, Love to Christ, Seals. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        7,
        "",
        "waters",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>Mayim (<em>מַיִם</em>).</strong> water; figuratively, juice; by euphemism, urine, semen. <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H4325, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        8,
        7,
        "a",
        "man",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâdâm (<em>אָדָם</em>).</strong> ruddy i.e. a human being (an individual or the species, mankind, etc.). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H120, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        8,
        7,
        "b",
        "love",
        "lang-hebrew",
        "Hebrew",
        "Hebrew.",
        "<strong>ʼâhab (<em>אָהַב</em>).</strong> to have affection for (sexually or otherwise). <em>[Reviewer: extend this with context, theological reading, and any cross-canon resonance before promoting.]</em>",
        "Strong's H157, A Concise Dictionary of the Words in the Hebrew Bible, James Strong (1894). PD.",
    ),
    (
        8,
        7,
        "c",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: LOVE. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        7,
        "d",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Love of Christ, The, Love to Christ. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        9,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: SILVER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        9,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Often as punishment, Walls. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        10,
        "",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Towers, Walls, Walls. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        11,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: BAAL-HAMON, GRAPE, VINEYARD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        11,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Vineyards, Vineyards. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        12,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: VINEYARD. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        12,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Vineyards. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    (
        8,
        14,
        "",
        "",
        "topic-nave",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: DEER. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Nave's Topical Bible, Orville J. Nave (1896). Public domain.",
    ),
    (
        8,
        14,
        "a",
        "",
        "topic-torrey",
        "Topic",
        "Topic.",
        "<strong>Topics.</strong> This verse appears under: Hart, The, Mountains. <em>[Reviewer: pick one topic (typically the first or most theologically loaded), write a 2–3 sentence thematic note, and discard the rest.]</em>",
        "Torrey's New Topical Textbook, R.A. Torrey (1897). Public domain.",
    ),
    # (ch, v, suf, anchor, kind, title, label, body_html),
]

NOTES_SNG = NOTES  # backward-compat alias
