"""Translation: douay-rheims · Book: bel

AUTO-GENERATED by scripts/extract_translation.py.
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "douay-rheims"
BOOK = "bel"
VERSES = [
    (1, 1, "And king Astyages was gathered to his fathers, and Cyrus the Persian received his kingdom."),
    (1, 2, "And Daniel was the king’s guest, and was honoured above all his friends."),
    (
        1,
        3,
        "Now the Babylonians had an idol called Bel: and there were spent upon him every day twelve great measures of fine flour, and forty sheep, and sixty vessels of wine.",
    ),
    (
        1,
        4,
        "The king also worshipped him, and went every day to adore him: but Daniel adored his God. And the king said to him: Why dost thou not adore Bel?",
    ),
    (
        1,
        5,
        "And he answered, and said to him: Because I do not worship idols made with hands, but the living God, that created heaven and earth, and hath power over all flesh.",
    ),
    (
        1,
        6,
        "And the king said to him: Doth not Bel seem to thee to be a living god? Seest thou not how much he eateth and drinketh every day?",
    ),
    (
        1,
        7,
        "Then Daniel smiled and said: O king, be not deceived: for this is but clay within, and brass without, neither hath he eaten at any time.",
    ),
    (
        1,
        8,
        "And the king being angry called for his priests, and said to them: If you tell me not, who it is that eateth up these expenses, you shall die.",
    ),
    (
        1,
        9,
        "But if you can shew that Bel eateth these things, Daniel shall die, because he hath blasphemed against Bel. And Daniel said to the king: Be it done according to thy word.",
    ),
    (
        1,
        10,
        "Now the priests of Bel were seventy, besides their wives, and little ones, and children. And the king went with Daniel into the temple of Bel.",
    ),
    (
        1,
        11,
        "And the priests of Bel said: Behold we go out: and do thou, O king, set on the meats, and make ready the wine, and shut the door fast, and seal it with thy own ring:",
    ),
    (
        1,
        12,
        "And when thou comest in the morning, if thou findest not that Bel hath eaten up all, we will suffer death, or else Daniel that hath lied against us.",
    ),
    (
        1,
        13,
        "And they little regarded it, because they had made under the table a secret entrance, and they always came in by it, and consumed those things.",
    ),
    (
        1,
        14,
        "So it came to pass after they were gone out, the king set the meats before Bel: and Daniel commanded his servants, and they brought ashes, and he sifted them all over the temple before the king: and going forth they shut the door, and having sealed it with the king’s ring, they departed.",
    ),
    (
        1,
        15,
        "But the priests went in by night, according to their custom, with their wives and their children: and they ate and drank up all.",
    ),
    (1, 16, "And the king arose early in the morning, and Daniel with him."),
    (1, 17, "And the king said: Are the seals whole, Daniel? And he answered: They are whole, O king."),
    (
        1,
        18,
        "And as soon as he had opened the door, the king looked upon the table, and cried out with a loud voice: Great art thou, O Bel, and there is not any deceit with thee.",
    ),
    (
        1,
        19,
        "And Daniel laughed: and he held the king that he should not go in: and he said: Behold the pavement, mark whose footsteps these are.",
    ),
    (1, 20, "And the king said: I see the footsteps of men, and women, and children. And the king was angry."),
    (
        1,
        21,
        "Then he took the priests, and their wives, and their children: and they shewed him the private doors by which they came in, and consumed the things that were on the table.",
    ),
    (
        1,
        22,
        "The king therefore put them to death, and delivered Bel into the power of Daniel: who destroyed him, and his temple.",
    ),
    (1, 23, "And there was a great dragon in that place, and the Babylonians worshipped him."),
    (
        1,
        24,
        "And the king said to Daniel: Behold thou canst not say now, that this is not a living god: adore him therefore.",
    ),
    (1, 25, "And Daniel said: I adore the Lord my God: for he is the living God: but that is no living god."),
    (
        1,
        26,
        "But give me leave, O king, and I will kill this dragon without sword or club. And the king said: I give thee leave.",
    ),
    (
        1,
        27,
        "Then Daniel took pitch, and fat, and hair, and boiled them together: and he made lumps, and put them into the dragon’s mouth, and the dragon burst asunder. And he said: Behold him whom you worshipped.",
    ),
    (
        1,
        28,
        "And when the Babylonians had heard this, they took great indignation: and being gathered together against the king, they said: The king is become a Jew. He hath destroyed Bel, he hath killed the dragon, and he hath put the priests to death.",
    ),
    (1, 29, "And they came to the king, and said: Deliver us Daniel, or else we will destroy thee and thy house."),
    (
        1,
        30,
        "And the king saw that they pressed upon him violently: and being constrained by necessity he delivered Daniel to them.",
    ),
    (1, 31, "And they cast him into the den of lions, and he was there six days."),
    (
        1,
        32,
        "And in the den there were seven lions, and they had given to them two carcasses every day, and two sheep: but then they were not given unto them, that they might devour Daniel.",
    ),
    (
        1,
        33,
        "Now there was in Judea a prophet called Habacuc, and he had boiled pottage, and had broken bread in a bowl: and was going into the field, to carry it to the reapers.",
    ),
    (
        1,
        34,
        "And the angel of the Lord said to Habacuc: Carry the dinner which thou hast into Babylon to Daniel, who is in the lions’ den.",
    ),
    (1, 35, "And Habacuc said: Lord, I never saw Babylon, nor do I know the den."),
    (
        1,
        36,
        "And the angel of the Lord took him by the top of his head, and carried him by the hair of his head, and set him in Babylon over the den in the force of his spirit.",
    ),
    (1, 37, "And Habacuc cried, saying: O Daniel, thou servant of God, take the dinner that God hath sent thee."),
    (1, 38, "And Daniel said: Thou hast remembered me, O God, and thou hast not forsaken them that love thee."),
    (1, 39, "And Daniel arose and ate. And the angel of the Lord presently set Habacuc again in his own place."),
    (
        1,
        40,
        "And upon the seventh day the king came to bewail Daniel: and he came to the den, and looked in, and behold Daniel was sitting in the midst of the lions.",
    ),
    (
        1,
        41,
        "And the king cried out with a loud voice, saying: Great art thou, O Lord the God of Daniel. And he drew him out of the lions’ den.",
    ),
    (
        1,
        42,
        "But those that bad been the cause of his destruction, he cast into the den, and they were devoured in a moment before him.",
    ),
]
