"""Translation: douay-rheims · Book: paz

AUTO-GENERATED by scripts/extract_translation.py.
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "douay-rheims"
BOOK = "paz"
VERSES = [
    (1, 1, "And they walked in the midst of the flame, praising God and blessing the Lord."),
    (1, 2, "Then Azarias standing up prayed in this manner, and opening his mouth in the midst of the fire, he said:"),
    (
        1,
        3,
        "Blessed art thou, O Lord, the God of our fathers, and thy name is worthy of praise, and glorious for ever:",
    ),
    (
        1,
        4,
        "For thou art just in all that thou hast done to us, and all thy works are true, and thy ways right, and all thy judgments true.",
    ),
    (
        1,
        5,
        "For thou hast executed true judgments in all the things that thou hast brought upon us, and upon Jerusalem the holy city of our fathers: for according to truth and judgment, thou hast brought all these things upon us for our sins.",
    ),
    (1, 6, "For we have sinned, and committed iniquity, departing from thee: and we have trespassed in all things:"),
    (
        1,
        7,
        "And we have not hearkened to thy commandments, nor have we observed nor done as thou hadst commanded us, that it might go well with us.",
    ),
    (
        1,
        8,
        "Wherefore all that thou hast brought upon us, and every thing that thou hast done to us, thou hast done in true judgment:",
    ),
    (
        1,
        9,
        "And thou hast delivered us into the hands of our enemies that are unjust, and most wicked, and prevaricators, and to a king unjust, and most wicked beyond all that axe upon the earth.",
    ),
    (
        1,
        10,
        "And now we cannot open our mouths: we are become a shame and reproach to thy servants, and to them that worship thee.",
    ),
    (1, 11, "Deliver us not up for ever, we beseech thee, for thy name’s sake, and abolish not thy covenant."),
    (
        1,
        12,
        "And take not away thy mercy from us for the sake of Abraham thy beloved, and Isaac thy servant, and Israel thy holy one:",
    ),
    (
        1,
        13,
        "To whom thou hast spoken, promising that thou wouldst multiply their seed as the stars of heaven, and as the sand that is on the sea shore.",
    ),
    (
        1,
        14,
        "For we, O Lord, are diminished more than any nation, and are brought low in all the earth this day for our sins.",
    ),
    (
        1,
        15,
        "Neither is there at this time prince, or leader, or prophet, or holocaust, or sacrifice, or oblation, or incense, or place of firstfruits before thee,",
    ),
    (1, 16, "That we may find thy mercy: nevertheless in a contrite heart and humble spirit let us be accepted."),
    (
        1,
        17,
        "As in holocausts of rams, and bullocks, and as in thousands of fat lambs: so let our sacrifice be made in thy sight this day, that it may please thee: for there is no confusion to them that trust in thee.",
    ),
    (1, 18, "And now we follow thee with all our heart, and we fear thee, and seek thy face."),
    (
        1,
        19,
        "Put us not to confusion, but deal. with us according to thy meekness, and according to the multitude of thy mercies.",
    ),
    (1, 20, "And deliver us according to thy wonderful works, and give glory to thy name, O Lord:"),
    (
        1,
        21,
        "And let all them be confounded that shew evils to thy servants, let them be confounded in all thy might, and let their strength be broken.",
    ),
    (1, 22, "And let them know that thou art the Lord, the only God, and glorious over all the world."),
    (
        1,
        23,
        "Now the king’s servants that had cast them in, ceased not to heat the furnace with brimstone, and tow, and pitch, and dry sticks,",
    ),
    (1, 24, "And the flame mounted up above the furnace nine and forty cubits:"),
    (1, 25, "And it broke forth, and burnt such of the Chaldeans as it found near the furnace."),
    (
        1,
        26,
        "But the angel of the Lord went down with Azarias and his companions into the furnace: and he drove the flame of the fire out of the furnace,",
    ),
    (
        1,
        27,
        "And made the midst of the furnace like the blowing of a wind bringing dew, and the fire touched them not at all, nor troubled them, nor did them any harm.",
    ),
    (1, 28, "Then these three as with one mouth praised, and glorified, and blessed God in the furnace, saying:"),
    (
        1,
        29,
        "Blessed art thou, O Lord the God of our fathers: and worthy to be praised, and glorified, and exalted above all for ever: and blessed is the holy name of thy glory: and worthy to be praised, and exalted above all in all ages.",
    ),
    (
        1,
        31,
        "Blessed art thou in the holy temple of thy glory: and exceedingly to be praised, and exceeding glorious for ever.",
    ),
    (
        1,
        32,
        "Blessed art thou, that beholdest the depths, and sittest upon the cherubims: and worthy to be praised and exalted above all for ever.",
    ),
    (
        1,
        33,
        "Blessed art thou on the throne of thy kingdom, and exceedingly to be praised, and exalted above all for ever.",
    ),
    (1, 34, "Blessed art thou in the firmament of heaven: and worthy of praise, and glorious for ever."),
    (1, 35, "All ye works of the Lord, bless the Lord: praise and exalt him above all for ever."),
    (1, 36, "O ye heavens, bless the Lord: praise and exalt him above all for ever."),
    (1, 37, "O ye angels of the Lord, bless the Lord: praise and exalt him above all for ever."),
    (1, 38, "O all ye waters that are above the heavens, bless the Lord; praise and exalt him above all for ever."),
    (1, 39, "O all ye powers of the Lord, bless the Lord: praise and exalt him above all for ever."),
    (1, 40, "O ye sun and moon, bless the Lord: praise and exalt him above all for ever."),
    (1, 41, "O ye stars of heaven, bless the Lord: praise and exalt him above all for ever."),
    (1, 42, "O every shower and dew, bless ye the Lord: praise and exalt him above all for ever."),
    (1, 43, "O all ye spirits of God, bless the Lord: praise and exalt him above all for ever."),
    (1, 44, "O ye fire and heat, bless the Lord: praise and exalt him above all for ever."),
    (1, 45, "O ye cold and heat, bless the Lord: praise and exalt him above all for ever."),
    (1, 46, "O ye dews and hoar frosts, bless the Lord: praise and exalt him above all for ever."),
    (1, 47, "O ye nights and days, bless the Lord: praise and exalt him above all for ever."),
    (1, 48, "O ye light and darkness, bless the Lord: praise and exalt him above all for ever."),
    (1, 49, "O ye ice and snow, bless the Lord: praise and exalt him above all for ever."),
    (1, 50, "O ye frost and cold, bless the Lord: praise and exalt him above all for ever."),
    (1, 51, "O ye lightnings and clouds, bless the Lord: praise and exalt him above all for ever."),
    (1, 52, "O let the earth bless the Lord: let it praise and exalt him above all for ever."),
    (1, 53, "O ye mountains and hills, bless the Lord: praise and exalt him above all for ever."),
    (1, 54, "O all ye things that spring up in the earth, bless the Lord: praise and exalt him above all for ever."),
    (1, 55, "O ye fountains, bless the Lord: praise and exalt him above all for ever."),
    (1, 56, "O ye seas and rivers, bless the Lord: praise and exalt him above all for ever."),
    (1, 57, "O ye whales, and all that move in the waters, bless the Lord: praise and exalt him above all for ever."),
    (1, 58, "O all ye fowls of the air, bless the Lord: praise and exalt him above all for ever."),
    (1, 59, "O all ye beasts and cattle, bless the Lord: praise and exalt him above all for ever."),
    (1, 60, "O ye sons of men, bless the Lord, praise and exalt him above all for ever."),
    (1, 61, "O let Israel bless the Lord: let them praise and exalt him above all for ever."),
    (1, 62, "O ye priests of the Lord, bless the Lord: praise and exalt him above all for ever."),
    (1, 63, "O ye servants of the Lord, bless the Lord: praise and exalt him above all for ever."),
    (1, 64, "O ye spirits and souls of the just, bless the Lord: praise and exalt him above all for ever."),
    (1, 65, "O ye holy and humble of heart, bless the Lord: praise and exalt him above all for ever."),
    (
        1,
        66,
        "O Ananias, Azarias, and Misael, bless ye the Lord: praise and exalt him above all for ever. For he hath delivered us from hell, and saved us out of the hand of death, and delivered us out of the midst of the burning flame, and saved us out of the midst of the fire.",
    ),
    (1, 67, "O give thanks to the Lord, because he is good: because his mercy endureth for ever and ever."),
    (
        1,
        68,
        "O all ye religious, bless the Lord the God of gods: praise him and give him thanks, because his mercy endureth for ever and ever.",
    ),
]
