"""Translation: douay-rheims · Book: sus

AUTO-GENERATED by scripts/extract_translation.py.
Do not edit by hand — re-run extraction to regenerate.
"""

TRANSLATION = "douay-rheims"
BOOK = "sus"
VERSES = [
    (1, 1, "Now there was a man that dwelt in Babylon, and his name was Joakim:"),
    (
        1,
        2,
        "And he took a wife whose name was Susanna, the daughter of Helcias, a very beautiful woman, and one that feared God.",
    ),
    (1, 3, "For her parents being just, had instructed their daughter according to the law of Moses."),
    (
        1,
        4,
        "Now Joakim was very rich, and had an orchard near his house: and the Jews resorted to him, because he was the most honourable of them all.",
    ),
    (
        1,
        5,
        "And there were two of the ancients of the people appointed judges that year, of whom the Lord said: Iniquity came out from Babylon from the ancient judges, that seemed to govern the people.",
    ),
    (1, 6, "These men frequented the house of Joakim, and all that had any matters of judgment came to them."),
    (1, 7, "And when the people departed away at noon, Susanna went in, and walked in her husband’s orchard."),
    (1, 8, "And the old men saw her going in every day, and walking: and they were inflamed with lust towards her:"),
    (
        1,
        9,
        "And they perverted their own mind and turned away their eyes that they might not look unto heaven, nor remember just judgments.",
    ),
    (
        1,
        10,
        "So they were both wounded with the love of her, yet they did not make known their grief one to the other:",
    ),
    (1, 11, "For they were ashamed to declare to one another their lust, being desirous to have to do with her."),
    (1, 12, "And they watched carefully every day to see her. And one said to the other:"),
    (1, 13, "Let us now go home, for it is dinner time. So going out they departed one from another."),
    (
        1,
        14,
        "And turning back again, they came both to the same place: and asking one another the cause, they acknowledged their lust; and then they agreed upon a time, when they might find her alone.",
    ),
    (
        1,
        15,
        "And it fell out, as they watched a fit day, she went in on a time, as yesterday and the day before, with two maids only, and was desirous to wash herself in the orchard: for it was hot weather.",
    ),
    (1, 16, "And there was nobody there, but the two old men that had hid themselves and were beholding her."),
    (
        1,
        17,
        "So she said to the maids: Bring me oil, and washing balls, and shut the doors of the orchard, that I may wash me.",
    ),
    (
        1,
        18,
        "And they did as she bade them: and they shut the doors of the orchard, and went out by a back door to fetch what she had commanded them, and they knew not that the elders were hid within.",
    ),
    (1, 19, "Now when the maids were gone forth, the two elders arose, and ran to her, and said:"),
    (
        1,
        20,
        "Behold the doors of the orchard are shut, and nobody seeth us, and we are in love with thee: wherefore consent to us, and lie with us.",
    ),
    (
        1,
        21,
        "But if thou wilt not, we will bear witness against thee, that a young man was with thee, and therefore thou didst send away thy maids from thee.",
    ),
    (
        1,
        22,
        "Susanna sighed, and said: I am straitened on every side: for if I do this thing, it is death to me: and if I do it not, I shall not escape your hands.",
    ),
    (1, 23, "But it is better for me to fall into your hands without doing it, than to sin in the sight of the Lord."),
    (1, 24, "With that Susanna cried out with a loud voice: and the elders also cried out against her."),
    (1, 25, "And one of them ran to the door of the orchard, and opened it."),
    (
        1,
        26,
        "So when the servants of the house heard the cry in the orchard, they rushed in by the back door to see what was the matter.",
    ),
    (
        1,
        27,
        "But after the old men had spoken, the servants were greatly ashamed: for never had there been any such word said of Susanna. And on the next day,",
    ),
    (
        1,
        28,
        "When the people were come to Joakim her husband, the two elders also came full of wicked device against Susanna, to put her to death.",
    ),
    (
        1,
        29,
        "And they said before the people: Send to Susanna daughter of Helcias the wife of Joakim. And presently they sent.",
    ),
    (1, 30, "And she came with her parents, and children, and all her kindred."),
    (1, 31, "Now Susanna was exceeding delicate, and beautiful to behold."),
    (
        1,
        32,
        "But those wicked men commanded that her face should be uncovered, (for she was covered,) that so at least they might be satisfied with her beauty.",
    ),
    (1, 33, "Therefore her friends and all her acquaintance wept."),
    (1, 34, "But the two elders rising up in the midst of the people, laid their hands upon her head."),
    (1, 35, "And she weeping looked up to heaven, for her heart had confidence in the Lord."),
    (
        1,
        36,
        "And the elders said: As we walked in the orchard alone, this woman came in with two maids, and shut the doors of the orchard, and sent away the maids from her.",
    ),
    (1, 37, "Then a young man that was there hid came to her, and lay with her."),
    (
        1,
        38,
        "But we that were in a corner of the orchard, seeing this wickedness, ran up to them, and we saw them lie together.",
    ),
    (1, 39, "And him indeed we could not take, because he was stronger than us, and opening the doors be leaped out:"),
    (
        1,
        40,
        "But having taken this woman, we asked who the young man was, but she would not tell us: of this thing we are witnesses.",
    ),
    (
        1,
        41,
        "The multitude believed them as being the elders and the judges of the people, and they condemned her to death.",
    ),
    (
        1,
        42,
        "Then Susanna cried out with a loud voice, and said: O eternal God, who knowest hidden things, who knowest all things before they come to pass,",
    ),
    (
        1,
        43,
        "Thou knowest that they have borne false witness against me: and behold I must die, whereas I have done none of these things, which these men have maliciously forged against me.",
    ),
    (1, 44, "And the Lord heard her voice."),
    (
        1,
        45,
        "And when she was led to be put to death, the Lord raised up the holy spirit of a young boy, whose name was Daniel.",
    ),
    (1, 46, "And he cried out with a loud voice I am clear from the blood of this woman."),
    (1, 47, "Then all the people turning themselves towards him, said: What meaneth this word that thou hast spoken?"),
    (
        1,
        48,
        "But he standing in the midst of them, said: Are ye so foolish, ye children of Israel, that without examination or knowledge of the truth, you have condemned a daughter of Israel?",
    ),
    (1, 49, "Return to judgment, for they have borne false witness against her."),
    (
        1,
        50,
        "So all the people turned again in haste, and the old men said to him: Come, and sit thou down among us, and shew it as: seeing God hath given thee the honour of old age.",
    ),
    (1, 51, "And Daniel said to the people: Separate these two far from one another, and I will examine them."),
    (
        1,
        52,
        "So when they were put asunder one from the other, he called one of them, and said to him: O thou that art grown old in evil days, now are thy sins come out, which thou hast committed before:",
    ),
    (
        1,
        53,
        "In judging unjust judgments, oppressing the innocent, and letting the guilty to go free, whereas the Lord saith: I The innocent and the just thou shalt not kill.",
    ),
    (
        1,
        54,
        "Now then, if thou sawest her, tell me under what tree thou sawest them conversing together. He said: Under a mastic tree.",
    ),
    (
        1,
        55,
        "And Daniel said: Well hast thou lied against thy own head: for behold the angel of God having received the sentence of him, shall cut thee in two.",
    ),
    (
        1,
        56,
        "And having put him aside, he commanded that the other should come, and he said to him: O thou seed of Chanaan, and not of Juda, beauty hath deceived thee, and lust hath perverted thy heart:",
    ),
    (
        1,
        57,
        "Thus did you do to the daughters of Israel, and they for fear conversed with you: but a daughter of Juda would not abide your wickedness.",
    ),
    (
        1,
        58,
        "Now therefore tell me, under what tree didst thou take them conversing together. And he answered: Under a holm tree.",
    ),
    (
        1,
        59,
        "And Daniel said to him: Well hast thou also lied against thy own head: for the angel of the Lord waiteth with a sword to cut thee in two, and to destroy you.",
    ),
    (
        1,
        60,
        "With that all the assembly cried out with a loud voice, and they blessed God, who saveth them that trust in him.",
    ),
    (
        1,
        61,
        "And they rose up against the two elders, (for Daniel had convicted them of false witness by their own mouth,) and they did to them as they had maliciously dealt against their neighbour,",
    ),
    (1, 62, "To fulfill the law of Moses: and they put them to death, and innocent blood was saved in that day."),
    (
        1,
        63,
        "But Helcias and his wife praised God, for their daughter Susanna, with Joakim her husband, and all her kindred, because there was no dishonesty found in her.",
    ),
    (1, 64, "And Daniel became great in the sight of the people from that day, and thenceforward."),
]
